- roles/ipaclient/tasks/install.yml
In the client krb5.conf setup, a pkinit_anchors entry was being added for pki-ca-bundle.  This should instead be kdc-ca-bundle.
> change pkinit_anchors to kdc-ca-bundle

- roles/ipaclient/tasks/install.yml
When the client already has a working keytab, use_otp is disabled. This creates
an issue when ipaclient_force_join is set, because the join module is called
with ipaadmin_principal and ipaadmin_password, but these variables may be
undefined if ipaadmin_keytab is used instead.
We should not disable OTP when force-join is specified.
> Fix otp + force-join usecase

- roles/ipaserver/library/ipaserver_prepare.py
- roles/ipaserver/library/ipaserver_test.py
- roles/ipaserver/tasks/install.yml
force and allow_zone_overlap options were missing from a couple places.
Signed-off-by: Scott Poore <spoore@redhat.com>
> server install force and allow_zone_overlap fixes

- roles/ipaclient/tasks/python_2_3_test.yml
- roles/ipareplica/tasks/python_2_3_test.yml
- roles/ipaserver/tasks/python_2_3_test.yml
- Do not register a change in the playbook run when registering the
variable checking for whether or not Python 3 imports work
Signed-off-by: Kellin <kellin@retromud.org>
> Capturing python3 check result is not a change

- roles/ipaserver/library/ipaserver_setup_ca.py
I have lowered the version here to 4.5.04 (current on CentOS 7.5)
Otherwise the execution fails on CentOS 7.5
> Lowered Version for Setup CA | Tested on CentOS 7.5

- roles/ipaclient/library/ipadiscovery.py
- roles/ipaserver/library/ipaserver_test.py
Fixes the error
```
File \"/tmp/ansible_ipaserver_test_payload_Ifhk4f/__main__.py\", line 264, in main\r\nTypeError: fail_json() takes exactly 1 argument (2 given)
```
> Fixes #51 upstream

- roles/ipaclient/library/ipaclient_test.py
When using ipaclient to join an IDM domain without having an ipaservers variable defined then the `TASK [ipaclient : Install - IPA client test]` fails with the below backtrace.
```
Traceback (most recent call last):
File \"/root/.ansible/tmp/ansible-tmp-1557337129.19-136008642669454/AnsiballZ_ipaclient_test.py\", line 113, in <module>
_ansiballz_main()
File \"/root/.ansible/tmp/ansible-tmp-1557337129.19-136008642669454/AnsiballZ_ipaclient_test.py\", line 105, in _ansiballz_main
invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
File \"/root/.ansible/tmp/ansible-tmp-1557337129.19-136008642669454/AnsiballZ_ipaclient_test.py\", line 48, in invoke_module
imp.load_module('__main__', mod, module, MOD_DESC)
File \"/tmp/ansible_ipaclient_test_payload_hgIJdW/__main__.py\", line 892, in …
```
> Fix errors when ipaservers variable is not set

- roles/ipaclient/tasks/install.yml
- roles/ipaclient/tasks/uninstall.yml
- roles/ipareplica/tasks/install.yml
- roles/ipareplica/tasks/uninstall.yml
- roles/ipaserver/tasks/install.yml
- roles/ipaserver/tasks/uninstall.yml
The use of squash_actions to invoke a package module, such as “yum”, to only invoke the module once is deprecated, and will be removed in Ansible 2.11. Instead of relying on implicit squashing, tasks should instead supply the list directly to the name, pkg or package parameter of the module.
[Reference to the upstream documentation.](https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.7.html#using-a-loop-on-a-package-module-via-squash-actions)
The ipa-krb5 and ipa-sssd modules include *_packages variables in both defaults/ and vars/, additionally, the list of packages in ipa-sssd differs from one to the other.
Unify list of packages into vars/
> Fixes #17 Improve how tasks manage package installation

- roles/ipareplica/library/ipareplica_test.py
This is the fix for the following when `ipareplica_ip_addresses` is defined:
```
TASK [ipareplica : Install - Replica installation test] ******************************************************************************************************************************************************************************************************************************************************
fatal: [hhh]: FAILED! => {"changed": false, "msg": "invalid IP address <IP>: global name 'CheckedIPAddress' is not defined"}
```
> Fixed wrong path to CheckedIPAddress class

- README.md
- roles/ipaclient/vars/Debian.yml
Added correct freeipa-client package for debian. Tried to do this already in #98 but messed it up.
> Add debian support for ipaclient

- plugins/modules/ipatopologysegment.py
With adding the domain and ca suffixes with `suffix: domain+ca` only ca
has been added as the suffix was only used from the last command. The
suffix is now stored together with the command and the argument. This
will fix this error.
Fixes: #106 (Last suffix adding twice in the list of topology segments)
> ipatopologysegment: Store suffix for commands in command list

- README-hostgroup.md
- README.md
- playbooks/hostgroup/ensure-hostgroup-is-absent.yml
- playbooks/hostgroup/ensure-hostgroup-is-present.yml
- playbooks/hostgroup/ensure-hosts-and-hostgroups-are-absent-in-hostgroup.yml
- playbooks/hostgroup/ensure-hosts-and-hostgroups-are-present-in-hostgroup.yml
- plugins/modules/ipahostgroup.py
There is a new hostgroup management module placed in the plugins folder:
plugins/modules/ipahostgroup.py
The hostgroup module allows to add, remove and disable hosts.
The hostgroup module is as compatible as possible to the Ansible upstream
ipa_hostgroup module, but addtionally offers to ensure member presence and
absence.
README-hostgroup.md
playbooks/hostgroup/ensure-hostgroup-is-absent.yml
playbooks/hostgroup/ensure-hostgroup-is-present.yml
playbooks/hostgroup/ensure-hosts-and-hostgroups-are-absent-in-hostgroup.yml
playbooks/hostgroup/ensure-hosts-and-hostgroups-are-present-in-hostgroup.yml
> New hostgroup management module

- README-sudocmd.md
- README.md
- playbooks/sudocmd/ensure-sudocmd-is-absent.yml
- playbooks/sudocmd/ensure-sudocmd-is-present.yml
- plugins/modules/ipasudocmd.py
- tests/sudocmd/test_sudocmd.yml
There is a new sudocmd management module placed in the plugins folder:
plugins/modules/ipasudocmd.py
The sudocmd module allows to add or remove sudo commands.
The sudocmd module is as compatible as possible to the Ansible upstream
ipa_sudocmd module.
README-sudocmd.md
playbooks/sudocmd/ensure-sudocmd-is-absent.yml
playbooks/sudocmd/ensure-sudocmd-is-present.yml
Signed-off-by: Rafael Guterres Jeffman <rjeffman@redhat.com>
> New sudocmd management module.

- README-pwpolicy.md
- README.md
- playbooks/pwpolicy/pwpolicy_absent.yml
- playbooks/pwpolicy/pwpolicy_present.yml
- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipapwpolicy.py
- tests/pwpolicy/test_pwpolicy.yml
New pwpolicy management module
There is a new pwpolicy management module placed in the plugins folder:
plugins/modules/ipapwpolicy.py
The pwpolicy module allows to ensure presence and absence of pwpolicies for
groups.
README-pwpolicy.md
playbooks/pwpolicy/pwpolicy_absent.yml
playbooks/pwpolicy/pwpolicy_present.yml
New tests added for pwpolicy:
tests/pwpolicy/test_pwpolicy.yml
---
ansible_freeipa_module: Convert int to string in compare_args_ipa
With IPA 4.5 integers for examle in pwpolicy_find are returned as
integer values. The internally generated value will be converted from
integer to string (using to_text) if the value from find call result
is a string (or unicode for Python2).
> Ipapwpolicy

- README-hbacsvc.md
- README.md
- playbooks/hbacsvc/ensure-hbacsvc-absent.yml
- playbooks/hbacsvc/ensure-hbacsvc-present.yml
- plugins/modules/ipahbacsvc.py
- tests/hbacsvc/test_hbacsvc.yml
There is a new hbacsvc (HBAC Service) management module placed in the plugins
folder:
plugins/modules/ipahbacsvc.py
The hbacsvc module allows to ensure presence and absence of HBAC Services.
README-hbacsvc.md
playbooks/hbacsvc/ensure-hbacsvc-absent.yml
playbooks/hbacsvc/ensure-hbacsvc-present.yml
New tests added for pwpolicy:
tests/hbacsvc/test_hbacsvc.yml
> New hbacsvc (HBAC Service) management module

- README-hbacsvcgroup.md
- README.md
- playbooks/hbacsvcgroup/ensure-hbacsvcgroup-absent.yml
- playbooks/hbacsvcgroup/ensure-hbacsvcgroup-member-absent.yml
- playbooks/hbacsvcgroup/ensure-hbacsvcgroup-member-present.yml
- playbooks/hbacsvcgroup/ensure-hbacsvcgroup-present.yml
- plugins/modules/ipahbacsvcgroup.py
- tests/hbacsvcgroup/test_hbacsvcgroup.yml
There is a new hbacsvcgroup (HBAC Service Group) management module placed
in the plugins folder:
plugins/modules/ipahbacsvcgroup.py
The hbacsvc module allows to ensure presence and absence of HBAC Service
Groups.
README-hbacsvcgroup.md
playbooks/hbacsvcgroup/ensure-hbacsvcgroup-absent.yml
playbooks/hbacsvcgroup/ensure-hbacsvcgroup-member-absent.yml
playbooks/hbacsvcgroup/ensure-hbacsvcgroup-member-present.yml
playbooks/hbacsvcgroup/ensure-hbacsvcgroup-present.yml
New tests added for the module:
tests/hbacsvcgroup/test_hbacsvcgroup.yml
> New hbacsvcgroup (HBAC Service Group) management module

- README-group.md
- plugins/modules/ipagroup.py
group_add_member is only supporting services in more recent IPA versions.
This is 4.7+. Code has been added to detect if services are supported by
the used IPA version and used in the parameters of the module. In this case
an error is printed.
Additionally all parameters will be get from the module using
module_params_get provided by ansible_freeipa_module. Additional to_text
conversions have been removed as they are not needed anymore with this.
> ipagroup: Properly support IPA versions 4.6 and RHEL-7

- plugins/modules/ipagroup.py
- tests/group/test_group.yml
The changed flag returned by ipagroup calls have not been correct. This
change fixes this. Addtitionally new test cases have been added to make
sure that the changed flag is correct.
> ipagroup: Fix changed flag, new test cases

- README-user.md
- plugins/modules/ipauser.py
The information about the version limitation of the passwordexpiration
parameter has been missing. The parameter is only usable for IPA versions
4.7 and up.
> ipauser: Add info about version limitation of passwordexpiration

- README-hbacrule.md
- README.md
- playbooks/hbacrule/ensure-hbarule-allhosts-absent.yml
- playbooks/hbacrule/ensure-hbarule-allhosts-disabled.yml
- playbooks/hbacrule/ensure-hbarule-allhosts-enabled.yml
- playbooks/hbacrule/ensure-hbarule-allhosts-present.yml
- playbooks/hbacrule/ensure-hbarule-allhosts-server-member-absent.yml
- playbooks/hbacrule/ensure-hbarule-allhosts-server-member-present.yml
- plugins/modules/ipahbacrule.py
- tests/hbacrule/test_hbacrule.yml
There is a new hbacrule (HBAC Rule) management module placed in the plugins
folder:
plugins/modules/ipahbacrule.py
The hbacrule module allows to ensure presence and absence of HBAC Rules.
README-hbacrule.md
playbooks/hbacrule/ensure-hbarule-allhosts-absent.yml
playbooks/hbacrule/ensure-hbarule-allhosts-disabled.yml
playbooks/hbacrule/ensure-hbarule-allhosts-enabled.yml
playbooks/hbacrule/ensure-hbarule-allhosts-present.yml
playbooks/hbacrule/ensure-hbarule-allhosts-server-member-absent.yml
playbooks/hbacrule/ensure-hbarule-allhosts-server-member-present.yml
New tests added for the module:
tests/hbacrule/test_hbacrule.yml
> New hbacrule (HBAC Rule) management module

- README-sudorule.md
- README.md
- playbooks/sudorule/ensure-sudorule-host-member-is-absent.yml
- playbooks/sudorule/ensure-sudorule-host-member-is-present.yml
- playbooks/sudorule/ensure-sudorule-hostgroup-member-is-absent.yml
- playbooks/sudorule/ensure-sudorule-hostgroup-member-is-present.yml
- playbooks/sudorule/ensure-sudorule-is-absent.yml
- playbooks/sudorule/ensure-sudorule-is-disabled.yml
- playbooks/sudorule/ensure-sudorule-is-enabled.yml
- playbooks/sudorule/ensure-sudorule-is-present.yml
- playbooks/sudorule/ensure-sudorule-sudocmd-is-absent.yml
- playbooks/sudorule/ensure-sudorule-sudocmd-is-present.yml
- plugins/modules/ipasudorule.py
- tests/sudorule/test_sudorule.yml
There is a new sudorule (Sudo Rule) management module placed in the plugins
folder:
plugins/modules/ipasudorule.py
The sudorule module allows to ensure presence and absence of Sudo Rules.
README-sudorule.md
playbooks/sudorule/ensure-sudorule-host-member-is-absent.yml
playbooks/sudorule/ensure-sudorule-host-member-is-present.yml
playbooks/sudorule/ensure-sudorule-hostgroup-member-is-absent.yml
playbooks/sudorule/ensure-sudorule-hostgroup-member-is-present.yml
playbooks/sudorule/ensure-sudorule-is-absent.yml
playbooks/sudorule/ensure-sudorule-is-disabled.yml
playbooks/sudorule/ensure-sudorule-is-enabled.yml
playbooks/sudorule/ensure-sudorule-is-present.yml …
> New sudorule (Sudo Rule) management module

- plugins/modules/ipahostgroup.py
- tests/hostgroup/test_hostgroup.yml
The changed flag returned by ipahostgroup calls have not always been correct.
The use of the module with IPA version 4.6 on RHEL-7 resulted in encoding
errors. All this has been fixed.
Addtitionally new test cases have been added to make sure that the issues
are solved.
> ipahostgroup: Fix changed flag, support IPA 4.6 on RHEL-7, new test cases

- README-host.md
- README-user.md
- playbooks/host/ensure_host_with_randompassword.yml
- playbooks/user/ensure_user_with_randompassword.yml
- playbooks/user/ensure_users_with_randompasswords.yml
- plugins/modules/ipahost.py
- plugins/modules/ipauser.py
- tests/host/test_host_random.yml
- tests/user/test_user_random.yml
ipauser: Return generated random password
The random password is only returned if random is yes and user did not exist or update_password is yes.
ipahost: Return generated random password
The random password is only returned if random is yes and the host did not exist or update_password is yes.
Fixes issue #134 (ipahost does not return the random password)
> ipauser, ipahost: Return random password

- roles/ipaclient/defaults/main.yml
- roles/ipaclient/tasks/install.yml
- utils/ansible-ipa-client-install
The sssd options in the ipaclient role missed a 's' in the role. The readme
of the role used the proper names with 3 's'. The names in the role have
been fixed and if the old setting are used, they will be used in the first
place.
Also utils/ansible-ipa-client-install has been adaped to use the proper
option names now.
This fixes issue #145 (The ipaclient role misspells sssd)
> ipaclient: Fix misspelled sssd options

- plugins/module_utils/ansible_freeipa_module.py
The use of gssapi.creds.Credentials is not good if krb5 ticket forwarding
is used. It will fail. gssapi.Credentials with usage and store is the proper
way to do this.
> ansible_freeipa_module: Better support for KRB5CCNAME environment variable

- roles/ipaclient/vars/CentOS-8.yml
- roles/ipareplica/vars/CentOS-8.yml
- roles/ipaserver/vars/CentOS-8.yml
The files for RHEL-8 (RedHat-8.yml) have simply been linked to CentOS-8.yml
for the ipaserver, ipareplica and ipaclient roles.
Fixes issue #121 (roles/*/vars needs CentOS-8.yml files)
> ipa[server,replica,client]: Add support for CentOS-8

- plugins/module_utils/ansible_freeipa_module.py
There are some commands in the IPA API that do not require arguments, and current implementation does not allow these commands to be executed.
This patch provides a utility function to allow this behavior, that is required by the vaultcontainer module.
> Allow execution of API commands that do not require parameters.

- roles/ipaserver/library/ipaserver_test.py
The use of zone_overlay_check for the domain name validation is not good
for a repeated execution of the server deployment where setup_dns is
enabled. The zone overlay check will fail with "DNS zone X already exists
in DNS". zone_overlay_check is later on used in dns.install_check so it is
not needed to do it here also.
Fixes issues #164 (domain option validator should not call zone overlap..)
> ipaserver_test: Do not use zone_overlap_check for domain name validation

- README-vault.md
- README.md
- playbooks/vault/data-archive-in-asymmetric-vault.yml
- playbooks/vault/data-archive-in-symmetric-vault.yml
- playbooks/vault/ensure-asymetric-vault-is-absent.yml
- playbooks/vault/ensure-asymetric-vault-is-present.yml
- playbooks/vault/ensure-service-vault-is-absent.yml
- playbooks/vault/ensure-service-vault-is-present.yml
- playbooks/vault/ensure-shared-vault-is-absent.yml
- playbooks/vault/ensure-shared-vault-is-present.yml
- playbooks/vault/ensure-standard-vault-is-absent.yml
- playbooks/vault/ensure-standard-vault-is-present.yml
- playbooks/vault/ensure-symetric-vault-is-absent.yml
- playbooks/vault/ensure-symetric-vault-is-present.yml
- playbooks/vault/ensure-vault-is-present-with-members.yml
- playbooks/vault/ensure-vault-member-group-is-absent.yml
- playbooks/vault/ensure-vault-member-group-is-present.yml
- playbooks/vault/ensure-vault-member-user-is-absent.yml
- playbooks/vault/ensure-vault-member-user-is-present.yml
- playbooks/vault/ensure-vault-owner-is-absent.yml
- playbooks/vault/ensure-vault-owner-is-present.yml
- plugins/modules/ipavault.py
- tests/vault/test_vault.yml
There is a new vault management module placed in the plugins folder:
plugins/modules/ipavault.py
The vault module allows to ensure presence and absence of vaults, manage
members and owner of the vault, and archive and retrieve vault data.
README-vault.md
playbooks/vault/data-archive-in-asymmetric-vault.yml
playbooks/vault/data-archive-in-symmetric-vault.yml
playbooks/vault/data-remove-from-asymmetric-vault.yml
playbooks/vault/data-remove-from-symmetric-vault.yml
playbooks/vault/data-retrieve-from-asymmetric-vault.yml
playbooks/vault/data-retrieve-from-symmetric-vault.yml
playbooks/vault/ensure-asymetric-vault-is-absent.yml
playbooks/vault/ensure-asymetric-vault-is-present.yml …
>  New vault management module.

- README-host.md
- plugins/modules/ipahost.py
The choices for the auth_ind parameter have been wrong. The choices are now
['radius', 'otp', 'pkinit', 'hardened', '']. The empty string has been added
to be able to rest auth_ind for the host entry.
> ipahost: Fix choices of auth_ind parameter, allow to reset parameter

- plugins/modules/ipasudocmd.py
This fixes the issue https://github.com/freeipa/ansible-freeipa/issues/185, where the python script was launching an exception
There was a lack of verification that the input string (for the description  field) was a text string
> Add missing validation in ipasudocmd

- roles/ipareplica/tasks/install.yml
Use ipaserver_realm as a fallback if ipareplica_realm is not defined. This
had been done for ipareplica_domain and ipaserver_domain, but was missing
for ipareplica_realm and ipaserver_realm.
Related: #114 (ipareplica 'Env' object has no attribute 'realm')
> ipareplica: Use ipaserver_realm as a fallback for realm

- README-pwpolicy.md
- plugins/modules/ipapwpolicy.py
- tests/pwpolicy/test_pwpolicy.yml
If the name is not set, the policy global_policy is now used. It was needed
before to explicitly name the global_policy. Also a check has been added
to fail early if global_policy is used with state absent.
The README for pwpolicy has been extended with an example for global_policy
and also the description of the name variable.
The test has also been extended to check a change of maxlife for
global_policy and that global_policy can not be used with state: absent
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1797532
> ipapwpolicy: Use global_policy if name is not set

- plugins/modules/ipahbacrule.py
- tests/hbacrule/test_hbacrule.yml
Changing members (host, hostgroup, hbacsvc, hbacsvcgroup, user, group) with
action hbacrule was not working due to the use of the wrong parameter
prefix. This has been fixed and the old members are removed correctly now.
The test script has been reworked completely to verify the fix.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1787996
> ipahbacrule: Fix handing of members with action hbacrule

- tests/group/test_group.yml
- tests/hbacrule/test_hbacrule.yml
- tests/hbacsvc/test_hbacsvc.yml
- tests/hbacsvcgroup/test_hbacsvcgroup.yml
- tests/hostgroup/test_hostgroup.yml
- tests/pwpolicy/test_pwpolicy.yml
- tests/sudocmd/test_sudocmd.yml
- tests/sudocmdgroup/test_sudocmdgroup.yml
- tests/sudorule/test_sudorule.yml
- tests/user/test_user.yml
- tests/user/test_users.yml
- tests/user/test_users_absent.yml
- tests/user/test_users_present.yml
- tests/user/test_users_present_slice.yml
- tests/vault/test_vault.yml
Most tests have simply been using the Tests as name, but this there is a
lack of information in automated runs. The name should be similar to the
test file name.
> tests: Fix top name tags in tests

- roles/ipareplica/README.md
- roles/ipaserver/README.md
Modify examples in server and replica roles for consistency with client
role, by defining language for code blocks.
> Modify roles README for consistency.

- README-host.md
- playbooks/host/host-member-ipaddresses-absent.yml
- playbooks/host/host-member-ipaddresses-present.yml
- playbooks/host/host-present-with-several-ip-addresses.yml
- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipahost.py
- tests/host/test_host.yml
- tests/host/test_host_ipaddresses.yml
ipahost was so far ignoring IP addresses when the host already existed.
This happened because host_mod is not providing functionality to do this.
Now ipaddress is a list and it is possible to ensure a host with several
IP addresses (these can be IPv4 and IPv6). Also it is possible to ensure
presence and absence of IP addresses for an exising host using action
member.
There are no IP address conclict checks as this would lead into issues with
updating an existing host that already is using a duplicate IP address for
example for round-robin (RR). Also this might lead into issues with ensuring
a new host with several IP addresses in this case. Also to ensure a list of
hosts with changing the IP address of one host to another in the list would
result in issues here.
New example playbooks have …
> ipahost: Add support for several IP addresses and also to change them

- plugins/modules/ipahost.py
The check to make sure that member can not be used on non existing hosts
has bee missing. Also the reverse flag for the dnsrecord_add call was None
if the varaible was not set.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1803026
> ipahost: Fail on action member for new hosts, fix dnsrecord_add reverse flag

- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipahost.py
- tests/host/test_host_ipaddresses.yml
If no IP address is given and either DNS is not configured or if the zone is
not found then ipahost may not fail in dnsrecord_find.
The error happened for example by ensuring the absence of a host that is not
part of the domain or for a host that has been added with force and is using
a domain that is not served by the DNS server in the domain. It also
happened if there was no DNS server in the domain at all.
A new test case has been added to test_host_ipaddresses.yml
The fix requires ipalib_errors provided by ansible_freeipa_module.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1804838
--
ansible_freeipa_module: Import ipalib.errors as ipalib_errors
For beeing able to catch ipalib.errors.NotFound errors in ipahost it is
needed to import ipalib.errors. ipalib.errors is now imported …
> ipahost: Do not fail on missing DNS or zone when no IP address given

- plugins/module_utils/ansible_freeipa_module.py
When implementing the ipaservice module, certificates are returned as
'bytes', and they need to be base64 encoded directly.
> Properly handle certificates stored as bytes in encode_certificate.

- tests/pwpolicy/test_pwpolicy.yml
One test did not use the admin password as the rest of the tests.
This caused the tests/pwpolicy/test_pwpolicy.yml suite to fail.
Changing the password to the same as in others fixes the issue.
Signed-off-by: Petr Vobornik <pvoborni@redhat.com>
> test_pwpolicy: unite admin passwords

- README-group.md
The external parameter was showing type flag instead of type bool.
> README-group: Fix description of external parameter

- README.md
Removed a trailling space on README.md because it was often removed by
text editors, adding an unnecessary line to the update patch.
> Removed trailling space on README.md.

- README-sudorule.md
This patch adds documentation for the sudorule variables `runasusercategory`
and `runasgroupcategory` that was missing.
> Add documentation of missing variables for sudorule.

- README-dnsconfig.md
- README.md
- playbooks/dnsconfig/disable-global-forwarders.yml
- playbooks/dnsconfig/disallow-reverse-sync.yml
- playbooks/dnsconfig/forwarders-absent.yml
- playbooks/dnsconfig/set-configuration.yml
- plugins/modules/ipadnsconfig.py
- tests/dnsconfig/test_dnsconfig.yml
There is a new vaultcontainer management module placed in the plugins folder:
plugins/modules/ipadnsconfig.py
The dnsconfig module allows to modify global DNS configuration.
README-dnsconfig.md
playbooks/dnsconfig/set_configuration.yml
playbooks/dnsconfig/disable-global-forwarders.yml
playbooks/dnsconfig/disallow-reverse-sync.yml
tests/dnsconfig/test_dnsconfig.yml
> New DNSConfig management module

- plugins/modules/ipahost.py
- tests/host/test_host_reverse.yml
Due to setting aaaa_extra_create_reverse or a_extra_create_reverse when not
needed, host module fails to add a host with reverse address. This patch
fixes the behavior  by only adding *_extra_create_reverse when needed.
Fixes issue #226
> Fixes behavior for host module attribute `reverse`

- roles/ipaserver/library/ipaserver_test.py
Gracefully handle RuntimeError raised during parameter validation
in fail_json.
Fixes: #115
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
- Bugfix Pull Request
roles/ipaserver/library/ipaserver_test.py
> Handle RuntimeError in fail_json

- tests/dnsconfig/test_dnsconfig.yml
This change avoid the need to obtain an admin TGT on the testing target before running the tests.
> Add admin password to the ipadnsconfig module tests.

- roles/ipaclient/tasks/install.yml
Keep the valid keytab file pre-existent in the master node. This fixes #191.
**Please, review carefully. It seems to work correctly in my environment but I don't know if there is any possible side effect related to https://github.com/freeipa/ansible-freeipa/commit/f366fb5270c00d289721562d4b8582d48407bf89.**
> Not delete keytab when ipaclient_on_master is true

- plugins/module_utils/ansible_freeipa_module.py
In the case that the admin password has been set and become was not set
the call to backend.connect in api_connect failed. The solution is simply
to set os.environ["KRB5CCNAME"] in temp_kinit after kinit_password has
been called using the temporary ccache. os.environ["KRB5CCNAME"] is not
used automatically by api.Backend.[ldap2,rpcclient].connect.
Fixes: #249 (Kerberos errors while using the modules with a non-sudoer user)
> ansible_freeipa_module: Set KRB5CCNAME for api_connect (non root)

- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipagroup.py
- plugins/modules/ipahbacrule.py
- plugins/modules/ipahbacsvcgroup.py
- plugins/modules/ipahostgroup.py
- plugins/modules/ipasudocmdgroup.py
- plugins/modules/ipauser.py
- tests/user/test_user.yml
- tests/user/test_users.yml
Because of a missing check member attributes (for use with action: member)
are cleared when a non-member attribute is changed. The fix simply adds a
check for None (parameter not set) to gen_add_del_lists in
ansible_freeipa_module to make sure that the parameter is only changed if
it should be changed.
All places where the add and removal lists have been generated manually
have been changed to also use gen_add_del_lists.
Resolves: #252 (The "Manager" attribute is removed when updating any user
attribute)
> Do not remove member attributes while updating others

- plugins/modules/ipavault.py
Even after obtaining Kerberos TGT with temp_kinit(), when connecting to
the IPA API with context `ansible-freeipa`, the API commands complained
that Kerberos credentials were not available. This patch fixes this
behavior.
> Fixes usage of Kerberos credentials on Vault module.

- README-host.md
- plugins/modules/ipahost.py
- tests/host/test_host_random.yml
If random is enabled and update_password is limited to "create_only", the
random password may only be changed if the host does not exist yet.
Additionally the generation of the random password will fail, if the host
is already enrolled if update_password is "always" (default value). An
error will be reported early in this case now.
The command host_show is now used instead of host_find, as `has_password`
and `has_keytab` are only returned by host_show, but not by host_find. The
find_host function has been adapated for this change.
Resolves: #253 (ipahost is not idempotent)
> ipahost: Honour update_password also for random

- plugins/modules/ipahost.py
The host_find command had to be replaced to get the "has_password" and
"has_keytab" return values. This commit replaces the dnsrecord_find
with the dnsrecord_show command to have consistent find functions in
the module.
> ipahost: Use dnsrecord_show instead of dnsrecord_find command

- tests/host/test_hosts_principal.yml
The hosts tag is used twice in some tests. This leads to a warning in
Ansible. The commit removes the duplicate tags.
> tests/host/test_hosts_principal.yml: Remove dudplicate hosts tag

- plugins/modules/ipagroup.py
group_remove_member is not able to handle services in old IPA releases.
In one case the check was missing and the removal of a user from a group
failed because of this with an older IPA version. The missing check has
been added.
Fixes #257 (ipagroup fails to remove user from group ipausers)
> ipagroup: Add lacking service check for group_remove_member with old IPA

- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipagroup.py
- plugins/modules/ipahbacrule.py
- plugins/modules/ipahbacsvcgroup.py
- plugins/modules/ipahostgroup.py
- plugins/modules/ipasudocmdgroup.py
- plugins/modules/ipauser.py
- tests/user/test_user.yml
- tests/user/test_users.yml
The find_user function was not using encode_certificate for certificates
that are stored in the user record. This could lead to some issues with
older ipa releases and Python 2.
> ipauser: Use encode_certificate for certificates in  find_user result

- README-hbacrule.md
- README-sudorule.md
- plugins/modules/ipahbacrule.py
- plugins/modules/ipasudorule.py
- tests/hbacrule/test_hbacrule_categories.yml
- tests/sudorule/test_sudorule_categories.yml
This patch fixes removal of categories with `all` value from `sudorule` and `hbacrule` modules.
> Fixes removal of `all` from categories in sudorule and hbacrule modules.

- README-user.md
- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipauser.py
- tests/user/certmapdata/test_user_certmapdata.yml
ipauser: Fix certmapdata, add missing certmapdata data option
certmapdata was not processed properly. The certificate was not loaded and
therefore the `issuer` and `subject` could not be compared to the
certmapdata entries in the user record. The function `load_cert_from_str`
from ansible_freeipa_moduleis used for this.
Additionally there was no way to use the certmapdata data format. This
is now possible with the `data` option in the certmapdata dict.
Example: "data: X509:<I>dc=com,dc=example,CN=ca<S>dc=com,dc=example,CN=test"
`data` may not be used together with `certificate`, `issuer` and `subject`
in the same record.
Given certmapdata for the ipauser module is now converted to the internal
data representation using also the new function `DN_x500_text` from
`ansible_freeipa_module`. …
> ipauser: Fix certmapdata, add missing certmapdata data option

- README-vault.md
- plugins/modules/ipavault.py
- tests/vault/test_vault.yml
This patch makes the module behavior similar to the IPA CLI command `vault_add`.
Tests are updated to reflect this change.
> Fixes behavior of ipavault when no user, service or shared is given.

- roles/ipaserver/README.md
Corrected variable names and description.
Added useful notes and the missing variable ipaserver_no_pkinit.
> Wrong variable names in the documentation

- README-vault.md
- plugins/modules/ipavault.py
- tests/vault/test_vault.yml
The `services` member attribute was missing from vault module. This
change adds it.
Handling of owner and ownergroups needed to be changed to fix `services`
and, due to this, have also been fixed.
> Add missing attribute `services` to vault module.

- plugins/modules/ipahost.py
- tests/host/test_host_no_zone.yml
Since ipahost uses dnsrecord-show, it raises an error when DNS zone is
not found, but it should not be an ipahost concern.
This patch fixes this behavior by returning no record if DNS zone is
not found, so processing resumes as if there is no record for the host.
It fixes behavior when `state: absent` and dnszone does not exist, so,
host should not exist either, and the ipahost answer is correct and
indifferent to DNS Zone state.
> Fixes host absent when DNS zone is not found.

- plugins/modules/ipauser.py
This patch explicitly set `no_log` option for `update_password` attribute
to `False`, so that the warning on `no_log` not being set is not issued
anymore. Ansible incorrectly issued the warning, as `update_password` does
not carry sensitive information.
> Fixes no_log warning for `update_password`.

- README-service.md
- plugins/modules/ipaservice.py
- plugins/modules/ipauser.py
- tests/service/test_service.yml
This PR fixes some issues found with the ipaservice module:
- Wrong error message when adding pac_type with `action: member`.
- Wrong error message when adding a service with missing service name.
- Not possible to add more than one `auth_ind`.
- Not possible to clear `auth_ind`.
- Wrong option `enabled` for `state` removed from documentation and module variables.
- Support for option `continue` when `state: absent`.
- Support for `service-add-smb`.
The issues are fixed with this PR, and details can be found in the individual commits.
> Fix service module

- README-group.md
- plugins/modules/ipagroup.py
- tests/group/test_group_membermanager.yml
A group membership manager is a user or a group that can add members to
a group or remove members from a group.
This is related to https://pagure.io/freeipa/issue/8114
New parameters have been added to the module:
- `membermanager_user`: List of member manager users assigned to this
group. Only usable with IPA versions 4.8.4 and up.
- `membermanager_group`: List of member manager groups assigned to this
group. Only usable with IPA versions 4.8.4 and up.
These parameters behave like member parameters.
A new test has been added:
- tests/group/test_group_membermanager.yml
> ipagroup: Add support for group membership management

- README-hostgroup.md
- plugins/modules/ipahostgroup.py
- tests/hostgroup/test_hostgroup_membermanager.yml
A group membership manager is a user or a group that can add members to
a group or remove members from a hostgroup.
This is related to https://pagure.io/freeipa/issue/8114
New parameters have been added to the module:
- `membermanager_user`: List of member manager users assigned to this
group. Only usable with IPA versions 4.8.4 and up.
- `membermanager_group`: List of member manager groups assigned to this
group. Only usable with IPA versions 4.8.4 and up.
These parameters behave like member parameters.
A new test has been added:
- tests/hostgroup/test_hostgroup_membermanager.yml
> ipahostgroup: Add support for group membership management

- README-dnsrecord.md
- README-service.md
- README.md
- playbooks/dnsrecord/ensure-A-and-AAAA-records-are-absent.yml
- playbooks/dnsrecord/ensure-A-and-AAAA-records-are-present.yml
- playbooks/dnsrecord/ensure-CNAME-record-is-absent.yml
- playbooks/dnsrecord/ensure-CNAME-record-is-present.yml
- playbooks/dnsrecord/ensure-MX-record-is-present.yml
- playbooks/dnsrecord/ensure-PTR-record-is-present.yml
- playbooks/dnsrecord/ensure-SRV-record-is-present.yml
- playbooks/dnsrecord/ensure-SSHFP-record-is-present.yml
- playbooks/dnsrecord/ensure-TLSA-record-is-present.yml
- playbooks/dnsrecord/ensure-TXT-record-is-present.yml
- playbooks/dnsrecord/ensure-URI-record-is-present.yml
- playbooks/dnsrecord/ensure-dnsrecord-is-absent.yml
- playbooks/dnsrecord/ensure-dnsrecord-is-present.yml
- playbooks/dnsrecord/ensure-dnsrecord-with-reverse-is-present.yml
- playbooks/dnsrecord/ensure-multiple-A-records-are-present.yml
- playbooks/dnsrecord/ensure-presence-multiple-records.yml
- plugins/modules/ipadnsrecord.py
- plugins/modules/ipaservice.py
- tests/dnsrecord/env_cleanup.yml
- tests/dnsrecord/env_setup.yml
- tests/dnsrecord/env_vars.yml
- tests/dnsrecord/test_compatibility_with_ansible_module.yml
- tests/dnsrecord/test_dnsrecord.yml
- tests/dnsrecord/test_dnsrecord_full_records.yml
- tests/service/test_service.yml
There is a new dnsrecord managem module placed in the plugins folder:
plugins/modules/ipadnsrecord.py
The dnsrecord module allows management of DNS records and is as compatible
as possible with the Ansible upstream `ipa_dnsrecord` module, but provide
some other features like multiple record management in one execution,
support for more DNS record types, and more.
README-dnsrecord
playbooks/dnsrecord/ensure-A-and-AAAA-records-are-absent.yml
playbooks/dnsrecord/ensure-A-and-AAAA-records-are-present.yml
playbooks/dnsrecord/ensure-CNAME-record-is-absent.yml
playbooks/dnsrecord/ensure-CNAME-record-is-present.yml
playbooks/dnsrecord/ensure-MX-record-is-present.yml …
> New dnsrecord management module.

- README-config.md
- playbooks/config/retrieve-config.yml
- playbooks/config/set-ca-renewal-master-server.yml
- plugins/modules/ipaconfig.py
- tests/config/test_config.yml
module to ensure that the global configuration options are set. It needs a small fix to ansible_freeipa_module.py to handle calling api commands without a named object which throws an exception without this fix.
> add an ipaconfig module

- tests/README.md
- tests/test_playbook_runs.py
Running test_playbook_runs.py would result of running only the last collected test but showing the name of the other tests instead.
To fix that the `test_path` was moved to an argument set by a method decorator.
> Fix all tests entry point

- plugins/modules/ipahbacrule.py
- plugins/modules/ipasudorule.py
- tests/hbacrule/test_hbacrule_categories.yml
- tests/sudorule/test_sudorule_categories.yml
Current implementation of hbacrule and sudorule allow for a new rule
creation script to be partialy successful when a member is provided and
the respective member category is set to `all` (either users, hosts,
services, commands, and their group counterparts).
Since the creation of the rule is independent of the adittion of members,
the rule is succesfully created, but member addition fails, leaving with
a created rule that has no members on it.
This patch fixes both modules by verifying if user, host, service or
commands (and groups of members) are being added if the corresponding
category is set to `all`, when the state is `present` and the action is
not `member`. If so, it fails before the rule is created.
> Fixes attempt to create rules with members when category is `all`.

- roles/ipaserver/library/ipaserver_setup_ca.py
The ca-less PR introduced a bug when http_ca_cert is not set. The test
for loading the certificate is testing for None, but the string will only
be empty in this case.
Related: #298 (Install server and replicas without CA)
> ipaserver/library/ipaserver_setup_ca.py: Fix bug introduced with ca-less PR

- README-dnsforwardzone.md
- plugins/modules/ipadnsforwardzone.py
- tests/dnsforwardzone/test_dnsforwardzone.yml
This PR adresses several issues on ipadnsforwardzone module:
* Change ipaadmin_password in tests to ease test automation;
* Allow exclusion of multiple zones in the same playbook;
* Fix error messages in several places;
* Add support for defining forwarders with `ip_address` and `port`, using variables;
* Add support for attribute `permission`;
* Allow modification of forward policy;
Please, see individual commits for more details.
> Fix forwardzone issues

- plugins/modules/ipaservice.py
- tests/service/test_service_disable.yml
Services without certificates, but with keytabs were not being
disabled. This change allows execution of service_disable if
there is a certificate or if has_keytab is true.
A new test was added to verify the issue:
tests/service/test_service_disable.yml
> Fixes service disable when service has no certificates attached.

- README-vault.md
- playbooks/vault/change-password-symmetric-vault.yml
- plugins/modules/ipavault.py
- tests/vault/test_vault_symmetric.yml
Allows changing passwords of symmetric waults, using a new variable
`new_password` (or the file-base version, `new_password_file`). The
old password must be passed using the `password` or `password_file`
variables that also received new aliases `old_password` and
`old_password_file`, respectively.
Tests were modyfied to reflect the changes.
> Add suppport for changing password of symmetric vaults.

- plugins/modules/ipagroup.py
- plugins/modules/ipahostgroup.py
- tests/group/test_group_membermanager.yml
- tests/hostgroup/test_hostgroup_membermanager.yml
If a unknown membermanager user presence will be ensured, the unknown user
error was ignored. This has been fixed in ipagroup. The code for the error
handling in ipagroup and ipahostgroup has been adapted because of this.
New tests for tests/[host]group/test_[host]group_membermnager.yml have been
added.
> ipa[host]group: Fix membermanager unknow user issue

- plugins/modules/ipahost.py
- plugins/modules/ipauser.py
- tests/host/test_hosts.yml
- tests/user/test_users.yml
It was possible to have several entries for names with the hosts and users
lists. This resulted sometimes in errors but also unexpected changes. A new
check has been added to make sure that the names in the users and hosts
lists are unique.
New tests have been added to verify this in the existing files:
- tests/host/test_hosts.yml
- tests/user/test_users.yml
> ipa[user,host]: Fail on duplucate names in the users and hosts lists

- tests/service/test_service_disable.yml
Due to use of some shell commands that required a Kerberos ticket,
the ipaservice test test_service_disable would no work if a ticket
was not granted before it ran. This patch adresses this issue by
acquiring a ticket for the `admin` user before it is needed, and
destroying the tickets by the end of the test execution.
> Fixes ipaservice disable tests.

- roles/ipaclient/action_plugins/ipaclient_get_otp.py
- roles/ipaclient/tasks/install.yml
Ansible is now also supporting discovered_python_interpreter for
action_plugins. task_vars needs to be non Null and contain a setting for
discovered_python_interpreter. The ipaclient_get_otp action_plugin
therefore needed to be adapted.
> action_plugins/ipaclient_get_otp: Discovered python needed in task_vars

- roles/ipareplica/tasks/install.yml
- roles/ipaserver/tasks/install.yml
With the CA-less patches the types for the pkcs12 infos have been changed
to lists in the modules. This is resulting in a bad conversion from None
to [''] for the parameters. Because of this a normal replica deployment is
failing as [''] is not a valid value.
The install.yml files for ipareplica and also ipaserver have been changed
in the way that the pkcs12 values are checked if they are None. The
parameter will simply be omitted in this case and the parameter in the
module will become None by default.
> ipa[server,replica]: Fix pkcs12 info regressions introduced with CA-less

- roles/ipareplica/library/ipareplica_create_ipa_conf.py
- roles/ipareplica/library/ipareplica_ds_apply_updates.py
- roles/ipareplica/library/ipareplica_ds_enable_ssl.py
- roles/ipareplica/library/ipareplica_setup_adtrust.py
- roles/ipareplica/library/ipareplica_setup_custodia.py
- roles/ipareplica/library/ipareplica_setup_http.py
- roles/ipareplica/library/ipareplica_setup_kra.py
- roles/ipareplica/library/ipareplica_setup_krb.py
- roles/ipareplica/tasks/install.yml
The parameters master_host_name, config_setup_ca, dirman_password have not
been set for some modules. Also there was no ldap2 connection within
ipareplica_setup_kra. All this resulted in improper configuration where
for example KRA deployment failed in the end.
A conversion warning in ipareplica_setup_adtrust has also been fixed for
the setup_ca parameter.
Fixes #314 (IPA replica installation failure - DS enabled SSL - second part)
> ipareplica: Fix missing parameters for several modules

- README-role.md
- README.md
- playbooks/role/role-is-absent.yml
- playbooks/role/role-is-present.yml
- playbooks/role/role-member-group-absent.yml
- playbooks/role/role-member-group-present.yml
- playbooks/role/role-member-host-absent.yml
- playbooks/role/role-member-host-present.yml
- playbooks/role/role-member-hostgroup-absent.yml
- playbooks/role/role-member-hostgroup-present.yml
- playbooks/role/role-member-privilege-absent.yml
- playbooks/role/role-member-privilege-present.yml
- playbooks/role/role-member-service-absent.yml
- playbooks/role/role-member-service-present.yml
- playbooks/role/role-member-user-absent.yml
- playbooks/role/role-member-user-present.yml
- playbooks/role/role-members-absent.yml
- playbooks/role/role-members-present.yml
- playbooks/role/role-rename.yml
- plugins/modules/iparole.py
- tests/role/env_cleanup.yml
- tests/role/env_facts.yml
- tests/role/env_setup.yml
- tests/role/test_role.yml
- tests/role/test_role_service_member.yml
There is a new role management module placed in the plugins folder:
plugins/modules/iparole.py
The role module allows to ensure presence or absence of roles and
manage role members.
README-role.md
playbooks/role/role-is-absent.yml
playbooks/role/role-is-present.yml
playbooks/role/role-member-group-absent.yml
playbooks/role/role-member-group-present.yml
playbooks/role/role-member-host-absent.yml
playbooks/role/role-member-host-present.yml
playbooks/role/role-member-hostgroup-absent.yml
playbooks/role/role-member-hostgroup-present.yml
playbooks/role/role-member-privilege-absent.yml
playbooks/role/role-member-privilege-present.yml
playbooks/role/role-member-service-absent.yml …
> New Role management module

- README-group.md
- plugins/modules/ipagroup.py
- tests/group/test_group_external_nonposix.yml
This patch adds suport for the IPA CLI option `posix` when modifying an existing group. Also, enhances verification of `external` and `posix/non-posix` groups to avoid unneded API failures (e.g. when no change to the posix/external status is needed).
This PR was based on PR #320.
> Add support for IPA CLI option `posix`.

- README-selfservice.md
- playbooks/selfservice/selfservice-absent.yml
- playbooks/selfservice/selfservice-member-absent.yml
- playbooks/selfservice/selfservice-member-present.yml
- playbooks/selfservice/selfservice-present.yml
- plugins/modules/ipaselfservice.py
- tests/selfservice/test_selfservice.yml
There is a new selfservice management module placed in the plugins folder:
plugins/modules/ipaselfservice.py
The selfservice module allows to ensure presence and absence of selfservices
and manage selfservice attributes.
README-selfservice.md
playbooks/selfservice/selfservice-absent.yml
playbooks/selfservice/selfservice-present.yml
playbooks/selfservice/selfservice-member-absent.yml
playbooks/selfservice/selfservice-member-present.yml
tests/selfservice/test_selfservice.yml
> New selfservice management module

- README-delegation.md
- playbooks/delegation/delegation-absent.yml
- playbooks/delegation/delegation-member-absent.yml
- playbooks/delegation/delegation-member-present.yml
- playbooks/delegation/delegation-present.yml
- plugins/modules/ipadelegation.py
- tests/delegation/test_delegation.yml
There is a new delegation management module placed in the plugins folder:
plugins/modules/ipadelegation.py
The delegation module allows to ensure presence and absence of delegations
and manage delegation attributes.
README-delegation.md
playbooks/delegation/delegation-absent.yml
playbooks/delegation/delegation-present.yml
playbooks/delegation/delegation-member-absent.yml
playbooks/delegation/delegation-member-present.yml
tests/delegation/test_delegation.yml
> New delegation management module

- plugins/module_utils/ansible_freeipa_module.py
When a fail_json is called a SystemExit exeception is raised.
Since the FreeIPABaseModule has an internal context manager to deal with exceptions this ContextManager captures the SystemExit. After dealing destroying the kinit session the SystemExit must be raised again to allow the fail_json to work properly.
> Fixed error msgs on FreeIPABaseModule subclasses

- README-user.md
Fix `ipauser` return value docmuentation by replacing occurrences of `host` with `user`, where needed.
> Replace `host` to `user` in module ipauser on return value documentation

- README-vault.md
- playbooks/vault/retrive-data-asymmetric-vault.yml
- playbooks/vault/retrive-data-symmetric-vault.yml
- plugins/modules/ipavault.py
- tests/vault/test_vault_asymmetric.yml
- tests/vault/test_vault_standard.yml
- tests/vault/test_vault_symmetric.yml
The ipavault module was returning a single string value when retrieving
data. To keep consistency with other modules, it should return a dict
with the `data` variable in it.
This change modifies the result of ipavault to be a dict and also fixes
relevant tests, examples and documentation.
> Modified return value for ipavault module.

- README-hostgroup.md
- playbooks/hostgroup/rename-hostgroup.yml
- plugins/modules/ipahostgroup.py
- tests/hostgroup/test_hostgroup_rename.yml
FreeIPA 4.8.7 introduced an option to rename an existing hostgroup.
This patch adds support for renaming hostgroups if the option is
available on installed IPA version.
> Add support for parameter `rename` on ipahostgroup.

- README-location.md
- playbooks/location/location-absent.yml
- playbooks/location/location-present.yml
- plugins/modules/ipalocation.py
- tests/location/test_location.yml
Tests for module ipalocation failed due to missing ipaadmin_password.
Added the variable to the playbooks, and also fixed the examples and
documentation. Some playbooks had identation fixed to two spaces
instead of one for consistency with other modules.
> Missing admin passwords in location module.

- README-vault.md
- plugins/modules/ipavault.py
- tests/vault/test_vault_symmetric.yml
While adding some tests to verify ipavault salt attribute manipulation, some errors were found both on the behavior of its update (salt should not be updated, unless symmetric vault password is changed), and in related parts of the code. This PR addresses these problems.
* Fixed an occurence in some scenarios, where the value of the vault type is returned as a tuple, rather than a string, this made some changes to existing vault to fail.
* When modifying an existing vault to change the value of salt, the password must also change. It is fine to "change" the password to the same value, thus only changing the salt value.
* The generation of a random salt, when one was not provided, was duplicated and in the wrong place, being generated too late to be used properly.
New tests have been added …
> Fix ipavault `salt` update.

- README-dnszone.md
- playbooks/dnszone/dnszone-reverse-from-ip.yml
- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipadnszone.py
- tests/dnszone/test_dnszone_name_from_ip.yml
IPA CLI has an option `name_from_ip` that provide a name for a zone
from the reverse IP address, so that it can be used to, for example,
manage PTR DNS records.
This patch adds a similar attribute to ipadnszone module, where it
will try to find the proper zone name, using DNS resolve, or provide
a sane default, if a the zone name cannot be resolved.
The option `name_from_ip` must be used instead of `name` in playbooks,
and it is a string, and not a list.
A new example playbook was added:
playbooks/dnszone/dnszone-reverse-from-ip.yml
A new test playbook was added:
tests/dnszone/test_dnszone_name_from_ip.yml
> Add support for option `name_from_ip` in ipadnszone module.

- .copr/Makefile
This commit adds .copr/Makefile that calls the executable script (build-srpm.sh)
to be used for COPR SRPM generation.
> Adding auto COPR builds

- plugins/modules/ipavault.py
When running module ipavault with Python 2.7, due to differences in
the handling of unicode string than in Python 3, the vault_type type
was different than the required.
This patch changes the default value to force a unicode string in
the supported versions of Python, fixing the module when Python 2
is used.
> Fix ipavault vault_type under Python 2.7

- README-config.md
- README-group.md
- README-service.md
Some attributes require a specific IPA version to be used, some were
not documented, some had different text.
This change standardize the text to show that some attributes require
a specific IPA version to be used, and add the versions where they
were not yet documented.
> Fixed note about specific IPA version for attributes.

- README-vault.md
There was a duplicate table for the return values in the vault module, the invalid one was removed.
> Fix invalid return value from vault module in README.md.

- tests/README.md
- tests/test_playbook_runs.py
Currently, running pytest requires that ssh uses key exchange. These
change allows the use of ssh with password to connect to the host.
> Add support for running pytest tests with ssh password.

- .gitignore
When using virtual environment for development, Git reports that the
virtual environment itself in untracked. This change add commonly found
virtual environment directories to the list of ignored files/directories.
> Add commonly used virtual environment paths to gitignore.

- .gitignore
- pytest.ini
- requirements-dev.txt
- requirements-tests.txt
- tests/README.md
- tests/azure/templates/group_tests.yml
- tests/azure/templates/pytest_tests.yml
- tests/pytests/dnszone/playbooks/dnszone_add_multiple_ipv4_ipv6_forwarders.yaml
- tests/pytests/dnszone/playbooks/dnszone_add_without_forwarder.yaml
- tests/pytests/dnszone/playbooks/dnszone_del_multiple.yaml
- tests/pytests/dnszone/playbooks/dnszone_disable.yaml
- tests/pytests/dnszone/playbooks/dnszone_enable.yaml
- tests/pytests/dnszone/playbooks/dnszone_invalid_ip.yaml
- tests/pytests/dnszone/playbooks/dnszone_invalid_serial.yaml
- tests/pytests/dnszone/playbooks/dnszone_name_from_ip.yaml
- tests/pytests/dnszone/playbooks/dnszone_with_forward_policy_only.yaml
- tests/pytests/dnszone/test_dnszone.py
- tests/test_playbook_runs.py
- tests/utils.py
Until now ansible-freeipa repository only had playbook tests. This PR introduces the ability of creating TestCase classes connected to the master host. This connection can be used to run commands in the managed host after the ansible playbook execution is the allowing the verification of the machine state.
* Fixes #359
> Added ability to add pytest tests

- playbooks/host/host-member-managedby_host-absent.yml
- playbooks/host/host-member-managedby_host-present.yml
- playbooks/host/host-present-with-managedby_host.yml
- playbooks/host/hosts-member-managedby_host-absent.yml
- playbooks/host/hosts-member-managedby_host-present.yml
- playbooks/host/hosts-present-with-managedby_host.yml
- playbooks/host/hosts-present-with-randompasswords.yml
The host's module example playbooks had syntax errors that prevented
its execution. The tasks were described as dicts rather than lists.
> Fix host's module managedby_host playbooks.

- .ansible-lint
- .github/workflows/lint.yml
- .yamllint
- README-dnszone.md
- molecule/resources/playbooks/prepare-build.yml
- playbooks/host/host-member-managedby_host-absent.yml
- playbooks/host/host-member-managedby_host-present.yml
- playbooks/host/host-present-with-managedby_host.yml
- playbooks/host/hosts-member-managedby_host-absent.yml
- playbooks/host/hosts-member-managedby_host-present.yml
- playbooks/host/hosts-present-with-managedby_host.yml
- playbooks/host/hosts-present-with-randompasswords.yml
- setup.cfg
- tests/azure/azure-pipelines.yml
- utils/lint_check.sh
This PR add support for running Yamllint, Ansible-lint and Flake8 as Github actions that will run on every push. It also adds yamllint and ansible-lint to Azure pipelines to be executed for every pull request.
A few existing playbooks needed to be fixed due to an ansible-lint issue.
This PR does not fixes any issues found in the existing playbooks, instead, it disables all found in playbooks during development. The issues should be fixed by other patches.
More details can be found on the individual commits.
> Add support for ansible-lint and yamllint as Github actions.

- playbooks/dnsforwardzone/ensure-dnsforwardzone-is-absent.yml
- playbooks/dnsforwardzone/ensure-dnsforwardzone-is-present.yml
- playbooks/dnsforwardzone/ensure-dnsforwardzone-with-forwarder-port.yml
Module dnsforwardzone had no example playbooks, which are added by this patch.
> Add missing example playbooks for dnsforwardzone module.

- README-trust.md
- README.md
- playbooks/trust/add-trust.yml
- playbooks/trust/del-trust.yml
- plugins/modules/ipatrust.py
- tests/trust/test_trust.yml
New trust management module
--------
There is a new trust management module placed in the plugins folder:
`plugins/modules/trust.py`
The trust module allows to ensure presence and absence of trusts.
`README-trust.md `
`playbooks/trust/add-trust.yml`
`playbooks/trust/del-trust.yml`
New tests added for the module:
`tests/hbacrule/test_trust.yml`
> added trust module and docs

- tests/user/test_users_present_slice.yml
users.json is generated for the tests and not part of the repo any more.
This test was lacking the include to generate the file.
Related to: b7e1a99b6eddf348dc854c753b45cecde09deb48
tests/user/test_users*.yml: Use extended dynamic users.json
> tests/user/test_users_present_slice.yml: Fix missing users.json

- README-privilege.md
- playbooks/privilege/privilege-absent.yml
- playbooks/privilege/privilege-member-absent.yml
- playbooks/privilege/privilege-member-present.yml
- playbooks/privilege/privilege-present.yml
- plugins/modules/ipaprivilege.py
- tests/privilege/test_privilege.yml
There is a new privilege management module placed in the plugins folder:
plugins/modules/ipaprivilege.py
The privilege module allows to ensure presence or absence of privilege
and manage privilege permission memebers.
README-privilege.md
playbooks/privilege/privilege-absent.yml
playbooks/privilege/privilege-member-absent.yml
playbooks/privilege/privilege-member-present.yml
playbooks/privilege/privilege-present.yml
tests/privilege/test_privilege.yml
> New privilege management module

- roles/ipaserver/module_utils/ansible_ipa_server.py
IPA_MODULES has been moved from ipaserver.install.installutils to
ipalib.facts with https://pagure.io/freeipa/issue/8458
> ipaserver/module_utils/ansible_ipa_server: IPA_MODULES moved to ipalib.facts

- README-vault.md
- plugins/modules/ipavault.py
- tests/vault/test_vault_asymmetric.yml
- tests/vault/test_vault_standard.yml
- tests/vault/test_vault_symmetric.yml
When retrieving data from a vault using `out` to store the data in a
file resulted is random characters being returned and logged. These
characters could generate a traceback print from Ansible's logger,
without breaking the script.
This patch fixes this behavior by supressing any return value when data
is retrieved to a file.
> Fixed log of vault data return when retrieving to a file.

- requirements-tests.txt
- tests/pytests/conftest.py
- tests/utils.py
In order to run the tests in idm-ci we need to configure the our pytest tests environment variables. This PR configures that automatically if an environment variable TWD is available and $TWD/config exists.
> Added helpers to config tests for execution on idm-ci

- roles/ipareplica/README.md
- roles/ipareplica/tasks/install.yml
- roles/ipaserver/README.md
- roles/ipaserver/tasks/install.yml
The new variables ipa[server,replica]_firewalld_zone have been added to
be able to set the zone in which the needed services for IPA are enabled.
New tasks have been added to check if the zone is available in the runtime
and also permamanet environment.
The code to enable firewalld has been moved out of thee
ipa[server,replica]_install_packages blocks to make sure that the firewalld
service is also enabled if the package is already installed.
Fixes: issue #177 (How to set up firewalld zones?)
> ipa[server,replica]: New variables to set firewalld zone

- roles/ipaclient/module_utils/ansible_ipa_client.py
- roles/ipareplica/module_utils/ansible_ipa_replica.py
- roles/ipaserver/module_utils/ansible_ipa_server.py
https://pagure.io/freeipa/issue/8458 moved more things to the ipalib and
ipalib.facts:
- sysrestore has been moved from ipalib.install to ipalib
- is_ipa_configured has been moved from ipaserver.install.installutils to
ipalib.facts
Fixes: #394 (TASK [ipaclient : Install - IPA client test] Error: module
'ipalib.install.sysrestore' has no attribute
'SYSRESTORE_STATEFILE')
> ipa[server,replica,client]: Fix moved sysrestore and is_ipa_configured

- plugins/modules/ipadelegation.py
- plugins/modules/ipadnsrecord.py
- plugins/modules/ipadnszone.py
- plugins/modules/iparole.py
- plugins/modules/ipaservice.py
- plugins/modules/ipasudorule.py
- plugins/modules/ipatopologysegment.py
- plugins/modules/ipauser.py
- roles/ipaclient/library/ipaclient_fix_ca.py
- roles/ipaclient/library/ipaclient_fstore.py
- roles/ipaclient/library/ipaclient_setup_nss.py
- roles/ipareplica/library/ipareplica_prepare.py
ansible-doc is reporting several issues in modules. Most of them have benn
due to misspelled description key word or due to use of multi line text
without the | in the description line.
> Fix module documentation

- utils/ansible-doc-test
This script can check modules in roles and also plugins folder to have
a valid documentation section. It is using anisble-doc internally.
usage: Usage: ansible-doc-test [options] [path]
optional arguments:
-h, --help  show this help message and exit
-v          increase output verbosity
There are different verbose levels:
-v   Shows the modules that are tested at the moment.
-vv  Shows the modules and also the doc output.
You can use the script to check specific modules, roles or modules in roles.
Here are some examples:
Test specific module with verbose level 1:
$ utils/ansible-doc-test -vv plugins/modules/ipauser.py
Test all modules in plugins folder:
$ utils/ansible-doc-test -v plugins
Test ipaserver_prepare.py in ipaserver role:
$ utils/ansible-doc-test -v …
> New script utils/ansible-doc-test

- utils/changelog
This scrip can be used to generate the changelog text for a new
ansible-freeipa release on github.
usage: Usage: changelog [options] [<new version>]
optional arguments:
-h, --help  show this help message and exit
--tag TAG   git tag
If the script is used without a givn tag, it will show all the changes since
the last tag. If a tag (this can be a also a commit) is given, then all
changes since this commit are shown.
> New script utils/changelog

- plugins/modules/ipavault.py
- tests/vault/test_vault_symmetric.yml
When using changing passwords, using password files, the file name was
being used as the password, and not its content. This patch fixes the
behavior to use the contents of the password file.
Tests have been added to ensure the correct behavior.
> Fix symmetric vault password change when using password_files.

- README-vault.md
- playbooks/vault/retrive-data-asymmetric-vault.yml
- playbooks/vault/retrive-data-symmetric-vault.yml
When using the ipavault module to retrieve stored data, this data is
often sensitive, and if `no_log` is not enabled on the playbook, the
sensitive data will be logged by Ansible.
This change in de documentation, and playbook examples, suggests the
use of `no_log: true` when using `state: retrieved` with ipavault.
> Add note about `no_log` use on vault data retrieve.

- playbooks/backup-server-to-controller.yml
- playbooks/backup-server.yml
- playbooks/copy-all-backups-from-server.yml
- playbooks/copy-backup-from-controller.yml
- playbooks/copy-backup-from-server.yml
- playbooks/remove-all-backups-from-server.yml
- playbooks/remove-backup-from-server.yml
- playbooks/restore-server-from-controller.yml
- playbooks/restore-server.yml
- roles/ipabackup/README.md
- roles/ipabackup/defaults/main.yml
- roles/ipabackup/meta/main.yml
- roles/ipabackup/tasks/backup.yml
- roles/ipabackup/tasks/copy_backup_from_server.yml
- roles/ipabackup/tasks/copy_backup_to_server.yml
- roles/ipabackup/tasks/get_ipabackup_dir.yml
- roles/ipabackup/tasks/main.yml
- roles/ipabackup/tasks/remove_backup_from_server.yml
- roles/ipabackup/tasks/restore.yml
- roles/ipabackup/vars/CentOS-7.yml
- roles/ipabackup/vars/CentOS-8.yml
- roles/ipabackup/vars/Fedora.yml
- roles/ipabackup/vars/OracleLinux-7.yml
- roles/ipabackup/vars/OracleLinux-8.yml
- roles/ipabackup/vars/RedHat-7.3.yml
- roles/ipabackup/vars/RedHat-7.yml
- roles/ipabackup/vars/RedHat-8.yml
- roles/ipabackup/vars/Ubuntu.yml
- roles/ipabackup/vars/default.yml
There is a new backup role in the roles folder:
roles/ipabackup
This role allows to backup an IPA server, to copy a backup from the
server to the controller, to copy all backups from the server to the
controller, to remove a backup from the server, to remove all backups
from the server, to restore an IPA server locally and from the controller
and also to copy a backup from the controller to the server.
Here is the documentation for the role:
roles/ipabackup/README.md
playbooks/backup-server.yml
playbooks/backup-server-to-controller.yml
playbooks/copy-backup-from-server.yml
playbooks/copy-all-backups-from-server.yml
playbooks/remove-backup-from-server.yml
playbooks/remove-all-backups-from-server.yml
playbooks/copy-backup-to-server.yml …
> New backup role

- utils/build-galaxy-release.sh
- utils/galaxyfy-README.py
- utils/galaxyfy-module-EXAMPLES.py
- utils/galaxyfy-playbook.py
- utils/galaxyfy.py
Up to now the snippets in the README files, the EXAMPLES in the modules
and also the tests playbooks have not been adapted while building the
collection.
These are the invoved python files:
utils/galaxyfy-README.py
utils/galaxyfy-module-EXAMPLES.py
utils/galaxyfy-playbook.py
utils/galaxyfy.py
utils/galaxyfy.py provides the function galaxyfy_playbook, which has been
extended and is used in galaxyfy-playbook.py, galaxyfy-README.py and
galaxyfy-module-EXAMPLES.py.
> build-galaxy-release: Galaxyfy READMEs, module EXAMPLES and tests

- README-group.md
- plugins/modules/ipagroup.py
- tests/env_freeipa_facts.yml
- tests/group/test_group_external_members.yml
This patch add support for adding external members to ipagroup which
have the `external` attribute set. It adds another attribute to the
module, `external_members`, which is a list of users or groups from
an external trust, to be added to the group.
This patch requires server-trust-ad to be tested, as such, the tests
have been guarded by a test block, for when such tests are available
in ansible-freeipa CI.
Fixes issue #418
> Add support for adding external members to ipagroup.

- utils/changelog
There is curently a merge commit without a subject, which leads into a
traceback in the changelog script.
The merge information provides the commit hash, which is now used to get
the subject later on using the generated commits hash.
> Fix utils/changelog for merge commits without subject

- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipavault.py
- tests/vault/test_vault_asymmetric.yml
- tests/vault/test_vault_standard.yml
- tests/vault/test_vault_symmetric.yml
Due to Ansible filtering out values in the output that might be match
values in sensible attributes that have `no_log` set, if a module need
to return data to the controller, it cannot rely on
`ansible_module.exit_json` if there is a chance that a partial match
may occur.
See: https://github.com/ansible/ansible/issues/71789
The change provided here uses the same implementation that is used on
Ansible's `AnsibleModule.exit_json`, without the data filtering layer,
so every attribute with be printed and, therefore, logged by Ansible.
This is needed for the Vault module, as we need to return values that
are explicit requested by the user and that might, at least partially,
match the values in attributes with `no_log` set.
Tests that reproduced the issue, and show it was fixed were provided …
> Bypass Ansible filtering on data returned by the module.

- README-permission.md
- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipapermission.py
- tests/permission/test_permission.yml
Some attribute values are only accepted for specific FreeIPA versions,
for example `self` for permission's `bindtype`. Although there are
options to check for command and parameter availability, there is no
check for verifying if a value should be accepted.
This patch add a function to check if the target FreeIPA host has, at
least a specific version. For example, calling `api_check_version(4.8)`
would return `True` for every 4.8-series release.
The version evaluation uses Python packaging's version comparision,
which is compatible with PEP 440.
> Add FreeIPA version check to module_utils.ansible_freeipa_module.

- tests/README.md
The test README only required than DNS support was enabled, but, currently, for (almost) complete testing support, KRA is also needed (for ipavault).
> Add KRA requirement to test documentation.

- plugins/modules/ipapermission.py
There was a colon (`:`) missing in the documentation part of ipapermission module.
> Fix ipapermission documentation issue with ansible-doc.

- utils/build-galaxy-release.sh
The currently used namespace and collection name are hard coded in
utils/build-galaxy-release.sh. They can now be defined as args 1 and 2
and default to freeipa and ansible_freeipa..
> Support namespace and name in utils/build-galaxy-release.sh as args

- .github/workflows/docs.yml
- utils/ansible-doc-test
This change add support for running ansible-doc-test as a Github
action on every commit or PR, ensuring that roles and modules are
able to produce correct documentation with ansible-doc.
> The task failure is expected, as there is an issue with one file, which
is ifxed in #426.
> Add action to verify Ansible documentation on each commit or PR.

- README.md
Information about the backup role and also the config, delegation, dns
config, location, permission, priviledge and self service modules have been
missing in the main README file.
> README.md: Add missing roles and modules

- roles/ipaserver/tasks/copy_external_cert.yml
Currently the certifaictes are copied ot the server with the complete
path that is provided within the playbook. This could result in
unexpected file placements. Certificates should be placed in the /root
folder for the deployment.
Fixes #405 (copy_external_cert does not handle pathed items)
> ipaserver: copy_external_cert should use basename on server only

- tests/dnsrecord/test_dnsrecord.yml
- tests/host/certificate/test_host_certificate.yml
- tests/host/certificate/test_hosts_certificate.yml
- tests/user/certificate/test_user_certificate.yml
- tests/user/certificate/test_users_certificate.yml
- tests/user/certmapdata/test_user_certmapdata.yml
- tests/user/certmapdata/test_users_certmapdata.yml
- tests/user/test_users_invalid_cert.yml
- tests/vault/tasks_vault_members.yml
- tests/vault/test_vault_asymmetric.yml
The file lookup is by default setting `rstrip=True` which could lead
into a stripped new line. This is not happening always but resulted in
failed tests sometimes with certificates pasted to the b64encode filter.
For all calls of lookup in the certificae tests `rstrip=False` has been
added to make sure that this is not happening any more. The user and
host tests have also been simplified to create the base64 encoded file
in the beginning and use this file then later on in the tests without
the need to use the b64encode filter.
Ref: https://github.com/ansible/ansible/issues/57521#issuecomment-502238000
> Fix lookup for certicates in tests

- plugins/modules/ipadnsrecord.py
- tests/dnsrecord/test_dnsrecord.yml
- tests/dnsrecord/test_dnsrecord_modify_record.yml
When modifying a record, depending on how the playbook tasks were
arranged, it was possible to end with more records than expected.
This behavior was fixed by modifying the way records are searched
when a modification is requested. This change also allows less calls
find_dnsrecord.
Tests were modified to reflect the changes, and a new test playbook
was added:
tests/dnsrecord/test_dnsrecord_modify_record.yml
> ipadnsrecord: fix record modification behavior.

- plugins/modules/ipadnsrecord.py
- tests/dnsrecord/test_dnsrecord.yml
There was a failure when NAPTR or DLV records where updated,
if the same record name had multiple entries. This patch fixes this
behavior, by using the requested record, not the retrieved one.
Tests have been updated to test for this issue on
tests/dnsrecord/test_dnsrecord.yml
> ipadnsrecord: fix record update when multiple records exist.

- plugins/modules/ipadnszone.py
- tests/dnszone/test_dnszone_mod.yml
Due to an issue with FreeIPA, when modifying the SOA serial attribute
along with other attributes, the value is ignored. In order to have
the value provided, the attribute is set is a later call to dnszone-mod
allowing it to retain the desired value.
Ref: https://pagure.io/freeipa/issue/8489
> ipadnszone: Fix modification o SOA serial with other attributes.

- .pre-commit-config.yaml
- requirements-dev.txt
This patch adds another lever of linter checking for ansible-freeipa
by enabling linters to run on the developer machine, before pushing
changes to be evaluated on the CI, allowing code fixes without
wating for CI to run the linters on the repository.
To enable pre-commit hooks, `pre-commit` is used, and was added to
requirements-dev.txt, and can be installed with pip
(`pip install -r requirements-dev.txt`). Once installed, on every
commit, YAML and python files on the commit will be evaluated.
If one needs to bypass the pre-commit linters, `git commit` can be
issued with `--no-verify`.
The linters will not be removed from the CI, as a commit can be
performed without running the checks.
> Add pre-commit configuration for linters.

- README-dnsforwardzone.md
- plugins/modules/ipadnsforwardzone.py
Examples of dnsforwarzone were using a single string rather than a
dict of values to set attribute `forwarders`. Both source code and
README examples were fixed.
Fix issue #446
> ipadnsforwardzone: Fix documentation for `forwarders` usage.

- utils/ansible-doc-test
Currently the script is failing with The given path '...' is not valid
if a path is not handled by the script. This is resulting in issues if
module_utils and action plugins are updated for example.
The solution is to simply ignore paths that are not handled.
> ansible-doc-test: Ignore unhandled paths

- roles/ipareplica/README.md
There was a typo in the README and also the ipareplica_hidden_replica
parameter was missing.
> ipareplica README.md: Fix typo, add hidden replica parameter

- roles/ipareplica/README.md
- roles/ipareplica/defaults/main.yml
- roles/ipareplica/library/ipareplica_test.py
- roles/ipareplica/tasks/install.yml
- roles/ipaserver/README.md
- roles/ipaserver/defaults/main.yml
- roles/ipaserver/library/ipaserver_test.py
- roles/ipaserver/module_utils/ansible_ipa_server.py
- roles/ipaserver/tasks/install.yml
The common_check function in the replica installer code has been changed
for the new memory checker code. With this the server and replica command
line installers got the option --skip-mem-check.
The server and replica role now also support the memory cheker and there
are new variables for server and replica:
ipaserver_mem_check - for ipaserver
ipareplica_mem_check - for ipaserver
These bool values default to yes and can be turned off in the inventory
or playbook if needed.
Related to freeipa PR https://pagure.io/freeipa/issue/8404 (Detect and
fail if not enough memory is available for installation)
Fixes: #450 (IPA Replica Installation Fails)
> ipa[server,replica]: Support memory check from command line installers

- plugins/modules/ipasudocmdgroup.py
- tests/sudocmdgroup/test_sudocmdgroup.yml
This PR fixes the creation of sudocmdgroups when the sudocmds are
specified, allowing groups to be created with sudocmd members in a
single task.
Fix issue #440.
> ipasudocmdgroup: Fix creation of sudocmdgroups with sudocmds.

- plugins/modules/ipahost.py
- tests/README.md
When using ipahost module with servers where DNS was not configured it failed to add hosts due to an exception raised on `dnsrecord_show` that was not being correctly handled.
As the exception was being handled twice, the This patch simply removes one of the handlers, allowing the exception to propagate to the caller, where it is handled.
This PR also modify host and dns module test playbooks, and adds a variable `SKIP_DNS` that can be used when running tests, to skip tests that require DNS to be configured on the server.
Fixes issue #434.
> Fix ipahost module when adding hosts to a server without DNS support.

- roles/ipareplica/library/ipareplica_prepare.py
- roles/ipareplica/library/ipareplica_setup_dns.py
The parameter options.no_dnssec_validation was set using a bad
parameter name. This lead to not beeing able to turn off dnssec
validation in the replica deployment.
Fixes: #456 (ipareplica_no_dnssec_validation)
> ipareplica: Fix no_dnssec_validation handling in prepare and setup_dns

- utils/changelog
The function get_commit was using the global merge variable instead of
the local commit variable. Therefore it returned the wrong commit
subject for merges without subject.
> utils/changelog: Fix get_commit to use proper variable

- utils/build-galaxy-release.sh
The default namespace and collection name was not set due to using ":"
instead of "-" while setting the variables internally.
> utils/build-galaxy-release.sh: Fix default namespace and collection name

- roles/ipabackup/tasks/backup.yml
- roles/ipabackup/tasks/restore.yml
The use of conditions in shell tasks without else clause is failing on
some systems with an undefined variable error.
> ipabackup: Fix undefined vars for conditions in shell tasks without else

- .pre-commit-config.yaml
With the parameter `args: ['.']`, yamllint would run over every
file during pre-commit, including those not being commited, and it
would allow for false negatives, not allowing a commit, even if
commited yaml files had no issues, but another file, not par of the
commit, had.
Changing the yamllint parameter to `files: \.(yaml|yml)$` it will
check only files being commited, preventing false negatives, and
allowing for faster commits.
> yamllint: Run yaml linter only on modified files in pre-commit.

- utils/build-galaxy-release.sh
warning[SC2044]: For loops over find output are fragile. Use find -exec
or a while read loop.
warning[SC2164]: Use 'cd ... || exit' or 'cd ... || return' in case cd
fails.
> utils/build-galaxy-release.sh: Fix covscan findings

- utils/new_module
warning[SC2166]: Prefer [ p ] || [ q ] as [ p -o q ] is not well
defined.
> utils/new_module: Fix covscan findings

- .pre-commit-config.yaml
This patch disables ansible-lint `always_run` flag, as this was
making patches that did not change any YAML file take longer in
the pre-commit step, as ansible-lint was executed with no parameter,
thus, searching and evaluating all YAML files in the repository.
With this change, if no YAML file is modified, ansible-lint is skipped.
> Faster pre-commit by running ansible-lint only when necessary.

- plugins/modules/ipaconfig.py
- plugins/modules/ipadelegation.py
- plugins/modules/ipadnsconfig.py
- plugins/modules/ipadnsforwardzone.py
- plugins/modules/ipadnsrecord.py
- plugins/modules/ipagroup.py
- plugins/modules/ipahbacrule.py
- plugins/modules/ipahbacsvc.py
- plugins/modules/ipahbacsvcgroup.py
- plugins/modules/ipahost.py
- plugins/modules/ipahostgroup.py
- plugins/modules/ipalocation.py
- plugins/modules/ipapermission.py
- plugins/modules/ipaprivilege.py
- plugins/modules/ipapwpolicy.py
- plugins/modules/iparole.py
- plugins/modules/ipaselfservice.py
- plugins/modules/ipaservice.py
- plugins/modules/ipasudocmd.py
- plugins/modules/ipasudocmdgroup.py
- plugins/modules/ipasudorule.py
- plugins/modules/ipatopologysegment.py
- plugins/modules/ipatrust.py
- plugins/modules/ipauser.py
- plugins/modules/ipavault.py
- utils/templates/ipamodule+member.py.in
- utils/templates/ipamodule.py.in
None of the modules on plugins/modules support Ansible check_mode (as reported on #407), which is an issue for pipelines with a stage to evaluate changes before merging pull requests, as well as for anyone who wants to view changes before applying them. 
Added code to enable check_mode on all plugins where I saw it feasible.
> Update modules to support check_mode

- plugins/modules/iparole.py
- tests/role/env_cleanup.yml
- tests/role/env_facts.yml
- tests/role/env_setup.yml
- tests/role/test_role_lists_handling.yml
When adding new members to a role, the existing members were removed.
The correct behavior for the "member" action is to add those members,
and substitute the existing ones. This patch fixes this behavior.
Fix #409, #411, #412, #413
> Fix handling members in ipa role.

- plugins/modules/ipavault.py
- tests/vault/env_cleanup.yml
- tests/vault/env_setup.yml
- tests/vault/tasks_vault_members.yml
- tests/vault/test_vault_asymmetric.yml
- tests/vault/test_vault_change_type.yml
- tests/vault/test_vault_standard.yml
- tests/vault/test_vault_symmetric.yml
Current implementation does not allow the change of an existingi Vault
type. To allow it, data is retrieved from the current vault, the vault
is modifiend, and then, data is stored again in the new vault.
Due to changing the process of modifying a vault, this change also
fixes the update of asymmetric vault keys. To change the key used,
the task must provide the old private key, used to retrieve data,
and the new public_key, used to store the data again. A new alias
was added to public_key (new_public_key) and public_key_file
(new_public_key_file) so that the playbook better express the
intention of the tak.
Vault tests have been updated to better test against the new update
process, and a new test file has bee added:
tests/vault/test_vault_change_type.
> Fix changing the type of an existing Vault.

- requirements-tests.txt
According to the testinfra changelog, since version 6.0.0, testinfra
is know as pytest-testinfra, and the use of testinfra is deprecated.
This change will prevent future isses when updating requirements using
`pip`.
Ref: https://testinfra.readthedocs.io/en/latest/changelog.html
> Change test requirement testinfra to pytest-testinfra.

- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipadnszone.py
In FreeIPA CLI, The attributes `allow_query` and `allow_transfer` can
hold IPv4 or IPv6 address or network address, and the values `none` and
`any`.
This patch adds support for network addresses, `none` and `any`, which
were not supported.
Fix issue #475.
> ipadnszone: Fix values accepted by allow_transfer and allow_query.

- README-permission.md
- plugins/modules/ipapermission.py
- tests/permission/test_permission.yml
The attrs handling was not complete and did not support to ensure presence
or absence of attributes with action:member.
The includedattrs and excludedattrs parameters have not been added with
this change as the use of attrs will automatically set includedattrs and
excludedattrs. The includedattrs and excludedattrs parameters are only
usable for managed permissions and duplicating attrs.
The permission module may not handle privileges. An IPA internal only API
has been used for this. The prvilege variable and all related code paths
have been removed.
Fixes: #424 ([Permission Handling] Not able to add additional attributes
with existing attributes)
Fixes: #425 ([Permission Handling] Not able to add member privilege while
adding permission)
> ipapermission: Fix attrs and drop privilege handling

- README-permission.md
There is a typo "Eure" instead of "Ensure" in the rename task.
> Fix typo in README-permission.md

- plugins/modules/ipapermission.py
- tests/permission/test_permission.yml
In `ipapermission` plugin, Some attributtes were not being managed
when `action: member` was enabled.
This patch enable member management for `right`, `rawfilter`,
`filter, and fixes management of `memberof`.
Fix issue #489
> Improve ipapermission member management.

- plugins/modules/ipadnsrecord.py
- tests/dnsrecord/test_compatibility_with_ansible_module.yml
When adding A or AAAA records using the compatibility mode with
Ansible's community general plugin, the reverse (PTR) record was
added, but the A/AAAA record was not. This patch fixes the behavior.
Fix issue #491
> Fix adding A/AAAA records with reverse in compatibility mode.

- utils/build-galaxy-release.sh
This patch adds a missing argument to `read` and adds information
on which step is being executed.
> Fix build-galaxy.sh execution and add running info.

- plugins/modules/ipasudorule.py
Updated names of objects that are part of sudorule, as the current ones do not match the names provided by IdM (resolves #500).
> Fixed names of member objects of sudorule

- molecule/centos-8-build/molecule.yml
- molecule/fedora-latest-build/molecule.yml
- tests/azure/azure-pipelines.yml
- tests/azure/build-containers.yml
- tests/azure/templates/build_container.yml
For some time, testing containers were failing to build in Azure pipelines. This PR addresses this problems by updating the vmImages, explicitly installing failing packages, and modifying the base images for the IPA containers.
> Fix container build.

- playbooks/selfservice/selfservice-absent.yml
- playbooks/selfservice/selfservice-member-absent.yml
- playbooks/selfservice/selfservice-member-present.yml
- playbooks/selfservice/selfservice-present.yml
The example playbooks for ipaselfservice were using the wrong module,
ipadelegation. This patch changes the references from ipadelegation
to ipaselfservice on these example playbooks.
Fix [RHBZ#1922060](https://bugzilla.redhat.com/show_bug.cgi?id=1922060)
> example playbooks: ipaselfservice examples mentioned ipadelegation.

- roles/ipaclient/tasks/install.yml
Due to commit f3f9672d527008dc741ac90aa465bac842eea08d (ipa-rmkeytab: Check
return value of krb5_kt_(start|end)_seq_get) in IPA 4.9.2 there is a new
error reported for ipa-rmkeytab in case of a non existing keytab file.
Using ipa-rmkeytab now results in the error 7 in this case.
The client role is using ipa-rmkeytab and needs to ignore error 7 also.
Fixes: #510 (ipa-client installation with OTP is failed with error code 7
(keytab: /usr/sbin/ipa-rmkeytab returned 7))
> ipaclient: Do not fail on rmkeytab error #7

- roles/ipabackup/tasks/get_ipabackup_dir.yml
**Fixes** #513
Details in the issue but basically :
```
- command: "{{ ansible_playbook_python }}"
+ command: "{{ ansible_python_interpreter | default('/usr/bin/python') }}"
```
in get_ipabackup_dir.yml and mention this variable or the default python path in README
> change variable in get_ipabackup_dir.yml and update README.md

- molecule/resources/playbooks/prepare-build.yml
- tests/azure/templates/build_container.yml
- tests/azure/templates/playbook_tests.yml
- tests/azure/templates/pytest_tests.yml
1) Set ANSIBLE_LIBRARY to fix unknown interpreter issue
The ANSIBLE_LIBRARY environment variable needs to point to molecule
directory.
2) Deactivate NTP in prepare-build
In CentOS 8 and also Fedora the configuration and start of chrony
fails with
Fatal error : adjtimex(0x8001) failed : Operation not permitted
For more information: https://bugzilla.redhat.com/show_bug.cgi?id=1772053
NTP will not be needed before a separate namespace is used for clocks.
> tests/azure: Set ANSIBLE_LIBRARY, deactivate NTP

- plugins/module_utils/ansible_freeipa_module.py
- tests/environment/test_locale.yml
IPA translates exception messages and Ansible uses controller's
language to execute plugins on target hosts, and since ansible-freeipa
uses Exceptions messages to detect some errors and/or states, using any
language that has a translation for the required messages may cause the
plugin to misbehave.
This patch modifies ansible_freeipa_module in plugin/module_utils to
force the use of "C" as the language by setting the environment variable
LANGUAGE.
Tests were added to verify the correct behavior:
tests/environment/test_locale.yml
The first test will fail, if ansible_freeipa_module is not patched, with
the message:
host_show failed: nonexistent: host nicht gefunden
This issue is not present if the language selected does not provide
a translation for the eror message.
This patch does not fix …
> Force plugins to execute using LANGUAGE='C'.

- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipaprivilege.py
- tests/privilege/test_privilege.yml
This PR fixes the behavior of `ipaprivilege` when a privilege is created with permissions.
As `None` was being passed to `compare_args_ipa()` (in `ansible_freeipa_modutils.py`) an exception was being raised. This was fixed by testing the function parameters to handle `None` values.
Also the behavior for creating and modifying privileges were fixed in the ipaprivilege module, so that a privilege can be created with permissions, and idempotence is ensured.
Fixes #529
> Fix privilege with permisions

- .pre-commit-config.yaml
It is needed to set ANSIBLE_LIBRARY to make sure that the current repo is
tested.
> ansible_doc_test pre commit: Set ANSIBLE_LIBRARY to test current repo

- README-server.md
- README.md
- playbooks/server/server-absent-continue.yml
- playbooks/server/server-absent-force.yml
- playbooks/server/server-absent-ignore_last_of_role.yml
- playbooks/server/server-absent-ignore_topology_disconnect.yml
- playbooks/server/server-absent.yml
- playbooks/server/server-hidden.yml
- playbooks/server/server-location.yml
- playbooks/server/server-no-location.yml
- playbooks/server/server-no-service-weight.yml
- playbooks/server/server-not-hidden.yml
- playbooks/server/server-present.yml
- playbooks/server/server-service-weight.yml
- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipaserver.py
- tests/server/test_server.yml
There is a new server management module placed in the plugins folder:
plugins/modules/ipaserver.py
The server module allows to ensure presence and absence of servers. The
module requires an existing server, the deployment of a new server can
not be done with the module.
README-server.md
playbooks/server/server-absent-continue.yml
playbooks/server/server-absent-force.yml
playbooks/server/server-absent-ignore_last_of_role.yml
playbooks/server/server-absent-ignore_topology_disconnect.yml
playbooks/server/server-absent.yml
playbooks/server/server-hidden.yml
playbooks/server/server-location.yml
playbooks/server/server-no-location.yml
playbooks/server/server-no-service-weight.yml …
> New server management module

- .github/workflows/docs.yml
- .pre-commit-config.yaml
- utils/ansible-doc-test
**.pre-commit-config.yaml: Do not set ANSIBLE_LIBRARY for ansible-doc-test**
With latest Ansible (4.0.0) it is needed to have a complete path for
ANSIBLE_LIBRARY. It is not good to hard code this in the
.pre-commit-config.yaml file for plugins and also all roles. Instead
it will be set in ansible-doc-test as it knows the path for each file
that is checked.
**.github/workflows/docs.yml: Enable verbose mode for ansible-doc-test**
Currently ansible-doc-test is run silently. There is no output about
the checked files in the test results. Therefore verbose mode has been
enabled.
**ansible-doc-test: Set ANSIBLE_LIBRARY using module_dir internally**
ANSIBLE_LIBRARY needs to be set properly for new Ansible version 4.0.0
to make sure that it is able to find the module that is checked.
For every …
> ansible-doc-test: ANSIBLE_LIBRARY needs to be set internally

- plugins/modules/ipasudorule.py
A repeated category reset of usercategory, hostcategory, cmdcaterory,
runasusercategory and hostcategory is resulting in the error
"no modifications to be performed".
The empty categories are now removed from the args if the category is
not set in the sudorule.
> ipasudorule: Fix category reset for idempotency

- plugins/modules/ipahost.py
The "DNS resource record not found" error occurs when a host arecord
or aaaarecord member is ensured to be absent and no dnsrecord entry
for the host exists.
The arecord or aaaarecord item are removed from dnsrecord_args if the
record is not defined in res_find_dnsrecord.
> host: Fix DNS resource record not found error

- plugins/modules/ipadnszone.py
A dnszone_mod call is always made to set the serial for a zone even if
this serial is set already.
A check is added to make sure that the serial is only set with
dnszone_mod if there is no serial set or if the serial is different.
> dnszone: Fix no modifications to be performed for serial

- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipahbacrule.py
**ansible_freeipa_module.py: New gen add and intersection functions**
Two new functions have been added for member management in plugins:
gen_add_list(user_list, res_list)
Generate the add list for addition of new members.
gen_intersection_list(user_list, res_list)
Generate the intersection list for removal of existing members.
gen_add_list should be used to add new members with action: members and
state: present. It is returning the difference of the user and res list
if the user list is not None.
gen_intersection_list should be used to remove existing members with
action: members and state: absent. It is returning the intersection of
the user and res list if the user list is not None.
**ipahbacrule.py: Reduce member changes to only needed ones**
Currently user, group, host, hostgoup, …
> Hbacrule only make required member changes

- plugins/module_utils/ansible_freeipa_module.py
The new argument ignore has been added to compare_args_ipa to ignore
attributes while comparing attributes of the user args and the object
args returned from IPA.
This code is using changes from
- Wolskie in PR #392
- jake2184 in PR #486
> ansible_freeipa_module.py: Add ignore argument to compare_args_ipa

- README-service.md
- plugins/modules/ipaservice.py
- tests/service/certificate/test_service_certificate.yml
- tests/service/env_cleanup.yml
- tests/service/env_setup.yml
- tests/service/test_service.yml
- tests/service/test_service_disable.yml
- tests/service/test_service_keytab.yml
- tests/service/test_service_without_skip_host_check.yml
This PR fixes ipaservice tests by enabling test fail when `result.failed` is `True`,
and fix the module handling EmptyModList and DuplicateEntry exceptions.
> Enhance ipaservice tests.

- plugins/modules/ipaconfig.py
- plugins/modules/ipadnsrecord.py
- plugins/modules/ipadnszone.py
- plugins/modules/ipaservice.py
- plugins/modules/ipasudocmdgroup.py
- plugins/modules/ipavault.py
Instead of importing ipalib.errors directly, all modules must import asible_freeipa_module.ipalib_errors.
This PR fixes the behavior on modules config, dnsrecord, dnszone, service, sudocmdgroup, and vault.
> Fix usage of ipalib errors.

- .github/workflows/lint.yml
- .pre-commit-config.yaml
- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipaconfig.py
- plugins/modules/ipadnsconfig.py
- plugins/modules/ipadnsforwardzone.py
- plugins/modules/ipadnsrecord.py
- plugins/modules/ipadnszone.py
- plugins/modules/ipagroup.py
- plugins/modules/ipahbacrule.py
- plugins/modules/ipahbacsvc.py
- plugins/modules/ipahbacsvcgroup.py
- plugins/modules/ipahost.py
- plugins/modules/ipahostgroup.py
- plugins/modules/ipapwpolicy.py
- plugins/modules/ipaservice.py
- plugins/modules/ipasudocmd.py
- plugins/modules/ipasudorule.py
- plugins/modules/ipatopologysegment.py
- plugins/modules/ipatrust.py
- plugins/modules/ipauser.py
- plugins/modules/ipavault.py
- setup.cfg
- utils/lint_check.sh
This PR adds support for running Pylint 2.8.2, over the `plugins` directory, as a pre-commit hook, and as a Github workflow action  to be executed or pushes and pull requests.
The Github workflow run pylint against all python files under the `plugins` directory.
The pre-commit hook runs pylint only in the modified Python files, to speed up the commit process. This is independent of directory, in the hope that all files will be either fixed or have the explicit checks disabled over time. 
All Pylint warnings for the `plugins` directory were either fixed or disabled, based, mostly, on code readability. The `roles` directory is not part of this PR, and should be addressed later.
> Add partial support for Pylint.

- plugins/modules/ipauser.py
The nomembers parameter is added to args for the api command. But
no_members is never part of res_find from user-show, therefore this
resulted in an error in the idempotency test where a user is ensured
again with the same settings.
As a workaround no_members is copied from args to res_find for the
update case to make sure that compare_args_ipa is working properly.
> user: Fix no modifications to be performed error

- README-sudocmd.md
- README-sudorule.md
- plugins/modules/ipasudocmd.py
I discovered a handful of typos in the docs while looking at something else, this PR simply fixes them. It only changes the README and ansible-doc output, it makes no change in functionality.
> fix minor documentation typos in sudo modules

- README-automember.md
- README.md
- playbooks/automember/automember-group-absent.yml
- playbooks/automember/automember-group-present.yml
- playbooks/automember/automember-hostgroup-absent.yml
- playbooks/automember/automember-hostgroup-present.yml
- playbooks/automember/automember-hostgroup-rule-absent.yml
- playbooks/automember/automember-hostgroup-rule-present.yml
- plugins/modules/ipaautomember.py
- tests/automember/test_automember.yml
I've extended & updated an automember module, first proposed in #392. That PR looked active for a couple of weeks, but silent for months. I've forked it, rebased on master, and addressed a few of the issues highlighted in the PR.
I can't tag the previous author, Mark Hahl / @Wolskie. I haven't changed any of the author notes or copyright.
> Add automember module

- .github/workflows/lint.yml
This patch modify Github 'lint' workflow to execute each linter
verifications as a separate job. This will allow us to easily see
which linter has failed, and ensure that all are executed, even
if one fails.
> ci: Run Github linter verification workflow in different jobs.

- README-vault.md
- plugins/modules/ipavault.py
This should sync the README and DOCUMENTATION string to the actual arguments the module accepts. It should change no functionality, just the docs.
Also: "user" and "users"  as two separate arguments? *sob*!  sadly that's how it is in the API so we cant change it.
> more minor documentation fixes, in vault module

- roles/ipabackup/library/ipabackup_get_backup_dir.py
- roles/ipabackup/tasks/get_ipabackup_dir.yml
Up to now a python snippet was used to get IPA_BACKUP_DIR from ipaplatform
but this was not working when ansible_facts was false due to not getting
ansible_python_interpreter set.
The module version is also working if gather_facts is turned off.
> ipabackup: Use module to get IPA_BACKUP_DIR from ipaplatform

- plugins/modules/ipaautomember.py
The parameters in the inclusive and exclusive dicts are not defined and
also not checked. Therefore it is possible to have parameters in the
dicts that are not used.
The dicts for the inclusive and exclusive parameters are now defined and
also added to the description.
> automember: Fail on wrong in/ex/clusive parameter names

- plugins/modules/ipaautomember.py
The action is service and member for the module, but it needs to be the
module name and member.
> automember: Fix action to be automember or member, not service

- plugins/modules/ipaautomember.py
result["failed"] is used only for INCLUDE_RE, EXCLUDE_RE if entries could
not be added that are already there and it entries could not be removed
that are not there.
All other issues like invalid attributes etc. are handled as exceptions.
Therefore the error section is not here as in other modules.
Fixes RHBZ#1979626
> automember: Fix result["failed"] issues with conditions

- plugins/modules/ipasudorule.py
Change, in the module documentation, the attribute named 'usergroup'
to 'group', as it is used in the code.
Fixes #580
> ipasudorule: Fix documentation attribute.

- tests/pwpolicy/test_pwpolicy.yml
Instead of ignoring errors it is better that we specific evaluate
errors provided by negative tests. This patche removes the an
occurrence of 'ignore_errors: true' in ansible-freeipa tests.
> Remove ignore_errors from pwpolicy tests.

- roles/ipaserver/README.md
This patch fixes rendering of the ipaserver role README.
Some variables with `choice` values were either hard to read when rendered, or were rendered wrongly due to bad formatting.
> Fix display of variables in ipaserver role README.

- README-automember.md
Missing variable "action" added in the automember module documentation.
> ipaautomember: Fix documentation.

- meta/runtime.yml
Galaxy now requires meta/runtime.yml to define requires_ansible.
runtime.yml has been added with requires_ansible: ">=2.9"
> New meta/runtime.yml for galaxy for requires_ansible

- plugins/modules/ipaautomember.py
- tests/automember/test_automember.yml
The automember_add_condition and automember_remove_condition commands
are not verifying condition keys in all cases. This is for example not
done in the removal case if a condition is not part of the automember
rule.
For consistent behaviour this needs to be done in the automember module
now. The condition keys are verified with the user and group aciattrs
returned by the API command json_metadata now.
Related: RHBZ#1976926
> automember: Verify condition keys

- tests/user/test_users_absent.yml
json_query is not part of Ansible Core. As this is the only used module
that is not in Core it has been replaced by constructig a new dict with
the needed user names from users dict using a loop and set_fact.
> Replace json_query in tests/user/test_users_absent.yml

- playbooks/selfservice/selfservice-member-absent.yml
A task name referenced attributes not used is the task.
> Fix task name in selfservice example playbook.

- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipahbacrule.py
- tests/hbacrule/test_hbacrule.yml
Single hostnames can be used for hbacrule_add_host and will match fqdn
in IPA internally. Simple host names have to be extended to be FQDN to
be able to compare them for _host_add and _host_remove.
Two new functions have been added to ansible_freeipa_module:
- api_get_domain - Get the domain from the api
- ensure_fqdn - Extend a single name with the domain
This fixes #617 - hbacrule_add_host: already a member
> hbacrule: Create FQDN from single hostnames

- .ansible-lint
Some YAML files used in the project are not Ansible playbooks and
should not be evaluated by ansible-lint. This change add the paths
and files that should not be evaluated to an exclude list, that
affects linter operations in CI and pre-commit scripts.
> ansible-lint: Add paths and files to exclude list.

- roles/ipabackup/tasks/restore.yml
- roles/ipabackup/vars/CentOS-7.yml
- roles/ipabackup/vars/CentOS-8.yml
- roles/ipabackup/vars/OracleLinux-7.yml
- roles/ipabackup/vars/OracleLinux-8.yml
- roles/ipabackup/vars/RedHat-7.3.yml
- roles/ipaclient/tasks/main.yml
- roles/ipaclient/vars/CentOS-7.yml
- roles/ipaclient/vars/CentOS-8.yml
- roles/ipaclient/vars/OracleLinux-7.yml
- roles/ipaclient/vars/OracleLinux-8.yml
- roles/ipaclient/vars/Ubuntu.yml
- roles/ipareplica/tasks/main.yml
- roles/ipareplica/vars/CentOS-7.yml
- roles/ipareplica/vars/CentOS-8.yml
- roles/ipareplica/vars/OracleLinux-7.yml
- roles/ipareplica/vars/OracleLinux-8.yml
- roles/ipareplica/vars/RedHat-7.3.yml
- roles/ipaserver/tasks/main.yml
- roles/ipaserver/vars/CentOS-7.yml
- roles/ipaserver/vars/CentOS-8.yml
- roles/ipaserver/vars/OracleLinux-7.yml
- roles/ipaserver/vars/OracleLinux-8.yml
- roles/ipaserver/vars/RedHat-7.3.yml
When loading variables in all ansible-freeipa roles, it is expected
that a file with these variables is present for each supported Linux
distribution, and then, based on the information about the distribution
provided by Ansible, the correct file is loaded.
Previously, only the facts `distribution` and dinstribution version
related facts were used, which required specific files, or links to
files for distributions in the same "family", which will probably have
the same variables set.
This change adds searching for files based on the `os_family` fact,
allowing distributions that follow the same family rules to be
supported, without any changes to the codebase. It is still possible
that a specific distribution configuration overrides the default
behavior, as `os_family` has lower priority …
> Use Ansible fact "os_family" as fallback, when distro is not directly suppported.

- tests/trust/test_trust.yml
Test playbooks were missing ipaadmin_password.
> tests/trust: Add ipaadmin_password to test playbooks.

- tests/azure/build-containers.yml
Currently, we rebuild the container images everyday, at midnight,
which ensures that we have all the latest changes from every distro
supported in CI.
This approach works fine for the upstream CI, but if we want to use
the CI images to test modules in a local container, for example, as
proposed by PR #556, updating the images daily means that there will
be much more images download that would not be needed, as the public
cloud images of supported distros don't change so often.
This patch proposes to change the build rate from daily to weekly,
reducing the need to download images by users, while still using a
good update window.
It should be noted that, if required, the images can be rebuilt
manually, so any urgent fix is added to the CI images.
> build_containers: build CI container images on Sundays.

- README-permission.md
- plugins/modules/ipapermission.py
Modules that support `state: renamed` have `new_name` as an alias
for the `rename` variable. This patch makes ipapermission consistent
with other modules.
> ipapermission: Add 'new_name' as an alias to 'rename'.

- .github/workflows/lint.yml
- .pre-commit-config.yaml
- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipaautomountlocation.py
- requirements-dev.txt
- setup.cfg
This PR sets pylint to version 2.10.2 in all linter actions, and
fixes code in plugins so that this version new checks are either
satisfied or ignored if needed.
> pylint: Upgrade to version 2.10.2.

- utils/templates/README-module+member.md.in
- utils/templates/README-module.md.in
- utils/templates/module-absent.yml.in
- utils/templates/module-member-absent.yml.in
- utils/templates/module-member-present.yml.in
- utils/templates/module-present.yml.in
- utils/templates/test_module+member.yml.in
- utils/templates/test_module.yml.in
ansible-freeipa modules should work without superuser privileges in
most cases, and to reflect this, the module tests should avoid using
`become: yes`.
This PR change the test playbook templates to use `become: no` by
default, so only modules that require superuser privileges will need
to change this variable.
> templates: Use `become: no` in tests by default.

- README-role.md
- plugins/modules/iparole.py
Modules that support `state: renamed` have `new_name` as an alias
for the `rename` variable. This patch makes iparole consistent with
other modules.
> iparole: Add 'new_name' as an alias to 'rename'.

- README-dnszone.md
- plugins/modules/ipadnszone.py
- tests/dnszone/test_dnszone_mod.yml
- tests/pytests/dnszone/test_dnszone.py
As of FreeIPA 4.9.7, setting SOA serial is deprecated, so this change
removes support for setting this variable in ipadnszone module.
As the behavior of SOA serial was unstable, at best, no effort was made
to allow its use with older versions of FreeIPA.
> dnszone: remove variable `serial`.

- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipadnszone.py
- tests/dnszone/test_dnszone.yml
This patch adds the required support for implementing `check_mode`
in FreeIPABaseModule class, and adds support for `check_mode` in
ipadnszone module.
Tests for verifying behavior were also added.
> ipadnszone: add check mode support

- plugins/modules/ipadnszone.py
Bind allows localhost and localnet in allow query so we should accept it.
> ipadnszone: Accept localhost and localnet in allow_query.

- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipaautomember.py
- plugins/modules/ipadelegation.py
- plugins/modules/ipadnsrecord.py
- plugins/modules/ipagroup.py
- plugins/modules/ipahbacrule.py
- plugins/modules/ipahbacsvc.py
- plugins/modules/ipahbacsvcgroup.py
- plugins/modules/ipahost.py
- plugins/modules/ipahostgroup.py
- plugins/modules/ipalocation.py
- plugins/modules/ipapermission.py
- plugins/modules/ipaprivilege.py
- plugins/modules/ipapwpolicy.py
- plugins/modules/iparole.py
- plugins/modules/ipaselfservice.py
- plugins/modules/ipaserver.py
- plugins/modules/ipaservice.py
- plugins/modules/ipasudorule.py
- plugins/modules/ipauser.py
- utils/templates/ipamodule+member.py.in
- utils/templates/ipamodule.py.in
execute_ipa_commands replces the check mode exit, the loop over the
generated commands and also in the member failure handling for modules
with member support.
> Use execute ipa commands

- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipatopologysuffix.py
The same error exists is the IPAAnsibleModule class documentation
and on the `ipatopologysuffix` plugin.
In the call to IPAAnsibleModule.ipa_command, a list was being used
as a single parameter, instead of its data being used as a parameter
list.
To test `ipatopologysuffix` the example playbook `verify-topologysuffix.yml`
was used against a single server environment (RHEL 8.4).
> Fix documentation and usage of IPAAnsibleModule

- .github/workflows/docs.yml
This patch pins ansible-core version to 2.11 when evaluating
documentation with ansible-doc-test, so both 2.9 (ansible) and
2.11 (ansible-core) are covered when testing documentation.
> CI: pin ansible-core version for ansible-doc-test.

- plugins/modules/ipaconfig.py
Removed the definition of unused function 'gen_args()' from ipaconfig.
> config: Remove unused code.

- plugins/modules/ipaconfig.py
When retrieving IPA configuration using ipaconfig module, a few
variables were not returning, and some data had the wrong data format.
This patch fix both issues and apply some code refactor, as data was
being retrieved from IPA API in different places using different
methods.
Fixes #636
> config: Fix data returned from module.

- plugins/modules/ipasudocmd.py
- plugins/modules/ipasudocmdgroup.py
Modify ipasudocmd and ipasudocmdgroup to use `execute_ipa_commands`.
> Use execute_ipa_commands for sudocmd plugins.

- README-group.md
- plugins/modules/ipagroup.py
- tests/group/test_group_external_nonposix.yml
The nonposix, posix and external parameters need to be mutually
exclusive. external was missing in this list. Only one of the three
parameters can be used.
external can not be set to no/false. This results in an error now.
if nonposix is used, posix is set as not nonposix. The nonposix
parameter is not used within the code anymore..
New tests have been added to tests the addition of users with for
nonposix and posix groups. The tests for the external group is not
active due to the need of an AD.
Fixes: #528 (Error creating nonposix group)
> group: Fix nonposix, posix and external handling and conversions

- tests/server/test_server.yml
As the server name was hard coded, when running tests for ipasever
module using a server not name as 'ipaserver', the tests would fail.
This patch allows the configuration of the server name using the
variable 'ipa_server_name', and if not provided, try to infer the
name from the inventory file (groups['ipaserver'][0], or, if not
defined in the inventory, it defaults to the original 'ipaserver'.
The same behavior is also applied to 'ipasever_domain'.
> ipaserver: Allow configuration of test server name.

- tests/config/test_config.yml
Currently, if a test fails during execution of ipaconfig playbook
tests, or if the failed task is the task reverting to the original
configuration fails, the testing host might be left in a state that
may cause other tests to fail due to the inconsistent configuration
state.
This patch ensures that if a test fails, a known configuration, the
same as used is the default installation of FreeIPA used in upstream
CI, is applied to the host, providing safe environment for testing.
> ipaconfig: Prevent configuration issues due to test failure.

- roles/ipaclient/library/ipaclient_setup_nss.py
- roles/ipaclient/library/ipaclient_test.py
- roles/ipaclient/module_utils/ansible_ipa_client.py
- roles/ipaclient/tasks/install.yml
ipaclient_setup_nss is using the nosssd_files dict if sssd is disabled
with no_sssd.
The nosssd_files dict is generated in ipaclient_test and used in
ipaclient_setup_nss. So far ipaclient_setup_nss was using nosssd_files
from ipaclient installer, which was always None.
> ipaclient_setup_nss: Use proper nosssd_files list

- tests/role/env_facts.yml
This patch fixes setting ipaserver_domain and ipaserver_realm facts
for iparole tests, fixing variable evaluation and allowing the tests to be
executed even if `gather_facts: no`.
> tests: Fix facts for iparole tests.

- setup.py
When running pylint against 'setup.py' it warns that an import is
not used. While it is not directly used, this is a fix for an issue
with older versions of Python, so this change tells pylint to ignore
the error.
> setup.py: Disable pylint rule import-error.

- README-server.md
- plugins/modules/ipaserver.py
The doc strings for the examples have not been good enough to express
that the module is requiring an existing server and that is not able to
deploy a new server.
> server: Express inability to deploy a server in example doc strings

- tests/automember/test_automember_client_context.yml
- tests/automount/test_automountlocation_client_context.yml
- tests/config/test_config_client_context.yml
- tests/delegation/test_delegation_client_context.yml
- tests/dnsconfig/test_dnsconfig_client_context.yml
- tests/dnsforwardzone/test_dnsforwardzone_client_context.yml
- tests/dnsrecord/test_dnsrecord_client_context.yml
- tests/dnszone/test_dnszone_client_context.yml
- tests/group/test_group_client_context.yml
- tests/hbacrule/test_hbacrule_client_context.yml
- tests/hbacsvc/test_hbacsvc_client_context.yml
- tests/hbacsvcgroup/test_hbacsvcgroup_client_context.yml
- tests/host/test_host_client_context.yml
- tests/hostgroup/test_hostgroup_client_context.yml
- tests/location/test_location_client_context.yml
- tests/permission/test_permission_client_context.yml
- tests/privilege/test_privilege_client_context.yml
- tests/pwpolicy/test_pwpolicy_client_context.yml
- tests/role/test_role_client_context.yml
- tests/selfservice/test_selfservice_client_context.yml
- tests/server/test_server_client_context.yml
- tests/service/test_service_client_context.yml
- tests/sudocmd/test_sudocmd_client_context.yml
- tests/sudocmdgroup/test_sudocmdgroup_client_context.yml
- tests/sudorule/test_sudorule_client_context.yml
- tests/trust/test_trust_client_context.yml
- tests/user/test_user_client_context.yml
When running the tests that can be executed either on server or client
context, without defining 'ipa_context', the context is automatically
identified.
Currently, the tests in upstream CI run only on a server, and the
context is identified as "server" context, and in order to run the test
using a client context 'ipa_context' must be set to 'client'.
This patch fixes all the client context tests by correctly setting
ipa_context when running the client context tests in a server host.
> Fix execution of client context tests.

- utils/build-galaxy-release.sh
The items in extends_documentation_fragments of the modules need to
have the proper galaxy prefix.
The documentation fragment
- ipamodule_base_docs
needs to be changed to
- ${collection_prefix}.ipamodule_base_docs
> utils/build-galaxy-release: Fix doc_fragment prefix for galaxy

- utils/templates/README-module+member.md.in
- utils/templates/README-module.md.in
- utils/templates/ipamodule+member.py.in
- utils/templates/ipamodule.py.in
Fix the module templates README by adding description for
`ipaapi_context` and `ipaapi_ldap_cache` variables.
Fix the module templates code by using IPAAnsibleModule method
`params_fail_used_invalid` to check for invalid parameters use for
a given state/action.
> Fix module templates README and invalid parameter tests.

- plugins/modules/ipaservice.py
- tests/service/test_service_without_skip_host_check.yml
When creating the lists to add/remove principal aliases, if the realm
was not specified, the alias would be used as it did not matched the
existing one, which has the realm part.
This patch fixes the add/del list creation by adding the current API
realm to each alias that does not have the realm part and then use
this modified list to be compared against the existing principal list.
This change also allows the use of the whole list in a single call to
the IPA API to add/remove the principals, instead of a call for every
one item in the list.
Fixes #663
> ipaservice: Fix idempotent behavior for principal aliases.

- plugins/modules/ipasudorule.py
- tests/sudorule/test_sudorule.yml
When setting 'runasuser' or 'runasgroup' for a sudorule, either IPA or
external users and groups may be used, but only IPA users and groups
were being searched for when modifying the attributes, making this task
not idempotent.
This patch fixes this issue by comparing users and groups to the IPA
and external setting.
Fix #664
> sudorule: Fix runas with external users and groups.

- plugins/modules/ipaprivilege.py
- tests/privilege/test_privilege.yml
This PR fixes ipaprivilege permission handling when using `action: privilege` and the use of the module when `check_mode: yes`.
As a result of fixing support for `check_mode`, the custom `result_handler` was removed in favor of the default handler in `IPAAnsibleModule` and the whole processing of comparing the arguments to the existing privilege was simplified.
Fixes #669
> ipaprivilege: Fix permissions handling.

- molecule/resources/playbooks/prepare-common.yml
- molecule/resources/playbooks/prepare.yml
- requirements-tests.txt
- tests/azure/azure-pipelines.yml
- tests/azure/nightly.yml
- tests/azure/templates/group_tests.yml
- tests/azure/templates/playbook_tests.yml
- tests/azure/templates/pytest_tests.yml
Currently, upstream CI test documentation against different Ansible
versions, but playbook tests are only executed with Ansible 2.9 series.
This patch add support for running playbook tests using ansible-core
version 2.11 and the latest version of Ansible.
All Ansible installations is done through Python's PIP.
See the [Checks Tab](https://github.com/freeipa/ansible-freeipa/pull/612/checks) for the resulting pipelines.
Total time for running tests is now more than 3h, using the maximum
parallelization allowed by Azure for open source projects (10 instances).
> CI: Test modules against Ansible core 2.11 and latest Ansible

- utils/build-galaxy-release.sh
The link for plugins/modules/ipabackup_get_backup_dir.py from
roles/ipabackup/library/ipabackup_get_backup_dir.py was left over
after the script finished.
> build-galaxy-release: Cleanup of ipabackup_get_backup_dir.py link

- plugins/modules/ipaautomember.py
- tests/automember/test_automember.yml
If a task with 'action: automember' tried to modify an automember rule
and did not provide either 'inclusive' or 'exclusive' parameters, the
regex for the missing arguments would be removed.
This patch fixes this behavior to only modify those parameters that
were set on the task, and leave the missing parameters in the state
they were before the task.
Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1976922
> automember: Fix behavior of unused parameters.

- plugins/module_utils/ansible_freeipa_module.py
Many module member attributes must be handled in a case insensitive
manner. To ease handling these cases, a function and a method to get
the module parameters converted to lowercase is provided.
This PR will be required by module specific PRs that will fix the handling
of member attributes that require case insensitive evaluation.
> ansible_module_utils: Add method to get parameters as lowercase.

- plugins/modules/ipaservice.py
Modify ipaservice so that it does not require a custom result handler
and can use the one provided by IPAAnsibleModule.
The modifications include changing the way members are handled,
using the gen_add_del_lists, gen_add_list and gen_intersection_list,
so that handling of "already a member" and "not a member" exception
are not required.
> ipaservice: Use IPAAnsibleModule member result handler.

- molecule/centos-9-build/Dockerfile
- molecule/centos-9-build/molecule.yml
- tests/azure/build-containers.yml
This patch add support for building testing images for CentOS 9 Stream.
> upstream ci: Build images for CentOS 9 Stream.

- README-config.md
The example didn't work for me with the following error (on freeipa 4.9.8):
TASK [display default login shell] **************************************************************************************************
fatal: [freeipa1.example.org]: FAILED! => {"msg": "
The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'defaultlogin'
Using the correct variable defaultshell works for me.
> Login shell is called defaultshell and not defaultlogin

- README-pwpolicy.md
Insert "ensure maxlife is set to 49 in global policy" instead of the wrong comment from cut&paste.
> correct comment in example playbook

- roles/ipabackup/vars/Ubuntu-18.04.yml
- roles/ipaclient/vars/Debian-10.yml
- roles/ipaclient/vars/Ubuntu-18.04.yml
- roles/ipareplica/vars/Ubuntu-18.04.yml
- roles/ipaserver/vars/Ubuntu-18.04.yml
In Debian 10 (Buster) and Ubuntu 18.04, ansible-freeipa roles
fail to execute due to the packages requiring Python 2.7, and
Ansible identifying that they may execute using Python 3.x.
This PR force `ansible_python_interpreter` to Python 2.7, allowing
roles to be executed on these distros.
The changes are based on previous contributions.
Fix #607
> Fix role issues in Debian based distros.

- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/README.md
- plugins/modules/ipaautomountlocation.py
- plugins/modules/ipadnszone.py
This patch add several deprecate warnings to FreeIPABaseModule, and
creates adapters to ease conversion of client classes to IPAAnsibleModule.
There is no 'ipa_commands' management in IPAAnsibleModule, as commands
is a list of tuples containing (command, name, args), and should be
managed by the module itself. Commands with no arguments should use an
empty dictionary as 'args'.
The 'ipa_run' method should be replaced by:
```python
exit_args = {}
ipaapi_context = self.params_get("ipaapi_context")
with self.ipa_connect(context=ipaapi_context):
self.check_ipa_params()
self.define_ipa_commands()
changed = self.execute_ipa_commands(
self.ipa_commands,
result_handler=my_custom_handler,
exit_args=exit_args
)
self.exit_json(changed=changed, **exit_args)
```
The 'process_command_result' should be …
> Deprecate FreeIPABaseModule in favor of IPAAnsibleModule.

- README-automember.md
- playbooks/automember/automember-default-group-not-set.yml
- playbooks/automember/automember-default-group-set.yml
- playbooks/automember/automember-default-hostgroup-not-set.yml
- playbooks/automember/automember-default-hostgroup-set.yml
- playbooks/automember/automember-group-membership-all-users-rebuilt.yml
- playbooks/automember/automember-group-membership-users-rebuilt.yml
- playbooks/automember/automember-group-orphans-removed.yml
- playbooks/automember/automember-hostgroup-membership-all-hosts-rebuilt.yml
- playbooks/automember/automember-hostgroup-membership-hosts-rebuilt.yml
- playbooks/automember/automember-hostgroup-orphans-removed.yml
- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipaautomember.py
- tests/automember/test_automember_client_context.yml
- tests/automember/test_automember_default_group.yml
- tests/automember/test_automember_orphans_removed.yml
- tests/automember/test_automember_rebuilt.yml
- ansible_freeipa_module: New api_get_basedn, IPAAnsibleModule.ipa_get_basedn
These functions have been added to get the basedb from api.env for use
with DN for example.
api_get_basedn is returning api.env.basedn
IPAAnsibleModule.ipa_get_basedn is a wrapper for api_get_basedn
-  automember: Add automember state: rebuilt
There was state: rebuild before, but the code was incomplete and was not
able to run properly.
New parameters:
- users: Limit the rebuild to the given users only
- hosts: Limit the rebuild to the given hosts only
- no_wait: Don't wait for rebuilding membership
New parameters and examples have been added to README-automember.md
tests/automember/test_automember_client_context.yml has been using
state: rebuild and lacked the automember_type parameter.
grouping was used in …
> Automember fixes

- molecule/resources/playbooks/prepare.yml
Sometimes the first test of a batch fails because it fails to grant a
TGT from Kerberos KDC as it is not yet fully working. By waiting until
a TGT can be acquired, these failures will not happen anymore.
> upstream CI: Wait for KDC to be available.

- plugins/modules/iparole.py
- tests/role/test_role.yml
All ansible-freeipa modules which allow object renaming should support
'state: renamed'.
This patch adds suport for the missing state, and fixes cases where a
user could try to rename the object and set its members, which would
fail depending on the operation order.
Fix #566
> iparole: Add state 'renamed'.

- tests/azure/nightly.yml
- tests/azure/templates/playbook_tests.yml
- tests/azure/templates/pytest_tests.yml
This patch modifies the Python version used to be the latest available,
and add stages to execute the tests using ansible-core 2.12. As we
use Ubuntu 20.04, Python version 3.8 is avaiable.
Previously, ansible-core 2.12 was not available as it cannot be
installed with Python 3.6, which was the version used.
> upstream CI: Enable nightly tests using ansible-core 2.12.

- molecule/centos-9/molecule.yml
- tests/azure/azure-pipelines.yml
- tests/azure/nightly.yml
This patch add support for running ansible-freeipa tests with the
CentOS 9 stream images, both on new pull requests and nightly tests.
This must not be merged before #698.
> upstream CI:  Add support for CentOS 9 stream.

- tests/azure/templates/group_tests.yml
When using group_tests, the pytest playbook was not receiving the
Ansible version to use, executing always with the latest available
version.
This patch fixes the behavior by passing the Ansible version to use
for tests to pytest_tests playbook.
> upstrem CI: Fix Ansible version in pytest playbooks.

- README-automountmap.md
- playbooks/automount/automount-map-absent.yaml
- playbooks/automount/automount-map-present.yaml
- plugins/modules/ipaautomountmap.py
- tests/automount/test_automountmap.yml
add module to create and manage auotmount maps
For the tests to work correctly PR #496 needs to be merged first (they need that module to create an automount location to contain the maps they create and manage)
> add module to create and manage automount maps

- plugins/modules/ipagroup.py
- tests/group/test_group.yml
Currently, when adding an overlapping set of members causes playbook to
fail as the already existing members are added twice.
This patch refactors membership management by removing duplicate logic
and handling all changes to members in a single place. This change
removed code that was causing the execution failures.
Fix #707
> ipagroup: Refactor and fix group member management.

- plugins/modules/ipasudorule.py
- tests/sudorule/test_sudorule_single_hostnames.yml
Single hostnames can be used for sudorule_add_host and will match fqdn
in IPA internally. Simple host names have to be extended to be FQDN to
be able to compare them for sudorule_host_add and sudorule_host_remove.
Fixes #672
> sudorule: Create FQDN from single hostnames

- plugins/modules/ipaautomountmap.py
- tests/sanity/ignore-2.12.txt
ERROR: plugins/modules/ipaautomountmap.py:118:30: E203: whitespace before ':'
ERROR: Found 1 compile issue(s) on python 2.6 which need to be resolved:
ERROR: plugins/modules/ipasudorule.py:382:63: SyntaxError: {ensure_fqdn(value.lower(), default_domain) for value in host}
> ansible-test fixes

- .pre-commit-config.yaml
This fixes the import error for render_group from rich.console.
> pre-commit: Update ansible-lint version to v5.3.2

- .github/workflows/lint.yml
- roles/ipabackup/library/ipabackup_get_backup_dir.py
- roles/ipaclient/action_plugins/ipaclient_get_otp.py
- roles/ipaclient/library/ipaclient_api.py
- roles/ipaclient/library/ipaclient_get_facts.py
- roles/ipaclient/library/ipaclient_get_otp.py
- roles/ipaclient/library/ipaclient_setup_nis.py
- roles/ipaclient/library/ipaclient_setup_ntp.py
- roles/ipareplica/library/ipareplica_custodia_import_dm_password.py
- roles/ipareplica/library/ipareplica_setup_certmonger.py
- roles/ipareplica/library/ipareplica_setup_ds.py
- roles/ipareplica/library/ipareplica_setup_http.py
- roles/ipareplica/library/ipareplica_setup_krb.py
- roles/ipareplica/library/ipareplica_test.py
- roles/ipareplica/module_utils/ansible_ipa_replica.py
- roles/ipaserver/library/ipaserver_prepare.py
- roles/ipaserver/library/ipaserver_setup_ntp.py
- roles/ipaserver/library/ipaserver_test.py
- roles/ipaserver/module_utils/ansible_ipa_server.py
- setup.cfg
- utils/lint_check.sh
Pylint was not being applied to ansible-freeipa roles
in upstream CI or in utility scripts. This patch enables
pylint for roles in both scenarios.
> Enable pylint for ansible-freeipa roles.

- plugins/modules/ipahbacsvcgroup.py
- tests/hbacsvcgroup/test_hbacsvcgroup_member_case_insensitive.yml
The hbacsvc members of hbacsvcgroup must be compared in a case
insensitive manner. This patch fixes comparation of member parameters
against existing members by converting parameters to lowercase, as it
is how the hbacsvc members are stored for hbacsvcgroups.
Also, there were some cases where a change with an empty set of members
was issued to IPA API, leading to a result of `changed: yes` when
`changed: no` was expected. The fix involved a refactoring of the
hbacsvcgroup member management code.
This PR should not be merged before PR #683.
> Note: commit ca0aed54b0ab9431a8dc2653ccada66f967e7a3e is part of #683.
> hbacsvcgroup: Fix member management idempotence issues.

- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/iparole.py
- tests/role/test_role_member_case_insensitive.yml
- tests/sanity/ignore-2.12.txt
Members of iparole should be compared in a case insensitive manner,
hosts should always be FQDN, and services should be compared with
the realm.
This PR fixes these issues, by forcing the members comparisons to be
performed always using lowercase characters.
Also, there is some code cleanup, removing unused code, and changing
custom code to the `ansisble_freeipa_module_utils` counterparts.
See the individual commits for more details.
This PR should not be merged before #716
> iparole: Fix idempotence issues

- plugins/modules/ipahbacrule.py
- tests/env_freeipa_facts.yml
- tests/hbacrule/test_hbacrule_member_case_insensitive.yml
Members of hbacrule must be compared in a case insensitive manner.
This patch fixes comparation of member parameters against existing
members by converting parameters to lowercase.
Also, there were some cases where a change with an empty set of members
was issued to IPA API, leading to a result of 'changed: yes' when
'changed: no' was expected. The fix involved a refactoring of the
member management code.
As the tests use the `ipaserver_domain` variable, a task to define it for
every test playbook, avaiable in `env_freeipa_facts.yml`.
> hbacrule: Fix member management idempotence issues.

- plugins/modules/ipahostgroup.py
- tests/hostgroup/test_hostgroup.yml
The host members of ipahostgroup need to be lowercase and FQDN to be
able to do a proper comparison with exising hosts in the hostgroup.
Fixes: #666 (ipahostgroup not idempotent and with error)
> ipahostgroup: Ensure host members are lowercase and FQDN

- plugins/modules/ipadnsconfig.py
- tests/dnsconfig/test_dnsconfig.yml
If one tries to set a list of forwarders which include an already
existing forwarder, the existing forwarder is removed, and the list
of configured forwarders contain only the new ones.
This patch fixes this behavior by setting a union of the currently
available forwarders and the list of forwarders provided in the
playbook.
Tests were added to ensure this behavior.
Fix issue #512
> dnsconfig: Fix management of forwarders.

- README-dnsconfig.md
- plugins/modules/ipadnsconfig.py
- tests/dnsconfig/test_dnsconfig.yml
This patch adds support for 'action: member' for ipadnsconfig plugin,
impacting management of DNS forwarders setting.
Use of 'state: absent' now requires 'action: member'. With 'state:
present', orwarders can be either defined through 'action: dnsconfig'
or added using 'action: member'.
This PR includes commit 95a3da8a73def6c223c806f86411b94c258a4d8f from #735
> dnsconfig: add support for 'action: member'.

- tests/user/test_user.yml
- tests/user/test_users.yml
The client context on server test is failing with a date that is
expired. The server context on server test is not failing.
Setting an expired date with the command line is possible though.
> User tests: Extend expiration dates for client on server test

- tests/automount/test_automountmap.yml
- tests/automount/test_automountmap_client_context.yml
The client context test playbook was missing for ipaautomountmap.
> automountmap: Add client context test playbook.

- plugins/modules/ipasudorule.py
- tests/sudorule/test_sudorule.yml
Upstream tests were not testing one path of code related to variable
`deny_sudocmdgroup`, and a regression was added.
This patch fixes a call to the current configuration dictionary, and
add tests so that the code path is executed in the upstream tests.
> sudorule: Fix management of deny_sudocmdgroup.

- plugins/modules/ipagroup.py
- tests/group/test_group.yml
The services returned by group_find are of type
ipapython.kerberos.Principal. Addtionally the services are case
insensitive. Therefore services need to be converted to a lowercase
sting for proper comparison.
test_group.yml has been extended with service tests.
> group: Services are ipapython.kerberos.Principal and case insensitive

- playbooks/dnsconfig/forwarders-present.yml
As of verison 1.6.1 of ansible-freeipa, ipadnsconfig supports
'action: member' to manage DNS forwardes, and requires the use of this
action if 'state: present'.
This patch fixes the playbook examples.
> dnsconfig: Add 'action: member' to dnsconfig example playbooks.

- plugins/modules/ipauser.py
- tests/user/test_user.yml
- tests/user/test_users.yml
When trying to ensure 'state: absent' with 'preserved: yes' in ipauser,
after the first execution the playbook would fail with "user is already
present". Similar idempotence issue would happen when 'state: undelete'
was used.
This PR fixes both issues, and improve tests for the states where user
is preserved, enabled and disabled. The 'find_user' function now uses
IPA API 'user_show' instead of 'user_find' so that only the requested
user is actually returned.
Fixes #747
> ipauser: Fix idempotence issue when using 'preserved'.

- README-servicedelegationtarget.md
- README.md
- playbooks/servicedelegationtarget/servicedelegationtarget-absent.yml
- playbooks/servicedelegationtarget/servicedelegationtarget-member-absent.yml
- playbooks/servicedelegationtarget/servicedelegationtarget-member-present.yml
- playbooks/servicedelegationtarget/servicedelegationtarget-present.yml
- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipaservicedelegationtarget.py
- tests/servicedelegationtarget/test_servicedelegationtarget.yml
- tests/servicedelegationtarget/test_servicedelegationtarget_client_context.yml
- tests/servicedelegationtarget/test_servicedelegationtarget_hostprincipal.yml
There is a new servicedelegationtarget management module placed in the plugins
folder:
plugins/modules/ipaservicedelegationtarget.py
The servicedelegationtarget module allows to ensure presence and absence of
servicedelegationtargets and servicedelegationtarget members.
Here is the documentation of the module:
README-servicedelegationtarget.md
playbooks/servicedelegationtarget/servicedelegationtarget-absent.yml
playbooks/servicedelegationtarget/servicedelegationtarget-member-absent.yml
playbooks/servicedelegationtarget/servicedelegationtarget-member-present.yml
playbooks/servicedelegationtarget/servicedelegationtarget-present.yml
tests/servicedelegationtarget/test_servicedelegationtarget.yml …
> New servicedelegationtarget management module

- README-servicedelegationrule.md
- README.md
- playbooks/servicedelegationrule/servicedelegationrule-absent.yml
- playbooks/servicedelegationrule/servicedelegationrule-present.yml
- playbooks/servicedelegationrule/servicedelegationrule-principal-member-absent.yml
- playbooks/servicedelegationrule/servicedelegationrule-principal-member-present.yml
- playbooks/servicedelegationrule/servicedelegationrule-target-member-absent.yml
- playbooks/servicedelegationrule/servicedelegationrule-target-member-present.yml
- plugins/modules/ipaservicedelegationrule.py
- tests/servicedelegationrule/test_servicedelegationrule.yml
- tests/servicedelegationrule/test_servicedelegationrule_client_context.yml
- tests/servicedelegationrule/test_servicedelegationrule_hostprincipal.yml
There is a new servicedelegationrule management module placed in the plugins
folder:
plugins/modules/ipaservicedelegationrule.py
The servicedelegationrule module allows to ensure presence and absence of
servicedelegationrules and servicedelegationrule members.
Here is the documentation of the module:
README-servicedelegationrule.md
playbooks/servicedelegationrule/servicedelegationrule-absent.yml
playbooks/servicedelegationrule/servicedelegationrule-principal-member-absent.yml
playbooks/servicedelegationrule/servicedelegationrule-principal-member-present.yml
playbooks/servicedelegationrule/servicedelegationrule-target-member-absent.yml
playbooks/servicedelegationrule/servicedelegationrule-target-member-present.yml …
> New servicedelegationrule management module

- plugins/modules/ipahost.py
Similar to [PR 286](https://github.com/freeipa/ansible-freeipa/pull/286), but applicable to the `ipahost` module.
This PR explicitly sets `no_log` option for `update_password` attribute to `False`, so that the warning on `no_log` not being set is not issued anymore. Ansible incorrectly issued the warning, as `update_password` does not carry sensitive information.
> Fixes `no_log` warning for `ipahost` module

- utils/build-galaxy-release.sh
The script now fixes the references for all doc_fragments in the
plugins/doc_fragments folder. So far it was only fixing the references
for ipamodule_base_docs.
PR #762 (automount location: add support for delete_continue) added an
other doc_fragment and the references have not been fixes as needed.
> build-galaxy-release: Fix refs for all doc_fragments in plugins/doc_fragments

- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipaservicedelegationrule.py
- plugins/modules/ipaservicedelegationtarget.py
- tests/servicedelegationrule/test_servicedelegationrule.yml
- tests/servicedelegationtarget/test_servicedelegationtarget.yml
Ensuring absence of members (services and targets) that do not exist may
not fail as they are not members for servicedelegationtarget and
servicedelegationrule.
servicedelegation_normalize_principals in ansible_freeipa_module has
been extended with a check_exists argument that defaults to False. state
== "present" is now given as this argument to turn on the element exists
check only if elements should be added.
> servicedelegation: Do not fail for not existing members with state absent

- molecule/centos-7/molecule.yml
- molecule/centos-8/molecule.yml
- molecule/centos-9/molecule.yml
- molecule/fedora-latest/molecule.yml
This disables the generation of the collection using the default
galaxy.yml. The installation of the generated collection fails with
invalid version A.B.C.
The collection is not used in the tests and the generated collection
is not using proper name and namespace in the collection files.
Note: utils/build-galaxy-releasesh needs to be used to generate the correct
collection.
> molecule: Disable prerun for normal tests

- tests/azure/nightly.yml
Enables ansible-core 2.12 for CentOS 9 stream on nightly tests.
> upstream ci: enable ansible-core 2.12 for CentOS 9 Stream.

- molecule/c8s-build/Dockerfile
- molecule/c8s-build/molecule.yml
- molecule/c8s/molecule.yml
- tests/azure/azure-pipelines.yml
- tests/azure/build-containers.yml
- tests/azure/nightly.yml
- tests/azure/templates/build_container.yml
- tests/azure/templates/group_tests.yml
- tests/azure/templates/playbook_tests.yml
- tests/azure/templates/pytest_tests.yml
Add configuration to execute build a testing CentOS 8 stream image and
to execute upstream tests using that image in pull requests (Ansible
2.9) and on the nightly tests (all supported Ansible versions).
> upstream CI: Enable CentOS 8 Stream for PR and nightly tests.

- molecule/centos-7-build/molecule.yml
- molecule/centos-8-build/molecule.yml
- molecule/centos-9-build/Dockerfile
- molecule/centos-9-build/molecule.yml
- molecule/fedora-latest-build/molecule.yml
- tests/azure/templates/build_container.yml
Due to changes in Ansible and CentOS, there were some
failures in the creation of testing containers for our upstream
CI.
This PR proposes fixes for three different failures:
* It allows the use of a new parameter to select a specific
Python version, or the latest available if not set.
* Disables `prerun` for molecule playbooks (as in PR #774).
* Remove installation of python3-devel from CentOS 9
Stream image, as it is not needed, and causing failures.
A pipeline showing the actual results can be seen at:
https://dev.azure.com/ansible-freeipa/ansible-freeipa/_build/results?buildId=2078&view=logs&j=51d2d85a-4fe0-5c9b-a9d4-926f090a5dc4
The CentOS 8 failure in the pipeline is expected and will
be adreessed in PR #732.
> upstream CI: Fix container builds in face of Ansible and CentOS changes.

- tests/dnsrecord/env_setup.yml
The test for dnsrecord creates a DNSSEC zone, and was forcing the task
to ignore errors using `ignore_errors: true`. The test environment
should be clean at that point, and without the zone, tests would fail,
so there is no need to keep the attribute set. If the task fails, it
should be fixed.
> ansible-lint: Remove warning on 'ignore_errors'.

- tests/azure/nightly.yml
Changed scenario from old CentOS 8 (centos-8) to current Centos 8
Stream (c8s).
> upstream ci: Fix scenario for Centos 8 Stream with Ansible 2.11.

- plugins/doc_fragments/ipamodule_base_docs.py
- plugins/module_utils/ansible_freeipa_module.py
Allows the creation of IPAAnsibleModule objects with specific
`ipa_arguments` which are defined in a dictionary of argumets in
the base class.
Every module using `delete_continue` should provide the proper behavior
and the module must be instantiated with:
ansible_module = IPAAnsibleModule(
...,
ipa_arguments=["delete_continue"]
)
The plugin documentation must be extended with
'ipamodule_arguments.delete_continue'.
> IPAAnsibleModule: Provide base configuration for delete_continue.

- plugins/modules/ipahbacrule.py
- tests/hbacrule/test_hbacrule_member_empty.yml
If a hbacrule member has any value, the only way to clear it is by
creating a task with 'state: absent' and 'action: member' and provide
a list with all the values for that member.
This patch allows the use of '<member>: []' with 'action: hbacrule'
to clear a hbacrule member.
Fix #751
> hbacrule: Allow clearing members with empty lists.

- README-service.md
- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipaconfig.py
- plugins/modules/ipahost.py
- plugins/modules/ipaservice.py
- plugins/modules/ipauser.py
- tests/config/test_config_empty_string_params.yml
- tests/host/test_host_empty_string_params.yml
- tests/service/test_service_empty_string_params.yml
- tests/user/test_user_empty_string_params.yml
So far it is possible to pass list parameters with empty strings to the
modules. The use of empty strings in list does not make a lot of sense,
though. The simple solution is to add a check to module_params_get for
empty strings in returned lists.
module_params_get_lowercase has been changed to use module_params_get to
have one place to add the check.
> module_params_get*: Fail on empty string in string list parameters

- .github/workflows/lint.yml
- .pre-commit-config.yaml
- requirements-dev.txt
- roles/ipaclient/module_utils/ansible_ipa_client.py
- setup.cfg
Updated pylint to the latest version supported by
Fedora 36 and FreeIPA, and fix issues found with
this release.
> Update pylint to version 2.12.2

- .ansible-lint
Failing to identify task files included by playbooks raised false
positives when runnnig ansible lint. This change force ansible-lint to
correctly identify YAML files named "env_*.yml" or "tasks_*.yml" as task
files that are imported by other playbooks, and treat them accordingly.
> ansible-lint: Identify env_*.yml and tasks_*.yml as task files.

- utils/templates/ipamodule+member.py.in
- utils/templates/ipamodule.py.in
Currently, along to idempotence issues fixes, modules have
used `IPAAnsibleModule.params_get_lowercase` method for
attributes that should use case insensitive comparison, and
the logic of member management has been refactored to
group the command list additions.
This PR add examples of both to the templates used in
`new_module`.
> Update module templates to current practices.

- utils/templates/module-absent.yml.in
- utils/templates/module-member-absent.yml.in
- utils/templates/module-member-present.yml.in
- utils/templates/module-present.yml.in
Add missing ipaadmin_password to example playbooks so new modules have
all necessary fields set on basic files.
> utils/new_module templates: Add missing password to example playbooks.

- README-dnsconfig.md
- README-dnsforwardzone.md
- plugins/modules/ipadnsconfig.py
- plugins/modules/ipadnsforwardzone.py
Modules ipadnsconfig and ipadnsforwardzone allow the setting of forward
policy for zone forwarders, but the parameter names differ between the
modules.
This patch ensures that the same parameter names can be used in each
module. To keep backwar compatibility in both modules, both
`forward_policy` and `forwardpolicy` are now supported.
> DNS forward policy: ensure consistency between module parameters.

- README-trust.md
- plugins/modules/ipatrust.py
Ensure only valid choices for trust_type ('ad')  are available for the
module parameter.
> ipatrust: Set valid choices for trust_type.

- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipaautomountmap.py
- plugins/modules/ipauser.py
- tests/automount/test_automountmap.yml
- tests/user/test_user_empty_lists.yml
This change modifies the comparison of the retrieved IPA object and the
provided arguments on ansible_freeipa_module.compare_args_ipa when the
provider argument is an empty string.
If an attribute is not available in 'ipa', its value is considered to be
a list with an empty string (['']), possibly forcing the conversion of
the 'args' attribute to a list for comparison. This allows, for example,
the usage of empty strings which should compare as equals to inexistent
attributes (None), as is done in IPA API.
Modules `ipauser` and `ipaautomountmap` are modified to use the new
behavior.
> module_utils: Fix comparison of elements not in IPA object.

- plugins/modules/ipatrust.py
- tests/trust/test_trust.yml
- tests/trust/test_trust_client_context.yml
While implementing `ipaidrange` module,  it was found that
`ipatrust` support for `range_type` was missing.
This PR fixes support for attribute `range_type` in `ipatrust`
and improves test coverage and execution for this module.
Please, see individual commits for detailed changes.
> ipatrust: fix range_type and test enhancement.

- plugins/modules/ipaautomountmap.py
This PR improves parameter checking and error messages
in `ipaautomountmap` module.
* Commit 1a31f62a6f63689ea2f35775cc1d16c446078b96:
> Fix error messages when the wrong number of 'name' is
provided
* Commit  23e07a9a17d76ed469ed03805d645503f27f7fde:
> Ensure automountmapname is never None or empty, and
is always set in calls to IPA API.
> ipaautomountmap: Fix parameter evaluation.

- README-idrange.md
- README.md
- playbooks/idrange/idrange-absent.yml
- playbooks/idrange/idrange-ad-posix-present.yml
- playbooks/idrange/idrange-ad-present.yml
- playbooks/idrange/idrange-present.yml
- plugins/modules/ipaidrange.py
- tests/idrange/tasks_remove_trust.yml
- tests/idrange/tasks_set_trust.yml
- tests/idrange/test_idrange.yml
- tests/idrange/test_idrange_client_context.yml
> Note: PR #810 must be merged before this one. Commit 7c1f4c591a32a0f81f64c4ed6e7d2a3e2e120fe9 is part of #810 but is required to test `ipaidrange`.
There is a new idrange management module placed in the plugins folder:
plugins/modules/ipaidrange.py
The idrange module allows to ensure presence and absence of idranges.
Here is the documentation of the module:
README-idrange.md
playbooks/idrange/idrange-absent.yml
playbooks/idrange/idrange-ad-posix-present.yml
playbooks/idrange/idrange-ad-present.yml
playbooks/idrange/idrange-present.yml
New tests for the module can be found at:
tests/idrange/test_idrange.yml
tests/idrange/test_idrange_client_context.yml
> New idrange management module

- README-group.md
- plugins/modules/ipagroup.py
- tests/group/test_group_idoverrideuser.yml
The CLI option `idoverrideusers` was not supported by ansible-freeipa,
and this patch adds support to it.
Tests require an AD trust, and a usere `aduser@ad.ipa.test` to exist.
A new test was added:
tests/group/test_group_idoverrideuser.yml
> Add support for managing idoverrideusers in ipagroup.

- utils/build-galaxy-release.sh
The "-i" option can be used to install the generated collection using
the ansible-galaxy collection install command. It is using the force
flag to install the collection if there is already a collection with the
same name and namespace. The ansible-galaxy collection build command is
already using the force flag to create the collection.
> utils/build-galaxy-release.sh: Add "-i" to install generated collection

- tests/README.md
- tests/azure/templates/playbook_tests.yml
- tests/azure/templates/pytest_tests.yml
- tests/azure/templates/variables.yaml
- tests/sanity/ignore-2.12.txt
- tests/test_playbook_runs.py
- tests/utils.py
pytest provide the means to skip tests based on patterns, but writing
these patterns for ansible-freeipa might not be feasible.
This PR allows the selection of playbook tests and modules that will
be executed with pytest using the environmentt variables IPA_ENABLED_TESTS
IPA_ENABLED_MODULES, IPA_DISABLED_TESTS or IPA_DISABLED_MODULES.
When using IPA_ENABLED_MODULES, all modules will be disabled, and only
the modules in the enabled list will be tested. If using the test
filter, IPA_ENABLED_TESTS, all tests are disabled, unless they are in
the enabled test lists.
If the IPA_DISABLED_* version is used, tests and modules are enabled by
default, and the list is used to disable the module or specific test.
To disable a test or module in Azure CI, edit the file
`tests/azure/variables` and add …
>  Add support to define which playbook tests to execute with pytest.

- requirements-dev.txt
When developing ansible-freeipa using a Python virtual environment,
some ansible-freeipa utility scripts failed to execute due to missing
tools.
This patch add the required tools and modules to requirements-dev.txt
and pin the versions to the same available in Fedora 36.
> requirements-dev: Update requirements for virtual environments

- tests/idrange/test_idrange.yml
There were some typos in the idrange test playbook.
> idrange: Fix typo in test comments.

- README.md
- playbooks/install-smartcard-clients.yml
- playbooks/install-smartcard-replicas.yml
- playbooks/install-smartcard-server.yml
- playbooks/install-smartcard-servers.yml
- roles/ipasmartcard_client/README.md
- roles/ipasmartcard_client/defaults/main.yml
- roles/ipasmartcard_client/files/ipasmartcard_client_add_ca_to_sssd_auth_ca_db.sh
- roles/ipasmartcard_client/files/ipasmartcard_client_add_ca_to_systemwide_db.sh
- roles/ipasmartcard_client/files/ipasmartcard_client_add_pkcs11_module_to_systemwide_db.sh
- roles/ipasmartcard_client/library/ipasmartcard_client_get_vars.py
- roles/ipasmartcard_client/library/ipasmartcard_client_validate_ca_certs.py
- roles/ipasmartcard_client/meta/main.yml
- roles/ipasmartcard_client/tasks/main.yml
- roles/ipasmartcard_client/vars/default.yml
- roles/ipasmartcard_server/README.md
- roles/ipasmartcard_server/defaults/main.yml
- roles/ipasmartcard_server/files/ipasmartcard_server_add_ca_to_sssd_auth_ca_db.sh
- roles/ipasmartcard_server/files/ipasmartcard_server_add_ca_to_systemwide_db.sh
- roles/ipasmartcard_server/files/ipasmartcard_server_enable_ocsp_directive.sh
- roles/ipasmartcard_server/files/ipasmartcard_server_mark_httpd_cert_as_trusted.sh
- roles/ipasmartcard_server/library/ipasmartcard_server_get_vars.py
- roles/ipasmartcard_server/library/ipasmartcard_server_validate_ca_certs.py
- roles/ipasmartcard_server/meta/main.yml
- roles/ipasmartcard_server/tasks/main.yml
- roles/ipasmartcard_server/vars/default.yml
There are new smartcard roles in the roles folder:
roles/ipasmartcard_server
roles/ipasmartcard_client
This roles allows to setup smartcard for servers and clients.
Here is the documentation for the roles:
roles/ipasmartcard_server/README.md
roles/ipasmartcard_client/README.md
playbooks/install-smartcard-server.yml
playbooks/install-smartcard-replicas.yml
playbooks/install-smartcard-servers.yml
playbooks/install-smartcard-clients.yml
> New roles for smartcard server and client setup

- README-idrange.md
- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipaidrange.py
- setup.cfg
- tests/idrange/test_idrange.yml
When an idrange does not exist, if `dom_name` is used to
ensure `state: present` it fails because de domain SID is
required to create a new idrange.
This patch allows domain SID to be obtained form `dom_name`,
fixing the behavior when an idrange needs to be created and
only `dom_name` is provided.
This is related to [RHBZ#2086993](https://bugzilla.redhat.com/show_bug.cgi?id=2086993) and [RHBZ#2086994](https://bugzilla.redhat.com/show_bug.cgi?id=2086994)
> idrange: Fix usage of dom_name when idrange doesn't exist.

- plugins/modules/ipaidrange.py
The parameter 'dom_name' must not be set when 'state:absent', but
it was not on the 'invalid' list..
> idrange: Fix list of invalid parameters for 'state:absent'.

- tests/azure/azure-pipelines.yml
- tests/azure/nightly.yml
- tests/azure/templates/galaxy_pytest_script.yml
- tests/azure/templates/galaxy_script.yml
- tests/azure/templates/galaxy_tests.yml
Provide a pipeline to test ansible-freeipa as an Ansible Galaxy
collection. The tests will use 'utils/build-galaxy-release.sh' to
create the galaxy release file, install it as a collection, andrun the
tests in it, which were modified to use FQCN.
The tests will run only on 'fedora-latest' for each PR, and on all
platforms for nightly and weekly tests.
> upstream CI: Add support for testing ansible-freeipa as a collection.

- tests/azure/nightly.yml
In upstream, Ansible only supports the latest version and the two
previous versions. Today, the versions supported are 2.13 (latest),
2.12 and 2.11.
ansible-freeipa upstream tests should only use Ansible upstream
supported versions as a way to reduce the number of jobs in
the tests, and to avoid errors due to unsupported features.
This PR ensures that only Ansible versions, supported in upstream,
are used in ansible-freeipa test matrix.
This should not be merged before #825
> upstream CI: Update nightly Ansible versions.

- roles/ipaserver/tasks/copy_external_cert.yml
With ansible-2.13 it is required to use jinja for list concatenation.
list: "[] + ['a'] + ['b']"
needs to become
list: "{{ [] + ['a'] + ['b'] }}"
copy_external_cert.yml needed to be changed.
> ipaserver: Use jinja for list concatenation

- plugins/module_utils/ansible_freeipa_module.py
- roles/ipaclient/library/ipaclient_api.py
- roles/ipaclient/library/ipaclient_setup_nis.py
- roles/ipaclient/library/ipaclient_setup_nss.py
- roles/ipaclient/library/ipaclient_setup_ntp.py
- roles/ipaclient/library/ipaclient_test.py
- roles/ipaclient/module_utils/ansible_ipa_client.py
- roles/ipareplica/library/ipareplica_custodia_import_dm_password.py
- roles/ipareplica/library/ipareplica_setup_ds.py
- roles/ipareplica/library/ipareplica_setup_http.py
- roles/ipareplica/library/ipareplica_setup_krb.py
- roles/ipareplica/library/ipareplica_test.py
- roles/ipareplica/module_utils/ansible_ipa_replica.py
- roles/ipaserver/library/ipaserver_setup_ntp.py
- roles/ipaserver/library/ipaserver_test.py
- roles/ipaserver/module_utils/ansible_ipa_server.py
Python 3.11 dropped compat inspect.getargspec. As the roles and modules
need to support Python2 and Python3, the code for getargspec has been
copied from Python 3.10 and is added as a fallback as soon as getargspec
can not be imported from inspect. The copied getargspec is using
getfullargspec internally.
Fixes: #855 (Python's inspect.getargspec was removed in version 3.11)
> Provide own getargspec for roles and modules with Python 3.11

- plugins/module_utils/ansible_freeipa_module.py
api_check_ipa_version was using packaging.version. IPA is using
pkg_resources.parse_version in ipaplatform.tasks.parse_ipa_version.
With this change tasks.parse_ipa_version from ipaplatform is used to
have exactly the same version comparison that also IPA has.
Additionally tasks is added to __all__.
> ansible_freeipa_module: Use ipaplatform.tasks.parse_ipa_version

- molecule/fedora-rawhide-build/Dockerfile
- molecule/fedora-rawhide-build/molecule.yml
- molecule/fedora-rawhide/molecule.yml
- tests/azure/build-containers.yml
- tests/azure/nightly.yml
This patch enable upstream CI to build a testing Fedora Rawhide
container and enables its use in nightly and weekly test runs.
> upstream CI: enable tests on Fedora Rawide.

- plugins/modules/ipadnsconfig.py
- tests/azure/templates/variables.yaml
- tests/dnsconfig/test_dnsconfig.yml
- tests/dnsconfig/test_dnsconfig_forwarders_ports.yml
In later versions of FreeIPA (4.9.10+) the handling of LDAP
boolean values has been fixed, but this changes were not
applied to ipadnsconfig.
This PR fixes this issues and split the ipadnsconfig tests
so that at least part of the tests can be executed while
there is still an issue with FreeIPA and python-dns 2.2.0.
Fix issue #862
> ipadnsconfig: Fix boolean values comparison

- roles/ipareplica/library/ipareplica_prepare.py
- roles/ipareplica/library/ipareplica_setup_adtrust.py
- roles/ipareplica/library/ipareplica_test.py
- roles/ipareplica/module_utils/ansible_ipa_replica.py
- roles/ipareplica/tasks/install.yml
- roles/ipaserver/library/ipaserver_prepare.py
- roles/ipaserver/library/ipaserver_test.py
- roles/ipaserver/tasks/install.yml
The SID is always generated in the command line installers in newer IPA
versions. This also needs to be done in the ipaserver and ipareplica roles.
For the IPA versions that are supporting this, the adtrust setup is always
executed to generated the SIDs, but only configures AD trust if
ipaserver_setup_adtrust or ipareplica_setup_adtrust is also enabled. A
check has been added to ipaserver_test and ipareplica_test to only enable
the SID generation for the IPA versions supporting this.
This is related to https://pagure.io/freeipa/8995
Fixes:
- https://bugzilla.redhat.com/show_bug.cgi?id=2110478
- https://bugzilla.redhat.com/show_bug.cgi?id=2110491
> ipaserver/ipareplica: Always generate SIDs

- roles/ipaclient/library/ipaclient_test.py
- Call was responsible for a `TypeError` exception
- Call was not useful (already followed by a proper `logger.warning` call)
Should fix issue #865: https://github.com/freeipa/ansible-freeipa/issues/865
> ipaclient: Removed invalid call `logger.info()`

- roles/ipareplica/tasks/install.yml
The internal parameter sid_generation_always is generated in
ipareplica_test to enable SID generation if ipareplica_setup_adtrust is
not enabled.
This parameter was not used for ipareplica_prepare though, therefore
adtrust.install_check was not executed and did not set the attribute
adtrust.netbios_name. As a result adtrust.netbios_name was None and the
try to use this as the new NetBIOS domain name failed with an
INVALID_SYNTAX error in adtrustinstance while executing
ipareplica_setup_adtrust.
This issue only occurs if SIDs are not enabled in the domain yet for
example with an old deployment.
> ipareplica: ipareplica_setup_adtrust fails while updating ipaNTFlatName

- plugins/modules/ipavault.py
flake8 reports an issue in ipavault:
plugins/modules/ipavault.py:528:20: E275 missing whitespace after keyword
The missing whitespace has been added: "and not(" -> "and not ("
> ipavault: Fix missing whitespace after keyword issue

- plugins/modules/ipasudorule.py
Some examples in ipasudorule were using `action: enabled` when it
should've been `state: enabled`. The examples were fixed.
Fixes #885
> ipasudorule: Fix usage of 'action' and 'state' in examples.

- tests/azure/templates/galaxy_script.yml
- tests/azure/templates/playbook_tests.yml
- tests/azure/templates/pytest_tests.yml
- tests/azure/templates/variables_c8s.yaml
- tests/azure/templates/variables_c9s.yaml
- tests/azure/templates/variables_centos-7.yaml
- tests/azure/templates/variables_fedora-latest.yaml
- tests/azure/templates/variables_fedora-rawhide.yaml
- tests/sanity/ignore-2.12.txt
- tests/test_playbook_runs.py
- tests/utils.py
- utils/check_test_configuration.py
This patch allows the configuration of enabled/disabled tests
in a per-test scenario way, allowing a test to be enabled or
disable depending on the Linux distribution used to run the
tests.
It also changes the 'skip' behavior of disabled tests to not
include the tests anymore, so that disabled tests are not
'skip'-ed, but are not even evaluated anymore.
Please, check individual commits for details.
> upstream CI: enable/disable tests based on test image

- README-user.md
- plugins/modules/ipauser.py
Attributes 'first' and 'last' are required if user does not exist, but
current documentation doesn't make it clear. This patch adds a note on
both attributes to make clear the cases where the attribute is required.
Fixes #881
> ipauser: Add note on attributes 'first' and 'last' requirements

- roles/ipareplica/tasks/install.yml
The NTP server chrony was always enabled and set up due to overwriting
the parameter ipaclient_no_ntp for the client part deployment.
For IPA deployments upt to 4.6 no_ntp was always used for the client
part deployment in ipa-replica-install. But afterwards ntp was
configured in the replica deployment part if no_ntp was not set.
The ipareplica roles always relied on the client for setting up the NTP
server but overwrote the setting for the client deployment part. This
did not result in a failure to enable the chrony server in RHEL and Fedora
based distributions as NTP server was always required by the ipa-server
package.
Fixes: #871 (ipa-replica-install with no-ntp is ignored)
> ipareplica: Do not overwrite ipaclient_no_ntp for client part deployment

- tests/utils.py
When enabling or disabling multiple tests, a comma separated list must
be used, but current code is using a colon to split the list.
This patch fixes this behavior.
> upstream CI: Fix list evaluation in IPA_ENABLED/IPA_DISABLED tests

- tests/azure/templates/variables_fedora-rawhide.yaml
Some DNS tests have been disabled for Fedora latest, but not for Fedora
Rawhide. Therefore these tests are filin still in nighty:
- dnsforwardzone
- test_dnsconfig_forwarders_ports
> fedora rawhide: Temporarily disable failing DNS tests

- roles/ipaserver/tasks/install.yml
The client part installation is checking for the client packages. These
packages are part of the server packages that have been installed with
the server role and therefore the task is not needed.
This is helping to reduce the deployment time of a server.
> ipaserver: ipaclient part does not need to install packages

- roles/ipaserver/library/ipaserver_test.py
- roles/ipaserver/module_utils/ansible_ipa_server.py
The idstart needs to be larger than UID_MAX or GID_MAX from /etc/login.defs.
This is "Require idstart to be larger than UID_MAX" for freeipa.
Fixes: #896 (Invalid RID/SID SSSD backtrace after deployment)
> ipaserver: Add missing idstart check

- .ansible-lint
- requirements-docker.yml
- requirements-podman.yml
- tests/README.md
- tests/utils.py
- utils/run-tests.sh
This patch allows local execution of playbook tests using ustream CI
testing images. Either 'podman' or 'docker' can be used to execute the
tests.
> Run tests locally with upstream CI images.

- roles/ipareplica/module_utils/ansible_ipa_replica.py
- roles/ipaserver/module_utils/ansible_ipa_server.py
In some cases ipa code is using sys.stdout.isatty. As stdout is mapped
to AnsibleModuleLog this call will lead in a traceback as it was not
defined.
The staticmethod isatty has been added to AnsibleModuleLog in ipaserver
role module_utils/ansible_ipa_server.py and in ipareplica role
module_utils/ansible_ipa_repica.py.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2120415
ansible-freeipa Replica Install Setup DNS fails
Fixes: #251 - 'AnsibleModuleLog' object has no attribute 'isatty'
Fixes: #117 - 'AnsibleModuleLog' object has no attribute 'isatty'
> ipaserver/ipareplica: Add isatty method to AnsibleModuleLog

- requirements-tests.txt
- tests/azure/pr-pipeline.yml
- tests/azure/templates/fast_tests.yml
- tests/azure/templates/galaxy_script.yml
- tests/azure/templates/playbook_fast.yml
- tests/azure/templates/playbook_tests.yml
- utils/check_test_configuration.py
- utils/get_test_modules.py
- utils/set_test_modules
The current workflow for bug fixing or new enhancements in
ansible-freeipa includes running Ansible playbooks tests for all the
available plugins for every pull request, even for contained
modifications.
This patch creates a new workflow for pull requests where only the
affected plugins are tested in the PR. Changes that might affect other
parts of the code will trigger tests for the parts affected.
A utility script, utils/filter_tests, is used to set the variables
IPA_ENABLED_MODULES and IPA_ENABLED_TESTS before executing the tests,
effectively limiting which tests are executed. The script can be
executed locally to list the tests that are expected run.
Tests are selected for execution based on the plugin name. For example,
a change to 'plugins/modules/ipalocation.py' would trigger all …
> upstream CI: run PR tests only for affected plugins

- utils/set_test_modules
If the repository is setup in a way that master branch is not available
for comparing the current HEAD against it, the comparison will fail and
not module/role will be scheduled for testing.
This patch forces fetching 'master' from ansible-freeipa repository,
allowing the comparison to be performed.
> upstream CI: Ensure 'master' branch is available for set_test_modules

- utils/set_test_modules
This patch forces the addition of a remote repository pointing to the
main ansible-freeipa repo, and fetch its contents before confaring the
modified files. The remote repository is removed after the modified
file list is generated.
> upstream CI: Force retrieval of ansible-freeipa master.

- roles/ipabackup/tasks/main.yml
- tests/backup_role/test_backup.yml
- utils/set_test_modules
When performing a backup with 'state:present', if 'ipabackup_name' is
provided, the backup will be performed, but the role with return an
error since 'ipabackup_name' should not be set for this state.
This patch moves the parameter evaluation to be performed before the
actual backup is performed, so that the backup is not performed and an
error is reported.
FIxes #900
> ipabackup: Fix order of ipabackup_name parameter evaluation.

- README-config.md
- playbooks/config/change-ipa-domain-netbios-name.yml
- playbooks/config/generate-users-groups-sids.yml
- plugins/modules/ipaconfig.py
- tests/azure/templates/variables_centos-7.yaml
- tests/config/test_config_sid.yml
Since FreeIPA 4.9.8 the 'config_mod' command has parameters to enable
and configure SIDs, and set the Netbios name.
This patch adds the following parameters to ipaconfig plugin:
enable_sids: New users and groups automatically get a SID assigned
add_sids: Add SIDs for existing users and groups
netbios_name: NetBIOS name of the IPA domain
Both add_sids and netbios_name requires 'enable_sid: yes'.
'enable_sid' and 'netbios_name' are returned when querying IPA
configuration.
'add_sids' always generate SIDs for users and groups, so, muiltiple
executions of the playbook with 'add_sids: yes' will return 'changed',
even if users and groups SIDs are not modified.
Fixes: #781
Related: https://bugzilla.redhat.com/show_bug.cgi?id=2069174
Related: https://bugzilla.redhat.com/show_bug.cgi?id=2069184
> ipaconfig: Add support for SID related attributes.

- playbooks/config/retrieve-config.yml
- playbooks/config/set-ca-renewal-master-server.yml
`ipaconfig` playbooks had "DNS configuration" on the titles, but they manage global IPA configuration.
> ipaconfig: Fix example playbook titles.

- tests/azure/templates/variables_c8s.yaml
- tests/azure/templates/variables_c9s.yaml
- tests/azure/templates/variables_centos-7.yaml
- tests/azure/templates/variables_fedora-latest.yaml
- tests/azure/templates/variables_fedora-rawhide.yaml
This PR re-enables upstream CI tests that include DNS forwarders with port specification.
> Re-enable dnsforwardzone tests

- roles/ipasmartcard_client/library/ipasmartcard_client_get_vars.py
All imports that are only available after installing IPA need to be in a try exception clause to be able to pass the fake execution test.
If the imports can not be done, all used and needed attributes are defined with the value None, MODULE_IMPORT_ERROR is set to the import error and fail_json is called.
> ipasmartcard_client_get_vars: Fix for ansible-test fake execution test

- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipadnsrecord.py
- plugins/modules/ipadnszone.py
- tests/sanity/ignore-2.12.txt
ansible_freeipa_module: Fix ansible-test fake execution test findings
All imports that are only available after installing IPA need to be in a
try exception clause to be able to pass the fake execution test. The old
workaround "if 'ansible.executor' in sys.modules:" is not working with
this test anymore.
If the imports can not be done, all used and needed attributes are
defines with the value None.
A check has been added to IPAAnsibleModule.__init__ to make sure that it
ipadnsrecord: Fix for ansible-test fake execution test
All imports that are only available after installing IPA need to be in a
try exception clause to be able to pass the fake execution test.
If the imports can not be done, all used and needed attributes are
defined with the value None, MODULE_IMPORT_ERROR is set to the …
> Fix plugins for ansible fake execution test

- plugins/modules/ipaautomember.py
- `required` tag was fixed according to the argument_spec
arguemnt_spec
- `no_log=False` or `no_log=True` needs to be set for all parameters that have `key` in the name or for dicts also in one the key names.
> ipaautomember: Fix documentation sections and agument spec

- plugins/modules/ipaautomountlocation.py
argument_spec
- `default=.*` needs to be dropped if `required=True` is also given
> ipaautomountlocation: Fix documentation sections and agument spec

- plugins/modules/ipaconfig.py
- `module` tag needs to be correct
- `type: int` needs to be set for integer parameters
- `type: string` is not valid and needs to be replaced by `type: str`
RETURN section
- `contains` needs to be used instead of `options` for dicts
- `type: int` needs to be set for integer parameters
- `type: list` needs to be set for list …
> ipaconfig: Fix documentation sections and agument spec

- plugins/modules/ipadelegation.py
> ipadelegation: : Fix documentation sections and agument spec

- plugins/modules/ipadnsconfig.py
- `type: int` needs to be set for integer parameters
- `aliases` tag need to be consistent to `argument_spec`
argument_spec
- `type=str` and `type=int` need to be replaced by `type="str"` and `type="int"`
> ipadnsconfig: Fix documentation sections and agument spec

- plugins/modules/ipagroup.py
- `type: int` needs to be set for integer parameters
argument_spec
> ipagroup: Fix documentation sections and agument spec

- plugins/modules/ipahbacrule.py
> ipahbacrule: Fix documentation sections and agument spec

- plugins/modules/ipalocation.py
> ipalocation: Fix documentation sections and agument spec

- plugins/modules/ipahbacsvc.py
> ipahbacsvc: Fix documentation sections and agument spec

- plugins/modules/ipahbacsvcgroup.py
> ipahbacsvcgroup: Fix documentation sections and agument spec

- plugins/modules/ipahostgroup.py
> ipahostgroup: Fix documentation sections and agument spec

- plugins/modules/ipatrust.py
- `type: int` needs to be set for integer parameters
- `type: bool` needs to be set for bool parameters
- `choices` needs to match `argument_spec`
argument_spec
- `default=.*` needs to be dropped if `required=True` is also given
> ipatrust Fix documentation sections and agument spec

- plugins/modules/ipasudocmdgroup.py
> ipasudocmdgroup: Fix documentation sections and agument spec

- plugins/modules/ipatopologysuffix.py
argument_spec
- `type="str"` needs to added to all string parameters
> ipatopologysuffix: Fix documentation sections and agument spec

- plugins/modules/ipasudocmd.py
> ipasudocmd: Fix documentation sections and agument spec

- plugins/modules/ipaservicedelegationtarget.py
> ipaservicedelegationtarget: Fix documentation sections and agument spec

- plugins/modules/ipaservicedelegationrule.py
> ipaservicedelegationrule: Fix documentation sections and agument spec

- plugins/modules/ipapwpolicy.py
- `extends_documentation_fragment: ipamodule_base_docs` needs added and `ipaadmin_*` parameters need to be removed
argument_spec
> ipapwpolicy: Fix documentation sections and agument spec

- plugins/modules/ipaidrange.py
- `type: string` is not valid and needs to be replaced by `type: str`
argument_spec
> ipaidrange: Fix documentation sections and agument spec

- plugins/modules/ipaprivilege.py
> ipaprivilege: Fix documentation sections and agument spec

- plugins/modules/ipaselfservice.py
> ipaselfservice: Fix documentation sections and agument spec

- plugins/modules/iparole.py
- all parameters need to be defined
argument_spec
> iparole: Fix documentation sections and agument spec

- plugins/modules/ipaserver.py
> ipaserver: Fix documentation sections and agument spec

- plugins/modules/ipaconfig.py
Ansible's fail_json() method required that the message paramater was passed with a keyword parameter, rather than a positional one. Although this seems to work with ansible-core 2.13+, it might not work with previous versions of Ansible.
This patch fixes the behaviour for all supported Ansible versions.
> ipaconfig: Fix fail_json calls.

- README-config.md
- plugins/modules/ipaconfig.py
- tests/config/test_config_sid.yml
Current behavior of ipaconfig mimics FreeIPA CLI and requires that
'enable_sid' is set to True every time add_sids or netbios_name are
used. It is sufficient that SID generation is enabled to use add_sids
and netbios_name, but the IPA API requires 'enable_sid' so that the
operations are executed.
This patch allows ansible-freeipa plugin ipaconfig to run 'add_sids' or
set 'netbios_name without requiring 'enable_sid' to be set on the
playbook.
If SID generation is enabled, 'add_sids' and 'netbios_name' can be used
without 'enable_sid: yes'. If SID generation is not enabled, an error
message will be raised if 'enable_sid: yes' is not used.
Depends on PR #921 being merged (due to commit 3c7bd565ecfbca802110f85ef8ae679c053d8bdb).
Fixes …
> ipaconfig: Do not require enable_sid for add_sids or netbios_name

- utils/new_module
- utils/templates/README-module+member.md.in
- utils/templates/README-module.md.in
- utils/templates/ipamodule+member.py.in
- utils/templates/ipamodule.py.in
ansible-test with ansible-2.14 is adding a lot of new tests to ensure that the documentation section and the agument spec is complete.
To aid the creation of new_modules that follow these rules, the 'new_module' script and its templates were modified to use the new ansible-test rules. The 'new_module' script now requires a new argument, github_user, and the code templates provide the required fields (like 'type' and 'elements') to the provide examples.
> new_module: Modify new_module and templates for Ansible 2.14

- plugins/modules/ipahost.py
- plugins/modules/ipaservice.py
This change follows language use recomendation from NISTIR 8366, "Guidance for NIST Staff on Using Inclusive Language in Documentary Standards", accessible from
https://nvlpubs.nist.gov/nistpubs/ir/2021/NIST.IR.8366.pdf
> documentation: Change occurences of whitelist to allowlist.

- plugins/modules/ipatopologysegment.py
argument_spec
- `type="str"` needs to added to all string parameters
> ipatopologysegment: Fix documentation sections and agument spec

- plugins/modules/ipadnsforwardzone.py
- `module` tag needs to be correct
- `action` parameter is missing and added
argument_spec
> ipadnsforwardzone: : Fix documentation sections and agument spec

- README-vault.md
- plugins/modules/ipavault.py
- `type: bool` needs to be set for bool parameters
- `type: string` is not valid and needs to be replaced by `type: str`
- `choices` needs to match `argument_spec`
- all parameters need to be defined
RETURN section
- `contains` needs to be used instead of `options` for …
> ipavault: Fix documentation sections and agument spec

- plugins/modules/ipauser.py
- `elements: dict` needs to be given for list of dict parameters
RETURN section
- `contains` needs to be used instead of `options` for dicts
- `type: str` needs to be used for string parameters
argument_spec
- `no_log=False` or `no_log=True` needs to be set for all …
> ipauser: Fix documentation sections and agument spec

- plugins/modules/ipahost.py
- tests/host/test_host_sshpubkey.yml
- `type` tag needs to match `argument_spec`
RETURN section
- `contains` needs to be used instead of `options` for dicts
- `type: str` needs to be used …
> ipahost: Fix documentation sections and agument spec

- plugins/doc_fragments/ipamodule_base_docs.py
> ipamodule_base_docs: Fix documentation sections

- plugins/modules/ipadnsrecord.py
- `type: string` is not valid and needs to be replaced by `type: str`
- `choices` needs to match `argument_spec`
- `description` needs to match parameter
- all parameters need to be defined
argument_spec
- `no_log=False` or `no_log=True` …
> ipadnsrecord: Fix documentation sections and agument spec

- README-netgroup.md
- README.md
- playbooks/netgroup/netgroup-absent.yml
- playbooks/netgroup/netgroup-member-absent.yml
- playbooks/netgroup/netgroup-member-present.yml
- playbooks/netgroup/netgroup-present.yml
- plugins/modules/ipanetgroup.py
- tests/netgroup/test_netgroup.yml
- tests/netgroup/test_netgroup_client_context.yml
- tests/netgroup/test_netgroup_member.yml
- tests/netgroup/test_netgroup_member_absent.yml
- tests/netgroup/test_netgroup_member_case_insensitive.yml
There is a new netgroup management module placed in the plugins folder:
plugins/modules/ipanetgroup.py
The netgroup module allows to ensure presence or absence of netgroup
and manage netgroup members.
README-netgroup.md
playbooks/netgroup/netgroup-absent.yml
playbooks/netgroup/netgroup-member-absent.yml
playbooks/netgroup/netgroup-member-present.yml
playbooks/netgroup/netgroup-present.yml
tests/netgroup/test_netgroup.yml
tests/netgroup/test_netgroup_client_context.yml
tests/netgroup/test_netgroup_member.yml
Signed-off-by: Denis Karpelevich <dkarpele@redhat.com>
> New netgroup management module

- tests/netgroup/test_netgroup_member.yml
- tests/netgroup/test_netgroup_member_absent.yml
Tests for ipanetgroup were not correctly clearing up the tests, causing test failures when running them in some specific order.
By fixing the 'name' attribute list the tests succeed, independently of the order they are executed.
> netgroup: Fix environment cleanup on ipanetgroup tests.

- .github/workflows/lint.yml
- plugins/module_utils/ansible_freeipa_module.py
- requirements-dev.txt
- roles/ipaserver/module_utils/ansible_ipa_server.py
- setup.cfg
- utils/galaxyfy-module-EXAMPLES.py
Under Python 3.11 some linters have failed to execute due to deprecated items. Increasing or setting specific allow the linters to succeed with Python's lates version.
> linters: Fix versions of linter packages due to Python 3.11.

- .github/workflows/ansible-test.yml
- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/readme.yml
There are warnings on Github workflows about the need to update actions
'checkout' and 'setup-python' due to the use of Node.js versions that
are too old.
Also Shellcheck is using an old version with deprecated items.
This PR updates the versions of the actions used to remove the warnings.
> upstream ci: Update Github actions due to old Node.js.     

- roles/ipaclient/library/ipaclient_api.py
- roles/ipaclient/library/ipaclient_fix_ca.py
- roles/ipaclient/library/ipaclient_fstore.py
- roles/ipaclient/library/ipaclient_get_facts.py
- roles/ipaclient/library/ipaclient_get_otp.py
- roles/ipaclient/library/ipaclient_ipa_conf.py
- roles/ipaclient/library/ipaclient_join.py
- roles/ipaclient/library/ipaclient_set_hostname.py
- roles/ipaclient/library/ipaclient_setup_automount.py
- roles/ipaclient/library/ipaclient_setup_firefox.py
- roles/ipaclient/library/ipaclient_setup_krb5.py
- roles/ipaclient/library/ipaclient_setup_nis.py
- roles/ipaclient/library/ipaclient_setup_nss.py
- roles/ipaclient/library/ipaclient_setup_ntp.py
- roles/ipaclient/library/ipaclient_setup_ssh.py
- roles/ipaclient/library/ipaclient_setup_sssd.py
- roles/ipaclient/library/ipaclient_test.py
- roles/ipaclient/library/ipaclient_test_keytab.py
- roles/ipaclient/module_utils/ansible_ipa_client.py
All imports that are only available after installing IPA need to be in a
try exception clause to be able to pass the fake execution test. The old
workaround "if 'ansible.executor' in sys.modules:" is not working with
this test anymore.
ansible-test with ansible-2.14 is adding a lot of new tests to ensure
that the documentation section and the agument spec is complete.
The module_utils file ansible_ipa_client and also all the modules in the
role had to be changed.
> Fix ipaclient role for ansible test

- roles/ipasmartcard_server/library/ipasmartcard_server_get_vars.py
- roles/ipasmartcard_server/library/ipasmartcard_server_validate_ca_certs.py
**ipasmartcard_server_get_vars: Fix doc sections and agument spec**
ansible-test with ansible-2.14 is adding a lot of new tests to ensure
that the documentation section and the agument spec is complete. Needed
changes:
- `suboptions` needs to be removed without arguments
**ipasmartcard_server_validate_ca_certs: Fix doc sections and agument spec**
ansible-test with ansible-2.14 is adding a lot of new tests to ensure
that the documentation section and the agument spec is complete. Needed
changes: …
> Fix ipasmartcard server role for ansible test

- roles/ipabackup/library/ipabackup_get_backup_dir.py
- `suboptions` needs to be removed without arguments
> ipabackup_get_backup_dir: Fix documentation sections and agument spec

- roles/ipasmartcard_client/library/ipasmartcard_client_get_vars.py
- roles/ipasmartcard_client/library/ipasmartcard_client_validate_ca_certs.py
**ipasmartcard_client_get_vars: Fix doc sections and agument spec**
ansible-test with ansible-2.14 is adding a lot of new tests to ensure
that the documentation section and the agument spec is complete. Needed
changes:
- `suboptions` needs to be removed without arguments
**ipasmartcard_client_validate_ca_certs: Fix doc sections and agument spec**
ansible-test with ansible-2.14 is adding a lot of new tests to ensure
that the documentation section and the agument spec is complete. Needed
changes:
- `module` needs to match module name
argument_spec
- …
> Fix ipasmartcard client role for ansible test

- README-sudorule.md
- playbooks/sudorule/ensure-sudorule-hostmask-member-is-absent.yml
- playbooks/sudorule/ensure-sudorule-hostmask-member-is-present.yml
- plugins/modules/ipasudorule.py
- tests/sudorule/test_sudorule.yml
The hostmask parameter allows matching a sudorule against a network address, and was missing from ipasudorule module.
Documentation and tests were updated to reflect changes.
Two new example playbooks are available:
playbooks/sudorule/ensure-sudorule-hostmask-member-is-absent.yml
playbooks/sudorule/ensure-sudorule-hostmask-member-is-present.yml
Fixes #676
> sudorule: Add support for 'hostmask' parameter

- README-pwpolicy.md
- playbooks/pwpolicy/pwpolicy_grace_limit.yml
- playbooks/pwpolicy/pwpolicy_password_check.yml
- plugins/modules/ipapwpolicy.py
- tests/pwpolicy/test_pwpolicy.yml
On recent version of FreeIPA options to verify passwords and for controlling a password grace period have been added to IPA API.
This patch adds support for the parameters maxrepeat, maxsequence, dictcheck and usercheck, available since FreeIPA, 4.9 and gracelimit, available since FreeIPA 4.9.10.
Test playbooks for the module have been updated with the new supported parameters.
New example playbooks can be found at:
playbooks/pwpolicy/pwpolicy_grace_limit.yml
playbooks/pwpolicy/pwpolicy_password_check.yml
> pwpolicy: Add support for password check and grace limit.

- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/readme.yml
This patch add 'fetch-depth: 0' to 'checkout' plugin on Github Worflows to slightly speed up verifications.
> github worflows: speed up git checkout.

- .pre-commit-config.yaml
The pycqa pre-commit repos were using 'gitlab.com', instead of 'github.com', which is, today, the correct repository to use.
This patch fixes the addresses for Flake8 and pydocstyle checks.
> pre-commit: Fix pycqa pre-commit repos.

- plugins/module_utils/ansible_freeipa_module.py
A combination of ansible-freeipa modifications and a newer version of IPA has brought a regression regarding different OS localization.
For properly setting environment to use "C" language, as required by ansible-freeipa, the setting must be executed before importing the module 'ipaserver.dcerpc', so setting environment language was moved closer to the 'import os' statement, so that it is always set, as soon as possible.
Note that 'import os' should always be imported before any FreeIPA module.
> This issue was found with the latest FreeIPA version (4.9.11) in Fedora 35.
> environment: Fix os.environ language setting.

- roles/ipaclient/tasks/install.yml
The DNS resolver configuration should not happen in the server client part installation where ipaclient_on_master is enabled.
> ipaclient: No DNS resolver configuration on master

- utils/ansible-freeipa.spec.in
The issue within the for loops to remove python shebangs and to remove the
execution flag from python files has been solved.
> ansible-freeipa.spec.in: Fix for loop with wildcard

- plugins/modules/ipanetgroup.py
- tests/netgroup/test_netgroup.yml
This patch fixes https://bugzilla.redhat.com/show_bug.cgi?id=2144724 which depends on freeipa bug https://pagure.io/freeipa/issue/9284.
The code for `netgroup_find` was taken from the module `ipahostgroup`.
Test for condition was added.
Another approach - is just to wait until fix for freeipa bug #9284 =)
Signed-off-by: Denis Karpelevich <dkarpele@redhat.com>
> Use netgroup_find instead of netgroup_show to workaround IPA bug.

- utils/galaxyfy.py
- utils/get_test_modules.py
The ansible builtins are using the ansible.builtin. prefix now, but the utils files were lacking support for this.
> utils files: Support builtins with ansible.builtin. prefix

- plugins/modules/ipapwpolicy.py
- tests/pwpolicy/test_pwpolicy.yml
- tests/pwpolicy/test_pwpolicy_invalid_data_type.yml
All values for pwpolicy can be cleared with an empty string in IPA CLI, and this behavior was missing in ansible-freeipa.
As of today, there is an issue in FreeIPA that does not allow clearing 'minlength' policy. The is is tracked by the FreeIPA project through https://pagure.io/freeipa/issue/9297
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2150334
> pwpolicy: Allow clearing policy values.

- tests/azure/azure-pipelines.yml
- tests/azure/nightly.yml
- tests/azure/pr-pipeline.yml
As we now have ansible-core 2.14 available through 'pip', the versions used for testing on Azure should be 2.12, 2.13 and 2.14, as Ansible keeps upstream support for the latest version plus the two previous ones.
This patch update the version used in tests by increasing the version used by 1 (MINOR).
Some tests were rename to reflect the version being used in future changes by using the labels 'latest', 'previous' and 'oldest', instead of the actual numbers.
> upstream ci: Update Ansible versions on Azure pipelines.

- .github/workflows/lint.yml
ansible-lint required to be run in a collection source directory with correct and working galaxy.yml
As ansible-freeipa is not converted to a collection, the galaxy.yml file can not be used to create the collection. This needs to be done with utils/build-galaxy-release.sh. The script is fixing all the prefixes for the roles and modules in all the yml files and also example snippets and in the documentation.
Therefore utils/build-galaxy-release.sh is called with the "-k" option to keep the dictory that has been used to generate the collection with the script. Afterwards ansible-lint is run in this build directory.
> .github/workflows/lint.yml: ansible-lint needs collection source dir

- tests/pwpolicy/test_pwpolicy.yml
When clearing minimum length parameter, FreeIPA raises an error, and the error is different when executing the playbook in server or client context. Since the error message is evaluated in the text, both errors must be accepted as "not a failure", since ansible-freeipa did the correct call.
Once https://pagure.io/freeipa/issue/9297 is fixed, the test must be updated to not accept any of these error messages.
> pwpolicy: Fix tests for 'minlength: ""'

- tests/dnszone/test_dnszone.yml
There was a typo ("in" -> "it") in some dnszone test playbook task names.
> dnszone tests: Fix typo on task names.

- playbooks/automount/automount-map-absent.yml
- playbooks/automount/automount-map-present.yml
A few playbooks still had task name starting with lower case letters.
> playbooks: Fix automount tasks to make ansible-lint happy

- tests/azure/templates/galaxy_pytest_script.yml
- tests/azure/templates/galaxy_script.yml
- tests/azure/templates/playbook_fast.yml
- tests/azure/templates/playbook_tests.yml
- tests/azure/templates/pytest_tests.yml
Due to DNS issues and the increase number of tests, the timeout setting used for upstream tests was being reached. As we still have room for running the tests using Azure infrastructure, this patch increases the timeout to 240 minutes (4h), per worker.
> upstream CI: increase Azure test timeout.

- roles/ipabackup/tasks/copy_backup_to_server.yml
ipabackup_item needs to be set again in copy_backup_to_server.yml. The variable is later on used in restore.yml.
> ipabackup: Use ipabackup_item again in copy_backup_to_server

- roles/ipaclient/library/ipaclient_test_keytab.py
The test in ipaclient_test_keytab is at first trying to use an existing krb5.conf to test if the host keytab can be used. With working DNS lookup an absent krb5.conf is not reported as an error as DNS lookup is silently used instead.
A temporary krb5.conf is now used in this test that forces to deactivate DNS lookups and also to load /etc/krb5.conf. A missing krb5.conf is now detected properly as the kinit call fails now properly.
ipaclient_test_keytab is now properly returning the state of usable or not usable krb5.conf in krb5_conf_ok. This fixes the handling of this case later on in the role.
> ipaclient: Fix allow_repair with removed krb5.conf and DNS lookup

- galaxy.yml
- tests/config/test_config.yml
- tests/config/test_config_sid.yml
- tests/env_freeipa_facts.yml
- tests/group/test_group.yml
- tests/group/test_group_external_members.yml
- tests/group/test_group_external_nonposix.yml
- tests/group/test_group_idoverrideuser.yml
- tests/group/test_group_membermanager.yml
- tests/hostgroup/test_hostgroup_membermanager.yml
- tests/hostgroup/test_hostgroup_rename.yml
- tests/idrange/test_idrange.yml
- tests/role/env_facts.yml
- tests/server/test_server.yml
- tests/service/test_service.yml
- tests/servicedelegationrule/test_servicedelegationrule_hostprincipal.yml
- tests/servicedelegationtarget/test_servicedelegationtarget_hostprincipal.yml
- tests/trust/test_trust.yml
- tests/user/test_users_absent.yml
- tests/user/test_users_present.yml
- tests/user/test_users_present_slice.yml
- tests/vault/test_vault_change_type.yml
Recent PR checks are failing due to `ansible-lint` being more strict and complaining about errors it didn't before.
With this PR, the errors are fixed and pre-commit is updated to match the upstream tool versions, so verification can be done, also, on commit time, before opening a PR.
> By merging this changes, the PRs which are showing `ansible-lint` failures need to be rebased to `upstream/master`.
> Fix ansible-lint on tests

- utils/ansible-freeipa.spec.in
According to [1] all Fedora packages need to be updated to use a SPDX expression. This patch updates the ansible-freeipa spec template to comply with this change.
[1] https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_1
> Migrated to SPDX license.

- roles/ipaclient/README.md
- roles/ipaclient/defaults/main.yml
- roles/ipaclient/library/ipaclient_setup_nss.py
- roles/ipaclient/tasks/install.yml
- roles/ipareplica/README.md
- roles/ipaserver/README.md
Create support for `subid` option for `ipaclient_setup_nss` role.
RFE #919
Signed-off-by: Denis Karpelevich <dkarpele@redhat.com>
> Add subid option to select the sssd profile with-subid.

- README-user.md
- plugins/modules/ipauser.py
- tests/user/test_user_random.yml
The way how randompasswords are returned by the ipauser module depends so far on the number of users that are handled by the module.
This is unexpected if for example a json file is provided with the users parameter. As it might be unknown how many users are in the json file, this behaviour is unexpected. The return should not vary in this case.
This chamge makes the return simply depend on the use of the users paramater. As soon as this parameter is used, the return will always be:
"user": { "\<the user \>": { "randompassword": "\<the user random password\>" } }
In the simply case with one user it will be still
"user": { "randompassword": "\<the user random password\>" }
Fixes: #1052 (ipauser should consitently return randompasswords when
used with users)
> ipauser: Make return value depending on users parameter

- README-host.md
- plugins/modules/ipahost.py
- tests/host/test_host_random.yml
The way how randompasswords are returned by the ipahost module depends so far on the number of hosts that are handled by the module.
This is unexpected if for example a json file is provided with the hosts parameter. As it might be unknown how many hosts are in the json file, this behaviour is unexpected. The return should not vary in this case.
This chamge makes the return simply depend on the use of the hosts paramater. As soon as this parameter is used, the return will always be:
"host": { "\<the host\>": { "randompassword": "\<the host random password\>" } }
In the simply case with one host it will be still
"host": { "randompassword": "\<the host random password\>" }
This change for ipahost is related to the ipauser PR #1053.
> ipahost: Make return value depending on hosts parameter

- roles/ipareplica/tasks/install.yml
Some ipareplica role had a few module calls with parameters set like 'some_argument | default(omit)' that were not actually available in such modules. If a user provided 'some_argument', the paramater would then be passed to the module and ipareplica deployment would fail.
By removing the parameters from the 'install' task, ipareplica deployment works even if the variables are set by the user.
Fixes #1061
> ipareplica role: Remove usage of undefined parameters.

- roles/ipareplica/README.md
- roles/ipareplica/tasks/uninstall.yml
- roles/ipaserver/README.md
- roles/ipaserver/defaults/main.yml
- roles/ipaserver/library/ipaserver_get_connected_server.py
- roles/ipaserver/tasks/uninstall.yml
New variables have been added to ipareplica and ipaserver role to enable the removal from the domein with the undeployment.
`ipaserver_remove_from_domain`
This enables the removal of the server from the domain additionally to the undeployment.
`ipaserver_remove_on_server`
The value defines the server/replica in the domain that will to be used to remove the server/replica from the domain if
`ipaserver_ignore_topology_disconnect` and `ipaserver_remove_from_domain` are enabled. Without the need to enable
`ipaserver_ignore_topology_disconnect`, the value will be automatically detected using the replication agreements of the server/replica.
For the replica role it is possible to use the server variables, but also the replica versions: `ipareplica_remove_from_domain` and …
> ipareplica/server: Enable removal from domain with undeployment

- roles/ipaclient/library/ipaclient_fix_ca.py
- roles/ipaclient/library/ipaclient_setup_nss.py
- roles/ipaclient/tasks/install.yml
With the fix to defer creating the final krb5.conf on clients a bug has
been introduced with ipaclient_setup_nss: The krb_name parameter that
points to the temporary krb5 configuration was not added to the module.
With a properly configured DNS (like for example IPA DNS) the krb TXT
records have been present in the DNS configuration. These have been used
automatically as a fallback and broke server affinity for the client.
Without the TXT records creating the IPA NSS database failed with
"Cannot find KDC for realm ..".
The krb_name parameter has been added to ipaclient_setup_nss and is also
properly set in tasks/install.yml.
With the fix to defer creating the final krb5.conf on clients a bug has
been introduced with ipaclient_fix_ca: The krb_name parameter that
points to the temporary …
> ipaclient: Defer krb5 configuration fix

- plugins/modules/ipahost.py
- plugins/modules/ipauser.py
> Update `EXAMPLE` sections for multiuser and multihost handling.

- roles/ipaserver/README.md
- roles/ipaserver/defaults/main.yml
- roles/ipaserver/library/ipaserver_test.py
- roles/ipaserver/module_utils/ansible_ipa_server.py
- roles/ipaserver/tasks/install.yml
Since FreeIPA version 4.10 it is possible to deploy servers that use Random Serial Number v3 support for certificates.
This patch exposes the 'random_serial_numbers' parameter, as 'ipaserver_random_serial_numbers', allowing a user to have random serial numbers enabled for the domain.
The use of random serial numbers is allowed on new installations only.
> roles/ipaserver: Allow deployments with random serial numbers

- plugins/modules/ipagroup.py
- tests/group/test_group_external_group_members_no_trust.yml
Due to an API misbehaviour in FreeIPA, ipaexternalmembers need to be
treated differently than other group members parameters. Even an empty
array triggers all tests for external members, including the check for
installed dcerpc bindings.
Therefore ipagroup module has been changed to not set ipaexternalmember
to an empty list if there are no external members to be added or
removed.
> ipagroup: Fix ensuring external group group members (without trust-ad)

- roles/ipaserver/defaults/main.yml
ipaserver_random_serial_numbers was enabled by default in roles/ipaserver/defaults/main.yml. This should not be the default and also resulted in issues in all IPA versions that do not support RSN.
The parameter now defaults to false.
> ipaserver: Do not enable random serial numbers by default

- utils/build-galaxy-release.sh
- utils/create_action_group.py
- utils/facts.py
- utils/galaxyfy.py
**New utils/facts.py: Provide facts about the repo like role and module lists**
The list of modules and roles is needed in several scripts now,
therefore it makes sense to have one place for this.
Here are the current variables:
BASE_DIR:           Base directory of the repo
ROLES:              List of roles in the roles folder
MANAGEMENT_MODULES: List of management modules in the plugins/modules
folder
ROLES_MODULES:      List of modules in the roles/*/library folders
ALL_MODULES:        List of all modules, the management and the roles
modules
All lists are sorted.
**utils/galaxyfy.py: Handle module_defaults, match roles and modules**
The section module_defaults was not handled by utils/galaxyfy.py, also
there was no verification that only roles and modules provided by
ansible-freeipa …
> Create action group in collection for use with module_defaults

- utils/new_module
- utils/templates/README-module+member.md.in
- utils/templates/README-module.md.in
- utils/templates/ipamodule.py.in
- utils/templates/test_module+member.yml.in
- utils/templates/test_module.yml.in
- utils/templates/test_module_client_context.yml.in
**utils/new_module: Fix github_user test**
new_module was always failing with "github_user is not valid". The wrong
variable was checked: $githubuser instead of $github_user.
**utils/new_module: Ensure correct number of parameters for new_module**
When testing the number parameters for new_module, the
`github_user` was not being taken into account.
**utils/templates/ipamodule.py.in: Add missing bracket**
The parameter argument spec of name was missing the closing bracket. The
bracket has been added.
**utils/templates/{README\*.md.in,test_module\*.yml.in}: Use true and false**
The values "yes" and "no" will not be valid in the future for bool
parameters. Therefore "yes" and "no" have been replaced by "true" and
"false".
**utils/templates/test_module\*.yml.in: Better docs for become and …
> Fixes and enhancements for utils/new_module and templates

- tests/README.md
- tests/azure/templates/build_container.yml
- tests/azure/templates/galaxy_pytest_script.yml
- tests/azure/templates/galaxy_script.yml
- tests/azure/templates/playbook_fast.yml
- tests/azure/templates/playbook_tests.yml
- tests/azure/templates/pytest_tests.yml
The docker driver is not part of molecule 5.0.0 anymore. molecule-plugins need to be installed to get the driver.
> tests/azure: Install molecule-plguins to get docker driver

- tests/azure/templates/build_container.yml
- tests/azure/templates/galaxy_pytest_script.yml
- tests/azure/templates/galaxy_script.yml
- tests/azure/templates/playbook_fast.yml
- tests/azure/templates/playbook_tests.yml
- tests/azure/templates/pytest_tests.yml
Due to https://github.com/docker/docker-py/issues/3113 requests need to be pinned below 2.29 as a temporary solution.
> Pin requests to < 2.29 temporarily

- .ansible-lint
Latest ansible-lint version (6.16.1) started to raise an error when variable names from within roles are not prefixed with  the role name. Error: var-naming[no-role-prefix].
As Ansible sanity check does not enforce this, it will be disabled, for now on ansible-freeipa's upstream CI.
A future effort to reduce the checks that are not being evaluated should be done as preparation for future Ansible Galaxy and Automation Hub requirements.
> upstream CI: Disable ansible-lint var-naming check

- .gitignore
Ignore vim .swp files and files generated by creating ansible-freeipa collection (freeipa-*.tar.gz and importer_result.json), when checking repository status.
> Make Git ignore temporary and output files.

- README-cert.md
- README.md
- playbooks/cert/cert-hold.yml
- playbooks/cert/cert-release.yml
- playbooks/cert/cert-request-host.yml
- playbooks/cert/cert-request-service.yml
- playbooks/cert/cert-request-user.yml
- playbooks/cert/cert-retrieve.yml
- playbooks/cert/cert-revoke.yml
- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipacert.py
- setup.cfg
- tests/cert/test_cert_client_context.yml
- tests/cert/test_cert_host.yml
- tests/cert/test_cert_service.yml
- tests/cert/test_cert_user.yml
I'm working on a module that is able to request & revoke certificates from a FreeIPA CA.
I'm currently refactoring the working module I hacked together in order to make it suitable for inclusion in `ansible-freeipa`. So far it looks like:
```YAML
- ipacert:
state: requested
csr: |
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE------
principal: HTTP/www.example.com
register: cert
- copy:
content: '{{ cert.chain | join }}'
path: /etc/pki/tls/certs/httpd.crt
```
The module code isn't ready yet, but I wonder if I could trouble you for a review of the documentation/examples, so I can finalize the parameter names, etc before implementing rest of the module.
> ipacert module

- roles/ipareplica/library/ipareplica_test.py
- roles/ipaserver/library/ipaserver_test.py
If server FQDN matches the domain name, the installation will succeed, but DNS records will not work. If 'setup_dns: true' is used, there will be no A record for the host, only a NS record, and the PTR record will point to the domain name.
Based on: https://github.com/freeipa/freeipa/pull/6853
Related to: https://pagure.io/freeipa/issue/9003
> Don't allow the FQDN to match the domain on server installs

- plugins/modules/ipapwpolicy.py
Use a simpler and faster 'any()' test instead of creating two lists and checking if resulting list is empty.
> ipapwpolicy: simplified and faster attribute verification

- tests/pwpolicy/test_pwpolicy.yml
The maxsequence test was testing maxrepeat. Therefore the typo reported with https://github.com/freeipa/ansible-freeipa/pull/1081 was never seen.
The test has been fixed.
> pwpolicy test: Fix maxsequence test

- roles/ipaserver/README.md
The setting was in singular in the example while being documented in plural form.
> Singular to plural on random serial numbers setting

- README-user.md
- plugins/modules/ipauser.py
- tests/user/test_user.yml
This patch adds a new parameter to ipauser, 'gecos', which can be used to set the 'gecos' field of an IPA user. The default behavior of automatically set the GECOS field to "<first> <last>" is not modified, it is only possible to change the field to a custom value.
No validation on the value provided is done, as it is with FreeIPA.
> ipauser: Add support to modify GECOS field.

- .github/workflows/ansible-test.yml
- tests/sanity/sanity.sh
'virtualenv' is an external dependency with the same purpose of Python's 'venv' module. This patch removes the external dependency in favor of the readily available package.
> Remove dependency on 'virtualenv'

- .github/workflows/docs.yml
- .github/workflows/lint.yml
- tests/azure/azure-pipelines.yml
- tests/azure/nightly.yml
- tests/azure/pr-pipeline.yml
- utils/run-tests.sh
ansible-core 2.15 has been released on May 15th, 2023, and version 2.12 has reached EOL on May 22nd, 2023.
This patch updates the ansible-core versions used on upstream CI tests to reflect Ansible's new releases.
> upstream CI: Update ansible-core version

- README-pwpolicy.md
- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipapwpolicy.py
- tests/pwpolicy/test_pwpolicy_invalid_data_type.yml
As raise by the discussion on PR #1066, the handling of boolean values that can be cleared by using an empty string should include the same parsing method as the one used by Ansible.
This patch exposes 'boolean()' through ansible_freeipa's `module_utils` and makes use of it to validate `ipapwpolicy` parameters `usercheck` and `dictcheck`.
Test were updated to reflect error message changes.
Also, documentation for `ipapwpolicy` was updated to reflect the fields (`int` or `bool`) that accept an empty string to clear the setting.
> Fix handling of ipapwpolicy attributes usercheck and dictcheck

- README-host.md
- README-server.md
- plugins/modules/ipahost.py
- plugins/modules/ipaserver.py
Host location and server location have very different meanings in IPA. ipahost uses 'location' as an optional hint to where the host may be physically located, ipaserever uses location to identify which DNS location the server is part of.
This change updates documentation to make attribute description more clear. Surrounding text have been changed to match text style as used in other plugins.
This patch is related to: https://github.com/freeipa/freeipa/pull/6840
> doc: Differentiate location meaning between host and server

- utils/run-tests.sh
When runing tests using 'utils/run-tests.sh' from inside an existing Python virtual environment the Ansible collections are not installed due to the order of execution of the script. On a machine that does not have the 'containers.*' collection the test fails as there is no container connector available.
This patch moves the section that installs Ansible collections to run after the virtual environment is configured, and then install the collections (usually, only 'containers.podman'), allowing the tests to be executed.
> utils/run-tests.sh: Install Ansible collections on virtual environment

- README-automountmap.md
- playbooks/automount/automount-map-indirect-map.yml
- plugins/modules/ipaautomountmap.py
- tests/automount/test_automountmap_indirect.yml
Indirect maps were not supported by ansible-freeipa ipaautomountmap. This patch adds support for adding indirect automount maps using the "parent" and "mount" parameters, if the map do not yet exist. An existing map cannot be modified.
The "parent" parameter must match an existing automount map, and the "mount" parameter is required if "parent" is used.
A new test playbook was added to test the feature:
tests/automount/test_automountmap_indirect.yml
Related:
* RHBZ [#2050176](https://bugzilla.redhat.com/show_bug.cgi?id=2050176)
* RHBZ [#2050158](https://bugzilla.redhat.com/show_bug.cgi?id=2050158)
Fixes #804
> ipaautomountmap: add support for indirect maps

- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipaconfig.py
- plugins/modules/ipahost.py
- plugins/modules/ipaservice.py
- plugins/modules/ipauser.py
**ansible_freeipa_module: New ipa_command_invalid_param_choices method**
New IPAAnsibleModule.ipa_command_invalid_param_choices method to return
invalid parameter choices for an IPA command.
This is needed to verify for example if userauthtype and authind are
supporting the idp value.
**ipaconfig: Add choices pkinit, hardened and idp to user_auth_type**
The parameter user_auth_type has been updated in FreeIPA. The choices
pkinit, hardened and idp have been missing and are now added.
An additional check was added to verify that the values of the
user_auth_type list are valid for the used IPA version.
**ipahost: Add choice idp to auth_ind**
The parameter auth_ind has been updated in FreeIPA. The choice
idp have been missing and is now added.
An additional check was added to verify that the …
> Update authtypes authind

- roles/ipabackup/README.md
- roles/ipareplica/README.md
- roles/ipaserver/README.md
Ubuntu does not have a FreeIPA server package since version 20.04. As versions 16.04 (Xenial Xerus) and 18.04 (Bionic Beaver) will be supported by Canonical until 2026 and 2028, repectively, we should keep existing support for both versions in the ipaserver and ipabackup roles until them.
This patch changes documentation to reflect that only those versions are supported.
> ipaserver: Update README with detailed Ubuntu support

- README-config.md
- README-host.md
- README-service.md
- README-user.md
**README-config.md: Add choices pkinit, hardened and idp to user_auth_type**
The parameter user_auth_type has been updated in FreeIPA. The choices
pkinit, hardened and idp have been missing and are now added.
**README-host.md: Add choice idp to auth_ind**
The parameter auth_ind has been updated in FreeIPA. The choice
idp have been missing and is now added.
**README-service.md: Add choice idp to auth_ind**
The parameter auth_ind has been updated in FreeIPA. The choice
idp have been missing and is now added.
**README-user.md: Add choices pkinit, hardened and idp to user_auth_type**
The parameter user_auth_type has been updated in FreeIPA. The choices
pkinit, hardened and idp have been missing and are now added.
> Update authtypes authind readmes

- README-user.md
- playbooks/user/add-user-external-idp.yml
- plugins/modules/ipauser.py
- tests/user/test_user_idp_attrs.yml
Add support for 'idp' and 'idp_user_id' to ipauser plugin.
FreeIPA 4.10.0 is required for both attributes.
> ipauser: Support for External IdP attributes.

- tests/azure/templates/galaxy_pytest_script.yml
- tests/azure/templates/galaxy_script.yml
- tests/azure/templates/playbook_fast.yml
- tests/azure/templates/playbook_tests.yml
- tests/azure/templates/pytest_tests.yml
Some test failures requires more information than just the playbook simple output. By increasing verbosity, the used parameters and the failed line will be visible in the test error report, making it easier to identify, reproduce and fix the issue.
> ci: Increase verbosity for Ansible playbook runs

- README-idview.md
- README.md
- playbooks/idview/idview-absent.yml
- playbooks/idview/idview-host-applied.yml
- playbooks/idview/idview-host-unapplied.yml
- playbooks/idview/idview-present.yml
- plugins/modules/ipaidview.py
- tests/idview/test_idview.yml
- tests/idview/test_idview_client_context.yml
There is a new idview management module placed in the plugins folder:
plugins/modules/ipaidview.py
The idview module allows to ensure presence and absence of idviews and idview host members.
README-idview.md
playbooks/idview/idview-absent.yml
playbooks/idview/idview-host-applied.yml
playbooks/idview/idview-host-unapplied.yml
playbooks/idview/idview-present.yml
New tests for the module can be found at:
tests/idview/test_idview.yml
tests/idview/test_idview_client_context.yml
> New idview management module.

- README-cert.md
The revocation example playbook on README was wrong as it didn't have a 'reason' set, and the parameter must be used with 'state: revoked'.
This patch fixes the example and adds a new example using a reason mnemonic instead of a reason number.
Fixes #1132
> ipacert: Fix revocation example playbook on README

- roles/ipabackup/README.md
- roles/ipaclient/README.md
- roles/ipareplica/README.md
- roles/ipaserver/README.md
- roles/ipasmartcard_client/README.md
- roles/ipasmartcard_server/README.md
Updated all roles README files to add supported distros, as CentOS Stream is supported (both 8 and 9) and also Debian clients.
> Updated supported distros

- utils/ansible-freeipa.spec.in
Current spec file template was missing certificate and netgroup modules.
> spec file: Updated list of modules

- utils/templates/ipamodule+member.py.in
- utils/templates/ipamodule.py.in
- utils/templates/test_module_client_context.yml.in
**utils/templates/test_module_client_context.yml.in: Fix FQDN issue**
Fixes left over FQDN issue for include_tasks.
**utils/templates/ipamodule\*.py.in: Fix superfluous type in argument spec**
The type was given twice for state and action argument specs. This has
been fixed.
> new_module template fixes

- plugins/module_utils/ansible_freeipa_module.py
- roles/ipaclient/library/ipaclient_fix_ca.py
- roles/ipaclient/library/ipaclient_get_otp.py
- roles/ipaclient/library/ipaclient_join.py
- roles/ipareplica/library/ipareplica_prepare.py
- roles/ipaserver/library/ipaserver_get_connected_server.py
The use of del os.environ assumes that the environment variable exists. If the variable does not exist, this call will result in a traceback. The solution is to use os.environ.pop(VARIABLE, None) instead.
This is the ansible-freeipa fix for https://pagure.io/freeipa/issue/9446 (Nightly test failure for replica installation with --setup-ca)
> Do not use "del os.environ" as the variable might not exist

- README-idoverrideuser.md
- README.md
- playbooks/idoverrideuser/idoverrideuser-absent.yml
- playbooks/idoverrideuser/idoverrideuser-certificate-absent.yml
- playbooks/idoverrideuser/idoverrideuser-certificate-present.yml
- playbooks/idoverrideuser/idoverrideuser-present.yml
- plugins/modules/ipaidoverrideuser.py
- tests/idoverrideuser/test_idoverrideuser.yml
- tests/idoverrideuser/test_idoverrideuser_client_context.yml
- utils/ansible-freeipa.spec.in
There is a new idoverrideuser management module placed in the plugins folder:
plugins/modules/ipaidoverrideuser.py
The idoverrideuser module allows to ensure presence and absence of idoverrides for users and certificate members.
README-idoverrideuser.md
playbooks/idoverrideuser/idoverrideuser-absent.yml
playbooks/idoverrideuser/idoverrideuser-certificate-absent.yml
playbooks/idoverrideuser/idoverrideuser-certificate-present.yml
playbooks/idoverrideuser/idoverrideuser-present.yml
New tests for the module can be found at:
tests/idoverrideuser/test_idoverrideuser.yml
tests/idoverrideuser/test_idoverrideuser_client_context.yml
> New idoverrideuser management module.

- README-idoverridegroup.md
- README.md
- playbooks/idoverridegroup/idoverridegroup-absent.yml
- playbooks/idoverridegroup/idoverridegroup-present.yml
- plugins/modules/ipaidoverridegroup.py
- tests/idoverridegroup/test_idoverridegroup.yml
- tests/idoverridegroup/test_idoverridegroup_client_context.yml
There is a new idoverridegroup management module placed in the plugins folder:
plugins/modules/ipaidoverridegroup.py
The idoverridegroup module allows to ensure presence and absence of idoverrides for groups.
README-idoverridegroup.md
playbooks/idoverridegroup/idoverridegroup-absent.yml
playbooks/idoverridegroup/idoverridegroup-present.yml
New tests for the module can be found at:
tests/idoverridegroup/test_idoverridegroup.yml
tests/idoverridegroup/test_idoverridegroup_client_context.yml
> New idoverridegroup management module.

- tests/azure/azure-pipelines.yml
- tests/azure/nightly.yml
Currently, ansible-freeipa's minimum supported ansible-core version is version 2.13, as it is the current minimum supported upstream ansible-core version. This patch changes upstream CI to run PR checks against this ansible-core version.
Also, it was announced that Ansible 2.9 will have some support for a year, or so, and this PR adds nightly testing against this version of Ansible, to check weather ansible-freeipa can still be used with this version or not.
> Ensure CI runs against the oldest supported Ansible versions.

- tests/azure/nightly.yml
Most of our usptream CI test imagens do not handle Ansible 2.9 so, this cange is being reverted.
This reverts commit 34654d1090c923044cbaa90f497c37cbe26a298e.
> Revert "upstream ci: Run nightly tests against Ansible 2.9"

- README-idp.md
- README.md
- playbooks/idp/idp-absent.yml
- playbooks/idp/idp-present.yml
- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipaidp.py
- tests/idp/test_idp.yml
- tests/idp/test_idp_client_context.yml
- utils/ansible-freeipa.spec.in
There is a new idp management module placed in the plugins folder:
plugins/modules/ipaidp.py
The idp module allows to ensure presence or absence of external Identity Providers.
README-idp.md
New idp example playbooks:
playbooks/idp/idp-present.yml
playbooks/idp/idp-absent.yml
tests/idp/test_idp.yml
tests/idp/test_idp_client_context.yml
> New idp management module

- utils/ansible-freeipa.spec.in
The idoverridegroup management reference has been added to the description.
> utils/ansible-freeipa.spec.in: Add ref for idoverridegroup management

- tests/azure/templates/fast_tests.yml
- tests/azure/templates/galaxy_tests.yml
- tests/azure/templates/group_tests.yml
After Azure updated available Python to version 3.12, test image preparation started to fail.
The fix is to pin python version to the latest is the 3.11 series until we can run tests with Python 3.12. 
Note that only the first commit should be applied ([55b8729](https://github.com/freeipa/ansible-freeipa/pull/1157/commits/55b8729c5270a4a6ab4ca6668b1e2e7d7b6afa10)). Other commits come from PR #1148 and are present only to fix test selection.
> upstream CI: Pin Python version to 3.11 

- .github/workflows/lint.yml
The release version 6.21.0 of ansible-lint introduced a bug that breaks the reporting of 'warning' messages. [1]
This patch pins ansible-lint version to the latest one in the 6.20 series, so that it can still be used to check pull requests.
[1]: https://github.com/ansible/ansible-lint/issues/3853
> upstream CI: Pin ansible-lint version to 6.20 series

- tests/azure/templates/fast_tests.yml
- tests/azure/templates/galaxy_script.yml
- tests/azure/templates/playbook_fast.yml
- tests/azure/templates/playbook_tests.yml
- utils/get_test_modules.py
This PR fixes issues related to test selection in upstream CI:
* `CheckPR`:
* Fixed test selection script.
* Use a single job to run the tests
* Other pipelines:
* Use the same random seed to randomly choose the tests to run on each group, ensuring all tests are executed.
> upstream CI: Fix test selection for CheckPR pipeline.

- plugins/modules/ipahbacrule.py
- tests/hbacrule/test_hbacrule_member_case_insensitive.yml
hbacsvcgroup names are converted to lower case while creation with hbacsvcgroup_add.
The hbacsvcgroup for sudo is builtin with the name "Sudo" though. This breaks the lower case comparison. Therefore all memberservice_hbacsvcgroup items are converted to lower case if "Sudo" is in the list.
> hbacrule: Fix use of builtin sudo hbacsvcgroup

- plugins/modules/ipahbacsvcgroup.py
The result_handler is not needed anymore as the idempotency issues with members have been fixed already for this module.
Related: #685 hbacsvcgroup: Fix member management idempotence issues.
> hbacsvcgroup: Remove obsolete result_handler

- plugins/modules/ipaidview.py
- tests/idview/test_idview.yml
The task to apply an unknown (invalid) host to an idview was not failing as expected and only reported no change.
A new host verification step has been added to fail before trying to apply invalid hosts. unapplying an invalid host is not failing as the invalid host is indeed not applied.
> ipaidview: Fail to apply unknown (invalid) hosts

- plugins/modules/ipaidoverridegroup.py
- plugins/modules/ipaidoverrideuser.py
- tests/idoverridegroup/test_idoverridegroup.yml
- tests/idoverrideuser/test_idoverrideuser.yml
All tasks for idoverrideuser and idoverridegroup with state absent failed with "'continue' is required" when delete_continue was not set.
This happended as delete_continue was internally None and continue: None was provided to the API.
The fix is simply to use '"continue": delete_continue or False' so that continue is set to False in this case.
> idoverride{user,group}: Fix delete_continue with state absent

- tests/host/test_host.yml
When testing ipahost through the test playbooks, if there are previous DNS A/AAAA records, the test fails due to a false positive idempotence issue.
This patch ensures that all DNS records for the test hosts are absent before test execution.
This issue could be seen in the 2023-11-06 Azure Nightly pipeline execution.
> ipahost: Remove dangling dns records during test setup

- .github/workflows/lint.yml
- .pre-commit-config.yaml
ansible-lint 6.21+ and pylint 3.0+ will be required for Ansible collections to be approved on Ansible Galaxy.
This patch updates pre-commit and upstream linters to use the required versions.
> Update ansible-lint and pylint versions

- tests/azure/build-containers.yml
In the current build container pipeline, all steps are serialized in a single job, and if one of the jobs fail to build, due to broken dependent image, or some Azure glitch, like slow connection, the only way to rebuild the failed container is to rebuild all containers.
By building containers in parallel jobs, if a container fails to build it is possible to restart only the failed job.
The patch also updates the VM version used to 'ubuntu-latest'.
> upstream CI: Build containers in parallel jobs

- tests/pwpolicy/test_pwpolicy.yml
The reset of the minlength parameter failed with an internal error so far. This has been fixed in IPA and therefore requires to fix the test in ansible-freeipa also.
Related: https://pagure.io/freeipa/issue/9297
> test_pwpolicy: minlength parameter can be reset with empty string now

- tests/host/test_host_random.yml
With ansible-core 2.14.12 using jinja2 templating in conditional statements with ansible_facts['fqdn'] is marked as unsafe and results in a failure.
The issues with using jinja2 templating in conditional statements for asserts have been solved and a new server_fqdn fact has been added for ansible_facts['fqdn'].
> test_host_random: No jinja2 templating in conditional statements

- .github/workflows/lint.yml
- requirements-dev.txt
By the first quarter of 2024, all collections must pass ansible-lint tests run with version 6.22.x. This PR ensure that all ansible-freeipa tests depending on ansible-lint use a valid version of it.
> Bump minimum ansible-lint version to 6.22

- tests/azure/templates/playbook_fast.yml
After the change for a single job to run PR tests, and if there is any
change to ansible_module_utils, all the playbook tests are executed,
and the result is a failure due to timeout.
This PR increases the timeout so that a PR with changes to
ansible_module_utils can have the tests executed.
> upstream ci: Increase timeout for PR tests

- roles/ipareplica/tasks/install.yml
Altough most of ansible-freeipa documentation and playbooks use 'ipaserver' as the group for the first server deployed for a realm, the ipareplica role only supported the use of groups["ipaservers"] as an alternative to set ipareplica_servers.
Also supporting groups.ipaserver, as already supported by the ipaclient role, make ansible-freeipa playbooks more consistent and current documentation and examples easier to follow when deploying a cluster with a server and a replica.
> ipareplica: Support inventory groups.ipaserver

- plugins/modules/ipauser.py
- tests/user/test_user.yml
If a playbook to ensure the existence of a user contains 'random:false' and 'update_password: always' is executed twice, the second execution will raise an exception due to "No modifications to perform", as there is actually nothing to modify.
The fix for the issue is to remove 'random' if it is not set to true, as setting it to 'false' would have no effect on the user object.
Related: https://issues.redhat.com/browse/RHEL-4934
> ipauser: Do not try to modify user when not changing password

- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipaconfig.py
- plugins/modules/ipahost.py
- plugins/modules/ipaidoverridegroup.py
- plugins/modules/ipaidoverrideuser.py
- plugins/modules/ipapwpolicy.py
- plugins/modules/ipaservice.py
- plugins/modules/ipauser.py
Some parameters, in modules, have a specific data type, but allow the use of an empty string to clear the parameter.
By providing a method to retrieve the parameter with the correct data type, or optionally an empty string, allows for consistency of parameter handling between different modules.
Currently, `ipapwpolicy` and `ipaidoverrideuser` requires such method, and both were modified to use the module_utils implementation.
> Handle data type or empty string in module_utils

- README-dnszone.md
- plugins/modules/ipadnszone.py
- tests/dnszone/test_dnszone.yml
IPA DNS Zones management can be delegated by adding a "Manage DNS zone" permission. The CLI commands that manage these permissions are dnszone-add-permission and dnszone-remove-permission.
The ansible-freeipa module ipadnszone did not have this capability, and it now support dnszone per-zone management delegation by setting the module parameter 'permission'. If set to 'true' the permission will be assigned to the zone, if set to false the permission will be removed.
> ipadnszone: Add support for per-zone privilege delegation

- README-user.md
- plugins/modules/ipauser.py
- tests/user/test_user.yml
- tests/user/test_users.yml
FreeIPA suports renaming user objects with the CLI parameter "rename", and this parameter was missing in ansible-freeipa ipauser module.
This patch adds support for a new state 'renamed' and the 'rename' parameter.
Tests were updated to cope with the changes.
Related to RHBZ#2234379, RHBZ#2234380
Fixes #1103
> ipauser: Add support for renaming users

- README-group.md
- plugins/modules/ipagroup.py
- tests/group/test_group.yml
- tests/group/test_groups.yml
FreeIPA suports renaming groupobjects with the CLI parameter "rename",
and this parameter was missing in ansible-freeipa ipagroup module.
This patch adds support for a new state 'renamed' and the 'rename'
parameter.
Tests were updated to cope with the changes.
Fixes #1103
> ipagroup: Add support for renaming groups

- README-sudorule.md
- playbooks/sudorule/ensure-sudorule-runasuser-group-is-absent.yml
- playbooks/sudorule/ensure-sudorule-runasuser-group-is-present.yml
- plugins/modules/ipasudorule.py
- tests/sudorule/test_sudorule.yml
On IPA CLI sudorule-add/del-runasuser accept 'group' as a parameter,
and this option was missing in ansible-freeipa ipasudorule module.
This patch adds a new parameter 'runasuser_group' to allow setting
Groups of RunAs Users, as allowed by CLI and WebUI.
Fixes: #898
> ipasudorule: Allow setting groups for runasuser.

- roles/ipaclient/library/ipaclient_setup_nss.py
- roles/ipaclient/library/ipaclient_test.py
- roles/ipaclient/module_utils/ansible_ipa_client.py
- roles/ipaclient/tasks/install.yml
This is "ipa-client-install: enable SELinux for SSSD" https://github.com/freeipa/freeipa/pull/6978 for ansible-freeipa:
For passkeys (FIDO2) support, SSSD uses libfido2 library which needs access to USB devices. Add SELinux booleans handling to ipa-client-install so that correct SELinux booleans can be enabled and disabled during install and uninstall. Ignore and record a warning when SELinux policy does not support the boolean.
Fixes: https://pagure.io/freeipa/issue/9434
> ipaclient: Enable SELinux for SSSD

- roles/ipaserver/library/ipaserver_set_ds_password.py
As FreeIPA now requires MS-PAC to be set in ipaKrbAuthzData to trigger PAC generation, there's a timing issue that causes API malfunction which is long enough to cause the client part insallation to fail.
By restarting KDC after DS password is set, we force cached values to be refreshed, allowing the API to work correctly.
Fixes #1200
> ipaserver: Fix deployment after Bronze-bit fix

- plugins/modules/ipahbacrule.py
- tests/hbacrule/test_hbacrule_member_case_insensitive.yml
FreeIPA provides a default hbacsvcgroup named "Sudo", with capital 'S', that is different from every other hbacsvcgroup, which are all represented by lower case letters.
As data from IPA API was not modified, this causes an idempotence error when using different capitalization with the 'hbacsvcgroup' parameter.
This patch fixes the issue by using the CaseInsensitive comparator to create the hbacsvcgroup list.
Tests were update to make sure a regression is not included in the future.
Fixes #834
> ipahbacrule: Fix handling of hbacsvcgroup in members

- plugins/modules/ipahostgroup.py
- tests/hostgroup/test_hostgroup_case_insensitive.yml
- tests/hostgroup/test_hostgroup_membermanager_case_insensitive.yml
ipahostgroup parameters 'host', 'hostgroup', 'membermanager_user' and 'membermanager_group' must be compared in a case insensitive manner and stored as lower case strings.
This patch fixes the comparison and storage of this parameters, and change the handling of members to use the same structure as in newer modules.
Two new tests files were added:
tests/hostgroup/test_hostgroup_case_insensitive.yml
tests/hostgroup/test_hostgroup_membermanager_case_insensitive.yml
Fixes #1196
> ipahostgroup: Fix idempotence issues due to capitalization

- tests/azure/templates/variables.yaml
**[TEMP] Temporarily modify ipaconfig to verify test deactivation**
**config:` Disable config tests due to pac type requirement MS-PAC**
The config tests are currently setting the pac type to empty or without
MS-PAC type. This results in failed authorization for IPA API.
An issue has been opened for FreeIPA to address this:
https://pagure.io/freeipa/issue/9527
> Disable config tests for pac type without ms pac

- plugins/modules/ipagroup.py
- tests/group/test_group_case_insensitive.yml
Some attributes for ipagroup objects are stored using lower case letters and should be converted upon retrieving parameter data.
This patch adds the missing conversion and provides a new test playbook:
tests/group/test_group_case_insensitive.yml
Fixes #1197
> ipagroup: Fix idempotence issues due to capitalization

- plugins/modules/ipadelegation.py
- tests/delegation/test_delegation_member_case_insensitive.yml
This patch force processing of permission, attribute and group
attributes in lower case, to match behavior of IPA CLI, transforming
all of them into lowercase characters.
The new behavior fixes idempotence issues when mixing different
capitalization in different tasks for the same attribute.
A new test playbook is avaiable at:
tests/delegation/test_delegation_member_case_insensitive.yml
Fix #759
> ipadelegation: Fix idempotence issues due to capitalization.

- README-dnszone.md
There was a space between the code block marker and the highlight hint in a playbook example.
> README-dnszone: Fix yaml code block declaration.

- roles/ipaserver/library/ipaserver_test.py
If ipaserver_domain is not given, the domain name is generated from the host fqdn.
This generated value was so far not returned, but the empty given value instead.
> ipaserver_test: Return generated domain_name

- utils/build-galaxy-release.sh
The offline default value was 0, which resulted in 0 for ${offline/1/--offline}.
This broke the ansible-galaxy collection install call.
> utils/build-galaxy-release.sh: Fix offline default value

- plugins/module_utils/ansible_freeipa_module.py
- roles/ipaclient/library/ipaclient_get_otp.py
- roles/ipaclient/module_utils/ansible_ipa_client.py
- roles/ipareplica/module_utils/ansible_ipa_replica.py
- roles/ipaserver/library/ipaserver_get_connected_server.py
FreeIPA PR https://github.com/freeipa/freeipa/pull/7286 moved ipalib.install.kinit to ipalib.
It is first tried to import kinit_keytab and kinit_password from ipalib.kinit, then ipalib.install.kinit and finally in some cases where support for IPA 4.5.0 is needed still also ipapython.ipautil.
Related: https://github.com/freeipa/freeipa/pull/7286
> ipalib.install.kinit moved to ipalib

- plugins/modules/ipaservice.py
delete_continue defaults to None. The use of continue: None is resulting in an error with the batch command. Therefore only set continue if it is not None.
> ipaservice: Do not set continue to None for service_del

- README-inventory-plugin-freeipa.md
- README.md
- plugins/inventory/freeipa.py
- utils/build-galaxy-release.sh
The inventory plugin compiles a dynamic inventory from IPA domain, filters servers by role(s).
Usage:
Create yml file, for example `freeipa.yml`:
---
plugin: freeipa
server: server.ipa.local
ipaadmin_password: SomeADMINpassword
verify: ca.crt
Get compiled inventory:
ansible-inventory -i freeipa.yml --graph
> New inventory plugin

- roles/ipaserver/library/ipaserver_prepare.py
- roles/ipaserver/module_utils/ansible_ipa_server.py
Use IPAChangeConf and realm_to_ldapi_uri to create IPA_DEFAULT_CONF.
With realm_to_ldapi_uri the ldap_uri is correctly using /run instead of /var/run.
Before IPA_DEFAULT_CONF was created using file operations.
> ipaserver_prepare: Properly create IPA_DEFAULT_CONF

- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipahost.py
This simplified the result_handler and also made the exception_handler
superfluous.
**ansible_freeipa_module: Import and provide normalize_sshpubkey**
normalize_sshpubkey is imported from ipalib.util and also added to
__all__ for use in modules.
> ipahost: Fix idempotency issues 

- README-user.md
A user rename requires "state: renamed". This has been wrong in the example.
> README-user.md: Fix state for user rename in example playbook

- README-group.md
The name tag in the multi rename example is was missing a ":".
> README-group.md: Add missing ":" in multi rename example

- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipagroup.py
- plugins/modules/ipahost.py
- plugins/modules/ipaservice.py
- plugins/modules/ipauser.py
**IPAAnsibleModule: Add support for batch command in execute_ipa_commands**
The method execute_ipa_commands has been extended to handle multi
commands with the batch command.
New constants for execute_ipa_commands debugging:
DEBUG_COMMAND_ALL = 0b1111
DEBUG_COMMAND_LIST = 0b0001
Print the while command list
DEBUG_COMMAND_COUNT = 0b0010
Print the command number
DEBUG_COMMAND_BATCH = 0b0100
Print information about the batch slice size and currently executed
batch slice
New parameters have been added to execute_ipa_commands:
batch: bool
Enable batch command use to speed up processing
batch_slice_size: integer
Maximum mumber of commands processed in a slice with the batch
command
keeponly: list of string
The attributes to keep in the results returned.
Default: None (Keep all)
debug: integer …
> Use batch command internally

- .github/workflows/ansible-test.yml
- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/readme.yml
- .pre-commit-config.yaml
- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipaautomember.py
- plugins/modules/ipadnsforwardzone.py
- plugins/modules/ipadnsrecord.py
- plugins/modules/ipagroup.py
- plugins/modules/ipahost.py
- plugins/modules/iparole.py
- plugins/modules/ipaservice.py
- plugins/modules/ipauser.py
- requirements-dev.txt
- roles/ipareplica/library/ipareplica_add_to_ipaservers.py
- roles/ipareplica/library/ipareplica_prepare.py
Use updated versions of the linter tools, Github actions, pre-commit hooks and fix some new warnings from pylint.
> Bump linter tools versions an fix linter errors

- utils/build-galaxy-release.sh
This fixes a bad tests if offline is not set:
utils/build-galaxy-release.sh: line 130: [: -ne: unary operator expected
Fixes f17f83d6bddd839efa2691ddf88d418e0921d4f0
> utils/build-galaxy-release.sh: Fix unary operator expected (v2)

- plugins/module_utils/ansible_freeipa_module.py
The error string returned by execute_ipa_commands in batch mode additionally contains the whole parameter list for the command. This is different to non batch mode execution and breaks tests that are checking the returned error message.
A left over debug message also have been removed from the error processing.
> ansible_freeipa_module: Fix errors in batch mode

- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipahost.py
- plugins/modules/ipaidoverrideuser.py
- plugins/modules/ipaservice.py
- plugins/modules/ipauser.py
Certificates given by ansible could have leading and trailing white
space, but also multi line input is possible that also could have
leading and training white space and newlines.
> Convert input certificates

- README-service.md
- plugins/modules/ipaservice.py
The service READNE so far lacks the documentation of multi service handling within a single task.
The alias for the continue parameter was also added.
Fixes: #1113
> README-service.md: Add multi service handling

- plugins/modules/ipapermission.py
- tests/permission/test_permission.yml
The parameters
- subtree (ipapermlocation)
- target (ipapermtarget)
- targetto (ipapermtargetto)
- targetfrom (ipapermtargetfrom)
have not been idempotent as the result returned from permission_show was a DN and not a string.
The find_permission function has been exetended to convert the values for these parameters to strings.
Fixes: #1257
> permission: Fix idempotency issues for DN parameters

- plugins/modules/ipauser.py
The alias for idp_user_id was ipaidpconfiglink by mistake. It was already correct (ipaidpsub) in the DOCUMENTATION section and also in the README.
> user: Fix idp_user_id aliases

- tests/sanity/sanity.sh
setuptools might not be installed before importing and using galaxy_importer. This could result in a backtrace by disabling ANSIBLE_TEST_LOCAL_IMAGE in galaxy-importer.cfg to run latest tests.
> tests/sanity/sanity.sh: Install setuptools with pip

- tests/utils.py
Truncate stdout and stderr in the way that it hopefully shows all important information. At least 15 lines of stdout (Ansible tasks) and remaining from stderr to fill up to maxlen size.
The test log mostly only showed lines from stderr as the log was a concatenation of stdout and stderr and only the last 2500 chars of this have been used. This was hiding the test result from stdout and failures have not beeen visible.
> Truncate stdout and stderr in upstream test log

- tests/service/test_services_present.yml
The cleanup of the test services and hosts have been missing, which could lead to a test failure.
> tests/service/test_services_present.yml: Add missing cleanup

- .github/workflows/lint.yml
- .pre-commit-config.yaml
- infra/image/build.sh
- infra/image/dockerfile/c10s
- infra/image/dockerfile/c8s
- infra/image/dockerfile/c9s
- infra/image/dockerfile/fedora-latest
- infra/image/dockerfile/fedora-rawhide
- infra/image/inventory
- infra/image/system-service/fixipaip.service
- infra/image/system-service/fixipaip.sh
- infra/image/system-service/fixnet.service
- infra/image/system-service/fixnet.sh
- tests/azure/build-containers.yml
- tests/azure/templates/build_container.yml
- utils/shfun
- utils/shlog
The new image builder is not using molecule and uses podman directly for the generation of the ansible-test images.
Two additional services are installed to simplify the use of the container in the test:
- fixnet.service uses /root/fixnet.sh to fix IP address of the server in /etc/hosts and to set localhost as the nameserver. This service is executed before IPA is started. This eliminates the need to restart the IPA server after the container has been started and the IPs have been fixed.
- fixipaip.service uses /root/fixipaip.sh to fix the IP address of the IPA dnsrecords of server and ipa-ca.
With these services it is now only needed to wait till all services in the container are started. There is no need to restart the IPA server anymore. Simply use something like this before starting …
> New image builder without molecule using podman

- infra/image/system-service/fixipaip.service
- infra/image/system-service/fixipaip.sh
- infra/image/system-service/fixnet.service
- infra/image/system-service/fixnet.sh
Checks for IPv4 addresses have been added and reverse zone handling for fixipaip.sh
The services are logging StandardOutput and StandardError to journal now.
> infra/image/system-services: Enhance checks, also fix reverse zone

- infra/image/system-service/fixipaip.sh
- infra/image/system-service/fixnet.sh
**infra/image/system-service/fixipaip.sh: Use of admin for kinit call**
The kinit call have been missing the principal.
**infra/image system-services: Fix DNS forwarder**
The DNS forwarder is set while deploying the IPA server. This forwarder
might not be correct later on.
The old /etc/resolv.conf is copied to /etc/resolv.conf.fixnet by the
fixnet service and later on the fixipaip service is trying to get the
nameserver from the copied file. If the retrieval failed of if the
namesever is 127.0.0.1, then the nameserver will be set to 8.8.8.8.
After fixing the IP addresses for the forward and reverse zone, also the
forwarder is set for the dnsserver "${HOSTNAME}".
> Infra image system services dns and kinit

- setup.cfg
This change disables the too-many-positional-arguments message for the pylint github workflow.
> pylint gihub workflow: Disable too-many-positional-arguments

- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipauser.py
So far a datetime object was created for the expiration dates krbpasswordexpiration and krbprincipalexpiration. This resulted in also sending these objects to the API. With this change, the dates are converted into strings using the LDAP_GENERALIZED_TIME_FORMAT defined in ipalib.constants. This way only strings are used with the IPA API.
A new function has been added to ansible_freeipa_module:
- date_string: Convert datetime to gernalized time format string
This fuction is used on the result of user_show to convert the expiration dates to the gernalized time format string.
The existing function date_format in ansible_freeipa_module has been renamed to convert_date and fixed in the way that it also uses date_string to return a gernalized time format string and not a datetime object. This …
> ipauser: Use date string, not datetime object for expiration dates

- README-hbacrule.md
- README-hbacsvcgroup.md
The example playbooks in the hbacrule and hbacsvcgroup READMEs has a small typo.  This just corrects that to be `hosts`.
> fix minor typo in hbacrule and hbacsvcgroup docs

- tests/cert/test_cert_host.yml
- tests/cert/test_cert_service.yml
- tests/cert/test_cert_user.yml
It seems that in recent versions, a minimum of 2048 bits for RSA keys are required to request a certificate. This seems to be enforced by crypto policies.
By adjusting the key size all ipacert tests pass.
> ipacert: Fix ipacert tests

- infra/azure/templates/build_container.yml
- infra/image/dockerfile/fedora-latest
- infra/image/dockerfile/fedora-rawhide
With the release of Fedora 41 there's a need to include DNF 5 libraries so that the image can be built.
The PR also fixes the missing "--privileged" option required to deploy IPA in our container images.
> Update images to Fedora 41

- .github/workflows/lint.yml
- .pre-commit-config.yaml
- requirements-dev.txt
- setup.cfg
- utils/lint_check.sh
Pydocstyle has been deprecated is no longer in development. It is also not a requirement for Ansible tests.
This patch removes pydocstyle from current checks performed.
> linters: Remove pydocstyle from linter checks

- infra/azure/scripts/get_test_modules.py
- infra/azure/scripts/set_test_modules
- infra/azure/templates/run_tests.yml
All scripts related to the Azure CI now reside on inrfa/azure, but the scripts that evaluate the changes made against ansible-freeipa's main development branch.
This patch move these scripts to the proper locations.
> upstream CI: Move scripts that evaluate repo changes to infra/azure

- infra/azure/azure-pipelines.yml
- infra/azure/build-containers.yml
- infra/azure/nightly.yml
- infra/azure/pr-pipeline.yml
- infra/azure/templates/build_container.yml
This patch modify the pipelines to create stages using the 'each' expression on Azure pipelines, so that the configuration and the list of distributions can be set using variables.
Testing CentOS 8 Stream and Galaxy collections still need to be handled in a separate group, although, the pipeline configuration becomes easily changed, specially when updating Ansible versions.
> upstream CI: Use Azure 'loops' to create stages

- README-sudorule.md
- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipasudorule.py
- setup.cfg
- tests/sudorule/test_sudorule.yml
- tests/sudorule/test_sudorule_categories.yml
- tests/sudorule/test_sudorule_client_context.yml
- tests/sudorule/test_sudorule_member_case_insensitive.yml
- tests/sudorule/test_sudorule_single_hostnames.yml
- tests/sudorule/test_sudorules.yml
- tests/sudorule/test_sudorules_member_case_insensitive.yml
Currently, ipasudorule must add or modify a single sudorule at a time, incurring in more load in the server if there are many rules to be processed.
This patch adds suport for adding multiple sudorules in one playbook task by using the parameter 'sudorules' and defining a list of sudorules configurations to be ensured.
As multiple sudorules will be processed, the patch also enables batch mode processing of sudorules, trying to reduce the load on the server.
To be able to process parameter values in the 'sudorules' dictionary, the method to retrieve parameters from the module in lowercase was refactored, allowing any parameter value, either from the module or from a dict, to be converted.
Test 'tests/sudorule/test_sudorule_client_context.yml' was modified to include tasks with 'sudorules' …
> ipasudorule: Add support for batch mode and multiple sudorules

- infra/image/shcontainer
container_copy can be used to copy a file to the container, container_fetch can be used to copy a file from the container.
For more information, please have a look at the podman-cp man page.
> infra/image/shcontainer: New container_copy and container_fetch

- infra/image/dockerfile/c10s
- infra/image/utils/hostnamectl-wrapper
The client part deployment fails in the configuration of NIS. The command /usr/bin/nisdomainname is failing in a container in this task as the container is not privileged.
The hostnamectl-wrapper is copied from the freeipa-container container project to replace /usr/bin/nisdomainname in the container.
> infra/image/dockerfile/c10s: Fix client part deployment for the server

- plugins/modules/ipaautomountmap.py
- plugins/modules/ipaconfig.py
- plugins/modules/ipadelegation.py
- plugins/modules/ipaidoverridegroup.py
- plugins/modules/ipaidoverrideuser.py
- plugins/modules/ipaidp.py
- plugins/modules/ipaidrange.py
- plugins/modules/ipaidview.py
- plugins/modules/ipalocation.py
- plugins/modules/ipapermission.py
- plugins/modules/ipaprivilege.py
- plugins/modules/iparole.py
- plugins/modules/ipaselfservice.py
- plugins/modules/ipaserver.py
- plugins/modules/ipaservicedelegationrule.py
- plugins/modules/ipaservicedelegationtarget.py
- utils/templates/ipamodule+member.py.in
- utils/templates/ipamodule.py.in
When searching for objects with *_show IPA API command, most plugins were hiding errors other than "ipalib_errors.NotFound" by handling the broad exception Exception instead.
This patch uses "ipalib_errors.NotFound" whenever "*_show" is used so that the only exception handled is when an object is not found. Other errors will not be handled making the module break as expected.
Fix #1312
> modules: Do not hide errors using IPA *_show command with Exception

- roles/ipaserver/module_utils/ansible_ipa_server.py
- utils/build-galaxy-release.sh
This change reduces the size of the Ansible collection and removes unused files.
While creating the collection, the role plugins have been linked into the global plugin folders, but a subsequent sed call replaced the links with changed files. The original files have also been changed with another sed call in the same way. This resulted in the duplication of the changed files.
The plugins of the roles are now moved into the global plugin folders and only changed there. The now empty plugin folders in the roles are removed.
> utils/build-galaxy-release.sh: Do not create duplicates for role plugins

- plugins/modules/ipacert.py
- tests/cert/test_cert_remove_hold_with_removeFromCRL.yml
When a revoked certificate with reason 6 (certificateHold) is revoked with reason 8 (removeFromCRL), the effect is that the certificate is valid again, as it is the same procedure as 'state: release'.
This is, at least, the behavior with IPA CLI comands, which is implemented by this patch.
A new test is added to verify this behavior:
tests/cert/test_cert_remove_hold_with_removeFromCRL.yml
Fixes [RHEL-70021](https://issues.redhat.com/browse/RHEL-70021)
> ipacert: Revoking with  removeFromCRL should be handled as cert release

- plugins/modules/ipasudorule.py
- tests/sudorule/test_sudorule_user_host_external.yml
When handling users and hosts is ipasudorule we were missing nome entry attributes returned from FreeIPA, which would cause the add/del lists to be incorrectly generated.
By adding the proper lists, both attributes are handled correctly.
A new test to verify the fix is added:
tests/sudorule/test_sudorule_user_host_external.yml
Fixes https://issues.redhat.com/browse/RHEL-68439
> ipasudorule: Evaluate all members related to hosts and users

- roles/ipareplica/README.md
- roles/ipareplica/library/ipareplica_create_ipa_conf.py
- roles/ipareplica/library/ipareplica_install_ca_certs.py
- roles/ipareplica/library/ipareplica_prepare.py
- roles/ipareplica/library/ipareplica_setup_ds.py
- roles/ipareplica/library/ipareplica_setup_kra.py
- roles/ipareplica/library/ipareplica_test.py
- roles/ipareplica/tasks/install.yml
The IP addresses set with ipareplica_ip_addresses have not been passed to ipaclient role for client deployment part. This resulted in not setting the IP addresses.
The description for ipareplica_ip_addresses in the ipareplica README and also the role modules was wrong and have been fixed to "List of IPA replica IP addresses".
Related: https://pagure.io/freeipa/issue/7405
Resolves: https://github.com/freeipa/ansible-freeipa/issues/1244
> ipareplica: Pass ipareplica_ip_addresses to client deployment part

- README.md
- roles/ipabackup/README.md
- roles/ipaclient/README.md
- roles/ipaclient/vars/Fedora-25.yml
- roles/ipaclient/vars/Fedora-26.yml
- roles/ipaclient/vars/RedHat-7.3.yml
- roles/ipareplica/README.md
- roles/ipareplica/vars/Fedora-25.yml
- roles/ipareplica/vars/Fedora-26.yml
- roles/ipareplica/vars/Fedora-27.yml
- roles/ipaserver/README.md
- roles/ipaserver/vars/Fedora-25.yml
- roles/ipaserver/vars/Fedora-26.yml
- roles/ipaserver/vars/Fedora-27.yml
- roles/ipasmartcard_client/README.md
- roles/ipasmartcard_server/README.md
This patch removes 'vars' files from roles for unsupported distributions and change minimum supported Fedora to version 34+.
> Remove 'vars' files of unsupported distributions

- README-group.md
- plugins/module_utils/ansible_freeipa_module.py
- plugins/modules/ipagroup.py
- tests/env_freeipa_facts.yml
- tests/group/test_group.yml
- tests/group/test_group_ad_users.yml
- tests/group/test_group_client_context.yml
- tests/group/test_group_external_members.yml
- tests/group/test_group_idoverrideuser.yml
When using AD objects, a user expects to use the more human readable
form, like "user@ad.domain", but this impose some dificulties on
evaluating which object is being referenced as AD has several forms to
refer to the same object.
Each object is AD is identified uniquely by its SID, and this is the
identifier that IPA stores in its database. When managing AD objects,
IPA finds its SID and works with that value.
ansible-freeipa tried to process these objects using the human readable
values, and it cause idempontence error when ensuring the values were
present or modified, and, at least in some cases, prevented the objects
to be made absent, as the object list created didn't match the SID to
the value used as module parameter.
By using SID to process the AD objects in ipagroup, the addition …
> ipagroup: Fix management of AD objects

- roles/ipaclient/library/ipaclient_setup_nss.py
- roles/ipareplica/module_utils/ansible_ipa_replica.py
- roles/ipaserver/module_utils/ansible_ipa_server.py
This is a hotfix to allow deployments of clients, replicas and servers with the dns_over_tls PR for freeipa: https://github.com/freeipa/freeipa/pull/7343/
ipaclient: client.update_ssh_keys has changed parameters, options.dns_over_tls needs to be set for ipaclient_setup_nss.
ipareplica, ipaserver: Set new parameters globally in module_utils so far: options.dns_over_tls, options.dns_over_tls_key, options.dns_over_tls_cert, options.dot_forwarders and options.dns_policy.
The enablement for DNS over TLS for the deployment roles will be done later on.
> ipa* deployment roles: Hotfix for dns_over_tls (Freeipa#7343)

- roles/ipareplica/module_utils/ansible_ipa_replica.py
Python's module "pkg_resources" API has been deprecated in Python 3.12 and will be removed in a future release, and recent FreeIPA versions provide a replacement for pkg_resources.parse_version.
To remove ansible-freeipa dependency on pkg_resources and not add a dependency on the 'packaging' module, which is not available in the standard Python distribution, we'll try to import the funcion used in FreeIPA to parse versions, and fallback to pkg_resources when it fails.
As an equivalent class is needed, a fallback function is not provided and execution will fail if neither the FreeIPA nor the pkg_resources parse_version function are available.
> ipareplica: Don't rely on pkg_resources whenever possible

- infra/image/shcontainer
- infra/image/shdefaults
Debugging is now enabled by default in the containers that are generated with container_create. "+SYS_PTRACE" has been added to CAP_DEFAULTS in shdefaults for this.
> infra/image/shdefaults: Add SYS_PTRACE to CAP_DEFAULTS

- roles/ipaclient/library/ipaclient_setup_sssd.py
This change addresses [[freeipa/ansible-freeipa#1356](https://github.com/freeipa/ansible-freeipa/issues/1356#issuecomment-2891804763)](https://github.com/freeipa/ansible-freeipa/issues/1356#issuecomment-2891804763) by explicitly setting `options.dns_over_tls = False` to ensure the attribute is always defined when running ipaclient ansible role.
On RHEL 9 systems (or any environment where `ipasssd_enable_dns_updates: true`), the `ipaclient` python module references `dns_over_tls` without first checking its existence, which results in the following `AttributeError: 'installer_obj' object has no attribute 'dns_over_tls'`:
```
TASK \[freeipa.ansible\_freeipa.ipaclient : Install - Configure SSSD] \*\*\*\*\*\*\*\*\*\*\*\*
An exception occurred during task execution. To see the full traceback, …
```
> ipaclient: Fix AttributeError by defaulting dns_over_tls to False

- roles/ipareplica/module_utils/ansible_ipa_replica.py
- roles/ipaserver/module_utils/ansible_ipa_server.py
When running under Mitogen, ipa_server and ipa_replica breaks execution by overwriting sys.stdout with sys.stdout.
With Mitogen, sys.stdout != sys.stdout at this point in the code, and changing it in this manner results in access to closed file descriptors for future invocations. Generally, it is recommended not to use sys.stdout and instead explicitly cache the current value of sys.stdout as proposed in this PR.
> Cache sys.stdout instead of assuming it is equal to sys.__stdout__
