freeipa/ansible-freeipa

library/ipahost.py

The module had unused imports preventing execution with an IPA 4.4 server.
The commit removes unneeded imports, and adds documentation details.

ipahost module: fix the module for IPA 4.4 server

---

setup.cfg
setup.py

This enables easy installation of these roles through pip.

Introduce setup files that copy roles to relevant directories

---

roles/ipaclient/vars/CentOS-7.yml
roles/ipareplica/vars/CentOS-7.yml
roles/ipaserver/library/ipaserver_setup_ca.py
roles/ipaserver/library/ipaserver_setup_kra.py
roles/ipaserver/tasks/install.yml
roles/ipaserver/vars/CentOS-7.yml

Changes required to make this module work with CentOS 7.5.

CentOS 7 Compatibility

---

setup.cfg

Added a small update so that setup.cfg contains all the necessary roles, should the user want to do that to install it

Updated setup.cfg to include all the necessary roles

---

roles/ipaclient/tasks/install.yml

Correcting small typo for lenth to length in a check

ipaclient install role length typo

---

plugins/modules/ipagroup.py

The ipagroup module was not using the failed and completed items in the dict
that is returned with api_command. But it was creating add and remove
lists for users, groups and services. This is not needed if the failures
"already a member" and "not a member" in the result failures are ignored.
Only other failures are reported.

ipagroup: Rework to use same mechanisms as ipahostgroup module

---

roles/ipaclient/tasks/install.yml

Allows predefining otp for ipaclient role using variable ipaclient_otp

Added support for predefining client OTP using ipaclient_otp

---

README-user.md
plugins/modules/ipauser.py
tests/user/test_users.yml

What would you think about supporting an LDAP-style alias for 'last'?

Support 'sn' alias of 'last' for surname

---

plugins/module_utils/ansible_freeipa_module.py

This patch allows the connection to the ipa api to use a context different
than 'server', if needed.

Added context configuration to api_connect.

---

README.md
roles/ipareplica/tasks/install.yml
roles/ipareplica/vars/CentOS-7.yml
roles/ipareplica/vars/Fedora-25.yml
roles/ipareplica/vars/Fedora-26.yml
roles/ipareplica/vars/Fedora-27.yml
roles/ipareplica/vars/Fedora.yml
roles/ipareplica/vars/RedHat-7.3.yml
roles/ipareplica/vars/RedHat-7.yml
roles/ipareplica/vars/RedHat-8.yml
roles/ipareplica/vars/Ubuntu.yml
roles/ipareplica/vars/default.yml
roles/ipaserver/tasks/install.yml
roles/ipaserver/vars/CentOS-7.yml
roles/ipaserver/vars/Fedora-25.yml
roles/ipaserver/vars/Fedora-26.yml
roles/ipaserver/vars/Fedora-27.yml
roles/ipaserver/vars/Fedora.yml
roles/ipaserver/vars/RedHat-7.3.yml
roles/ipaserver/vars/RedHat-7.yml
roles/ipaserver/vars/RedHat-8.yml
roles/ipaserver/vars/Ubuntu.yml
roles/ipaserver/vars/default.yml

Fix install packages in ipaserver and ipareplica roles

---

plugins/modules/ipauser.py

If there is no domain set for email addresses, extend the email addresses
with the default email domain that is gathered from the config_show output.
This fixes RHBZ#1747413 ([ansible-freeipa] user module throwing an error if..)

ipauser: Extend email addresses with default email domain if no domain is set

---

roles/ipaclient/library/ipaclient_test.py

This fixes #193, and is based on PR #176.

Removes invalid and unnecessary calls to logger.info.

---

README-sudorule.md
playbooks/sudorule/ensure-sudorule-does-not-have-sudooption.yml
playbooks/sudorule/ensure-sudorule-has-sudooption.yml
playbooks/sudorule/ensure-sudorule-is-present-with-order.yml
playbooks/sudorule/ensure-sudorule-is-present.yml
playbooks/sudorule/ensure-sudorule-runasuser-is-absent.yml
playbooks/sudorule/ensure-sudorule-runasuser-is-present.yml
plugins/modules/ipasudorule.py
tests/sudorule/test_sudorule.yml

This patch adds the following attributes to ipasudorule:
- order
- sudooption
- runasuser
- runasgroup

Add missing attributes to ipasudorule.

---

README-service.md
plugins/modules/ipaservice.py

Add missing documentation for the `principal` variable.

Fixes documentation for module ipaservice.

---

README-dnszone.md
README.md
playbooks/dnszone/disable-zone-forwarders.yml
playbooks/dnszone/dnszone-absent.yml
playbooks/dnszone/dnszone-all-params.yml
playbooks/dnszone/dnszone-disable.yml
playbooks/dnszone/dnszone-enable.yml
playbooks/dnszone/dnszone-present.yml
plugins/module_utils/ansible_freeipa_module.py
plugins/modules/README.md
plugins/modules/ipadnszone.py
tests/dnszone/test_dnszone.yml
tests/dnszone/test_dnszone_mod.yml

Added module to handle ipa `dnszone-add`, `dnszone-del`, `dnszone-mod`, `dnszone-enable` and `dnszone-disable`.
This PR also proposes a base class to implement our modules in ansbile-freeipa.

DNSZone module

---

plugins/module_utils/ansible_freeipa_module.py

When accessing an instance of AnsibleFreeIPAParams with .get the obj was by-passing the call to _afm_convert which was the primaty reason why it was created.
Also the class now extends Mapping instead of dict.

Fixed a bug in AnsibleFreeIPAParams

---

tests/sudorule/test_sudorule.yml

This patch adds tests for some options that were not being tested, and enhances test behavior.

Sudorule test enhancement

---

azure-pipelines.yml
plugins/module_utils/ansible_freeipa_module.py
plugins/modules/ipadnsconfig.py
plugins/modules/ipagroup.py
plugins/modules/ipahost.py
plugins/modules/ipauser.py
roles/ipaclient/action_plugins/ipaclient_get_otp.py
roles/ipaclient/files/py3test.py
roles/ipaclient/library/ipaclient_api.py
roles/ipaclient/library/ipaclient_get_facts.py
roles/ipaclient/library/ipaclient_get_otp.py
roles/ipaclient/library/ipaclient_test.py
roles/ipareplica/files/py3test.py
roles/ipaserver/files/py3test.py
setup.cfg

Addresses #241 (but does not close)

Add flake8 and pydocstyle lints

---

pytest.ini
tests/README.md
tests/ansible.cfg
tests/test_playbook_runs.py

Allow to run tests using pytest.

Added pytests as test entrypoint

---

plugins/modules/ipadnsconfig.py
tests/dnsconfig/test_dnsconfig.yml

This fixes reporting errors on dnsconfig module and add some tests
to verify that invalid IP addresses cannot be used as forwarders.

Fixes error handling on dnsconfig module.

---

README-host.md
README-service.md

Adhere to recent changes on FreeIPA CLI help messages.
Also, see: https://tools.ietf.org/id/draft-knodel-terminology-01.html

Terminology improvements: use allow list.

---

roles/ipareplica/README.md

This PR just fixes a variable name error in the README.md file

Fix variable name error

---

roles/ipaclient/vars/OracleLinux-7.yml
roles/ipaclient/vars/OracleLinux-8.yml
roles/ipareplica/vars/OracleLinux-7.yml
roles/ipareplica/vars/OracleLinux-8.yml
roles/ipaserver/vars/OracleLinux-7.yml
roles/ipaserver/vars/OracleLinux-8.yml

These are copies of the Red Hat Enterprise linux files.

ipa[server,replica,client]: New OracleLinux vars files

---

README-role.md
README-service.md
plugins/modules/iparole.py
plugins/modules/ipavault.py

This PR fixes some documentation issues found on ansible-freeipa modules. The modules affected are:
* ipavault
* ipaservice
* iparole
See individual commit entries for details.

Fix some documentation issues.

---

README-dnszone.md
plugins/module_utils/ansible_freeipa_module.py
plugins/modules/ipadnszone.py
tests/dnszone/test_dnszone.yml

Added the possibility to remove multiple dnszone entries at once. Code, tests, documentation and README were updated.

Allow to manage multiple dnszone entries.

---

README-location.md
playbooks/location/location-absent.yml
playbooks/location/location-present.yml
plugins/modules/ipalocation.py
tests/location/test_location.yml

There is a new location management module placed in the plugins folder:
plugins/modules/ipalocation.py
The location module allows to ensure presence or absence of locations.
README-location.md
playbooks/location/location-absent.yml
playbooks/location/location-present.yml
tests/location/test_location.yml

New location management module

---

molecule/default
molecule/resources/playbooks/library
molecule/resources/playbooks/module_utils
molecule/resources/playbooks/roles

Remade all symlinks so that they are relative (and therefore portable).
I ran into problems building my own collection artifact as I'm not scampos :-)

Fixed symlinks to be not absolute

---

roles/ipaclient/library/ipaclient_setup_firefox.py
roles/ipaclient/tasks/install.yml

Fix domain not being passed for configuring firefox

---

README-permission.md
playbooks/permission/permission-absent.yml
playbooks/permission/permission-allow-read-employeenum.yml
playbooks/permission/permission-member-absent.yml
playbooks/permission/permission-member-present.yml
playbooks/permission/permission-present.yml
playbooks/permission/permission-renamed.yml
plugins/modules/ipapermission.py
tests/permission/test_permission.yml

I made a rough attempt at a new permissions module. 
Ideally when this is completed it will close out #377.

[WIP] Initial Attempt at Permissions Module

---

utils/gen_modules_docs.sh

error[SC2148]: Tips depend on target shell and yours is unknown.
Add a shebang.

utils/gen_modules_docs.sh: Fix covscan findings

---

.github/workflows/lint.yml
plugins/modules/ipadnsrecord.py
requirements-dev.txt
tests/utils.py

This patch fixes all issues on the codebase so that  flake8-bugbear plugin can be enabled.
It also prepares configuration to take advantage of bugbear if it is installed, and change Python linters Github action to use bugbear on every commit.
This is part of the the lint verifications in issue #241.

Tools flake8 bugbear

---

playbooks/permission/permission-absent.yml
playbooks/permission/permission-allow-read-employeenum.yml
playbooks/permission/permission-member-absent.yml
playbooks/permission/permission-member-present.yml
playbooks/permission/permission-present.yml
playbooks/permission/permission-renamed.yml

This patch fixes a few issues with ipapermission example playbooks.
Commit 873b691 fixes [RHBZ#1921654](https://bugzilla.redhat.com/show_bug.cgi?id=1921654).

Fix ipapermission example playbooks

---

.github/workflows/docs.yml
roles/ipaclient/library/ipaclient_get_facts.py
roles/ipaclient/library/ipaclient_test.py

This patch forces installation of ansible modules before executing
ansible-doc-test.

Fix execution of Github Workflow to verify ansible docs.

---

README.md

Signed-off-by: Robbie Harwood <rharwood@redhat.com>

Various spelling/style fixes in README.md

---

plugins/modules/ipahostgroup.py

Use gen_add_list and gen_intersection_list for host, hostgroup,
membermanager_user and membermanager_group member handling.
The functions are used to reduce the add lists to the new entries
only and the delete lists to the entries that are in the user and
the show list result.
This enables to remove the ignores for "already a member" and
"not a member" errors..

hostgroup: Reduce addition and deletion of members to changed only

---

plugins/modules/ipagroup.py

Use gen_add_list and gen_intersection_list for user, group, service,
externalmember, membermanager_user and membermanager_group member
handling.
The functions are used to reduce the add lists to the new entries
only and the delete lists to the entries that are in the user and
the show list result.
This enables to remove the ignores for "already a member" and
"not a member" errors..

group: Reduce addition and deletion of members to changed only

---

README-automountlocation.md
playbooks/automount/automount-location-absent.yml
playbooks/automount/automount-location-present.yml
plugins/modules/ipaautomountlocation.py
tests/automount/test_automountlocation.yml

Add module to create and manage auotmount locations from ansible

add module to create and manage automount locations

---

.pre-commit-config.yaml

Update version of tools used in pre-commit hooks.

pre-commit: Update version of pre-commit hooks.

---

plugins/modules/ipasudorule.py

Use gen_add_list and gen_intersection_list for host, hostgroup, user,
group, allow_sudocmd, allow_sudocmdgroup, deny_sudocmd, deny_sudocmdgroup,
sudooption, runasuser, runasgroup and res_find member handling.
The functions are used to reduce the add lists to the new entries
only and the delete lists to the entries that are in the user and
the show list result.
This enables to remove the ignores for "already a member" and
"not a member" errors..

sudorule: Reduce addition and deletion of members to changed only

---

README-host.md
playbooks/host/host-member-allow_create_keytab-absent.yml
playbooks/host/host-member-allow_create_keytab-present.yml
playbooks/host/host-member-allow_retrieve_keytab-absent.yml
playbooks/host/host-member-allow_retrieve_keytab-present.yml
playbooks/host/host-member-managedby_host-absent.yml
playbooks/host/host-member-managedby_host-present.yml
playbooks/host/host-present-with-allow_create_keytab.yml
playbooks/host/host-present-with-allow_retrieve_keytab.yml
playbooks/host/host-present-with-managedby_host.yml
playbooks/host/hosts-member-certificate-absent.yml
playbooks/host/hosts-member-certificate-present.yml
playbooks/host/hosts-member-managedby_host-absent.yml
playbooks/host/hosts-member-managedby_host-present.yml
playbooks/host/hosts-member-principal-absent.yml
playbooks/host/hosts-member-principal-present.yml
playbooks/host/hosts-present-with-certificate.yml
playbooks/host/hosts-present-with-managedby_host.yml
playbooks/service/service-member-principal-absent.yml
playbooks/service/service-member-principal-present.yml

This changes exmaple to example.

playbooks, README-host: Change exmaple to example

---

.github/workflows/lint.yml
.pre-commit-config.yaml
utils/build-galaxy-release.sh
utils/build-srpm.sh
utils/gen_modules_docs.sh
utils/lint_check.sh
utils/new_module

Add Shellcheck verification as a pre-commit hook and as a PR check.

CI: Add supoprt for Shellcheck

---

roles/ipabackup/vars/Ubuntu-18.04.yml
roles/ipaclient/vars/Ubuntu-18.04.yml
roles/ipareplica/vars/Ubuntu-18.04.yml
roles/ipaserver/vars/Ubuntu-18.04.yml

Recently added Ubuntu configuration filesi for roles miss document
start marker.

yamllint: Fix missing document start.

---

plugins/modules/ipaservice.py

This PR refactors ipaservice to reduce the number of variables (in
favor of a 'struct') and to group member management code so that it
can be leveraged, and not partially duplicated, between the states
and actions.
Although this code is less direct that the previous one, it will reduce the
number fo changes to be made if changes to member management is
required.
This PR must be merged after #668, on which it is based.

ipaservice: code refactor

---

site.yml

Remove the file 'site.yml' which is not needed or used anymore.

Remove unused, old example of ipaclient deploy.

---

.github/workflows/docs.yml

Execute Github workflow for ansibel-doc-test using ansible-core 2.12.

upstream CI: Enable ansible-doc-test for ansible-core 2.12.

---

utils/build-galaxy-release.sh

The script is now using a build dir for the creation of the Ansible
Collection. Additionally only files known to the fit repo are pulled in
by default. The new "-a" option is pulling in all files from local repo.
The new -k" option can be used to keep the build dir for verification of
the changes to the files.
The colleciton is placed into the main repo dir and no git reset --hard
is used in the repo to preserve local changes.

build-galaxy-release.sh: Use build dir, new options, checks, no reset

---

roles/ipaserver/library/ipaserver_prepare.py
roles/ipaserver/module_utils/ansible_ipa_server.py

ERROR: Found 6 pylint issue(s) which need to be resolved:
ERROR: plugins/modules/ipaserver_prepare.py:395:4: invalid-name: Variable name "e" doesn't conform to snake_case naming style
ERROR: roles/ipaserver/library/ipaserver_prepare.py:395:4: invalid-name: Variable name "e" doesn't conform to snake_case naming style
ERROR: roles/ipaserver/module_utils/ansible_ipa_server.py:333:12: invalid-name: Variable name "ds" doesn't conform to snake_case naming style
ERROR: roles/ipaserver/module_utils/ansible_ipa_server.py:348:12: invalid-name: Variable name "ds" doesn't conform to snake_case naming style
ERROR: roles/ipaserver/module_utils/ansible_ipa_server.py:361:12: invalid-name: Variable name "ip" doesn't conform to snake_case naming style
ERROR: …

ansible-test: Fix new findings

---

.github/workflows/readme.yml

The test is now also checking that role README files are mentioned in
the main README.

README test: Also check role readme files

---

plugins/modules/ipasudorule.py
tests/sudorule/test_sudorule_member_case_insensitive.yml

This change refactors member management for ipasudorule module and
fixes idempotence issues related to case insensitive comparison.
Fixes #589

sudorule: fix idempotence issues and refactor.

---

tests/servicedelegationtarget/test_servicedelegationtarget.yml

List tests, also an empty list test has been added.

test_servicedelegationtarget.yml: Added list tests

---

roles/ipaclient/tasks/install.yml
tests/config/test_config.yml
tests/env_freeipa_facts.yml
tests/role/test_role_lists_handling.yml
tests/vault/test_vault_change_type.yml

New issues have been reported as issues by new ansible-lint:
- Upper case var names in tasks
- Unnamed tasks

Fix new ansible-lint findings

---

tests/sanity/sanity.sh

When running tests/sanity/sanity.sh locally, podman might be available
instead of Docker. Due to current configuration, only Docker is used by
sanity.sh.
This patch searches for the availability of docker, which is kept as
the default container engine to use, and use podman only if docker is
not found.
This change also allows the execution of the script from a directory
other than the repository root.

sanity.sh: Allow use of podman instead of docker

---

tests/backup_role/test_backup.yml

A new test playbook for ipabackup role can be found at:
tests/role_backup/test_backup.yml
The test is not yet complete, as 'state: restored' is not tested.

ipabackup: Add playbook tests for ipabackup.

---

utils/ansible-freeipa.spec.in

The spec file was updated and was lacking several updates.

utils/ansible-freeipa.spec.in: Sync with Fedora rawhide spec file

---

plugins/modules/ipadnszone.py

- `type` tag needs to match `argument_spec`
RETURN section
- `type: dict` needs to be given for dicts
- `contains` needs to be used instead of `options` for dicts
- `type: str` needs to be used for …

ipadnszone: Fix documentation sections and agument spec

---

plugins/modules/ipapermission.py

- `choices` needs to match `argument_spec`
argument_spec

ipapermission: Fix documentation sections and agument spec

---

plugins/modules/ipaservice.py

- all parameters need to be defined
argument_spec
- `no_log=False` or `no_log=True` needs to be set for all parameters that have `key` in the name or for dicts also in one the key names
The `copyright` date is extended …

ipaservice:: Fix documentation sections and agument spec

---

roles/ipaclient/library/ipaclient_setup_nss.py

In case get_certs_from_ldap failed with errors.NoCertificateError the code lead to a trace back as certstore.make_compat_ca_certs was using with undefined ca_certs variable.
The code to generate ca_certs for this case was copied over from ipaclient_api. This is loading the certificate list from paths.IPA_CA_CRT.

ipaclient_setup_nss: Fix undefined ca_certs for NoCertificateError case

---

.github/workflows/docs.yml
.github/workflows/lint.yml
.pre-commit-config.yaml
plugins/module_utils/ansible_freeipa_module.py
plugins/modules/ipaautomountmap.py
plugins/modules/ipadnszone.py
requirements-dev.txt
requirements-tests.txt
utils/get_test_modules.py

Update development and Github workflow tools versions to match the versions available on Fedora 37.

Update development and Github workflow tools.

---

.ansible-lint
roles/ipabackup/meta/main.yml
roles/ipabackup/tasks/backup.yml
roles/ipabackup/tasks/copy_backup_from_server.yml
roles/ipabackup/tasks/copy_backup_to_server.yml
roles/ipabackup/tasks/main.yml
roles/ipabackup/tasks/restore.yml
roles/ipaclient/meta/main.yml
roles/ipaclient/tasks/install.yml
roles/ipareplica/meta/main.yml
roles/ipareplica/tasks/install.yml
roles/ipaserver/meta/main.yml
roles/ipaserver/tasks/copy_external_cert.yml
roles/ipaserver/tasks/install.yml
roles/ipasmartcard_client/meta/main.yml
roles/ipasmartcard_client/tasks/main.yml
roles/ipasmartcard_server/meta/main.yml
roles/ipasmartcard_server/tasks/main.yml

This PR fixes several ansible-lint warnings on ansible-freeipa roles.
Please, see individual commits for details on the issues fixed.

Fix ansible-test lint warnings in roles.

---

plugins/modules/ipapwpolicy.py

With 4.9.10, the value of bools have been changed from "TRUE" and "FALSE" to real bool values.
With IPA < 4.9.10 the new bool checks distcheck and usercheck failed the tests for enabling the checks with a "already enabled" error.
A new version check altogether with providing the ansible module for gen_args has been added. The values True and False are now transformed into "TRUE" and "FALSE" for IPA < 4.9.10.
The function bool_param has been renamed to bool_or_empty_param to match the int_or_empty_param and to have a more explaining name.

pwpolicy: Fix new bool checks for IPA prior to 4.9.10

---

README-user.md
plugins/modules/ipauser.py
tests/user/test_user.yml
tests/user/test_users.yml

ipauser plugin was missing user parameter "street".
Fixes #1041

ipauser: Add support for parameter "street"

---

plugins/module_utils/ansible_freeipa_module.py

Fix ipa_command_invalid_param_choices for IPA 4.6 (RHEL-7)
- krbprincipalauthind in host_add does not have choices defined
- krbprincipalauthind in service_add does not have choices defined
api.Command[command].params[name].cli_metavar returns "STR" and ast.literal_eval failes with a ValueError "malformed string".
There is no way to verify that the given values are valid or not in this case. The check is done later on while applying the change with host_add, host_mod, service_add and service_mod.

ansible_freeipa_module: Fix ipa_command_invalid_param_choices

---

utils/run-tests.sh

Sometimes it is hard to debug an Azure failure due to the current log implementation and some tests are failing due to the order of execution.
As the order of execution is pseudo-random, based o a seed, this patch allows to replicate the same test order by using the seed and the desired group as arguments to `utils/run-tests.sh`.
Refer to individual commits for details.

Reproduce upstream CI groups in developer's machine

---

tests/azure/templates/variables.yaml

This reverts commit de3c6c0ace1f67f95fb8a347c078db0659b9532f.

Revert "[TEMP] Enable only idp, service and user module tests"

---

utils/build-galaxy-release.sh

Two new options have been added to enable the offline build within rpm:
-o <A.B.C>  Build offline without using git, using version A.B.C
Also enables -a
-p <path>   Use path for the installation of the generated collection
(use with -i)
Example usage:
utils/build-galaxy-release.sh -o 1.12.1 -i \
-p %{buildroot}%{_datadir}/ansible/collections \
freeipa ansible_freeipa

utils/build-galaxy-release.sh: Enable offline generation for rpm

---

roles/ipaclient/library/ipaclient_configure_dns_resolver.py

The changed state returned from ipaclient_configure_dns_resolver was always True. The internal functions (copies from FreeIPA code) have been fixed to return a changed state.
Fixes: #1217 (ipaclient: Configure DNS resolver always reports as changed)

ipaclient_configure_dns_resolver: Return proper changed state

---

plugins/modules/ipauser.py

These are manager, principal, certificate and certmapdata.
The result_handler function has been adapted and the exception_handler function has been removed.
A new function has been added:
convert_certificate

ipauser: Fix idempotency issues for members

---

plugins/inventory/freeipa.py

The bindings for requests and urllib3 might not be available, especially in the ansible-test fake execution test (next version). These imports are now in a try exception clause to make sure that the fake execution test will be passing and also that there is a better error message if the bindings are missing.
urllib3.exceptions.InsecureRequestWarning is now also only disabled if no certificate has been given for the verification of the connection.

plugins/inventory/freeipa: Try imports for requests and urllib3

---

README-host.md

This is just a small documentation change.

README-host.md: correction of managedby_host description

---

.yamllint
infra/image/dockerfile/c10s
playbooks/dnszone/dnszone-all-params.yml
playbooks/vault/vault-is-present-with-password-file.yml
playbooks/vault/vault-is-present-with-public-key-file.yml
roles/ipaclient/tasks/install.yml
roles/ipaclient/tasks/uninstall.yml
roles/ipaclient/vars/Fedora-25.yml
roles/ipaclient/vars/Fedora-26.yml
roles/ipaclient/vars/RedHat-7.3.yml
roles/ipaclient/vars/RedHat-7.yml
roles/ipaclient/vars/default.yml
roles/ipareplica/defaults/main.yml
roles/ipaserver/defaults/main.yml
roles/ipaserver/tasks/uninstall.yml
roles/ipasmartcard_client/tasks/main.yml
roles/ipasmartcard_server/tasks/main.yml
tests/ca-less/install_replica_without_ca.yml
tests/ca-less/install_server_without_ca.yml
tests/cert/test_cert_host.yml
tests/cert/test_cert_user.yml
tests/external-signed-ca-with-automatic-copy/install-server-with-external-ca-with-automatic-copy.yml
tests/external-signed-ca-with-manual-copy/install-server-with-external-ca-with-manual-copy.yml
tests/group/test_group.yml
tests/host/test_host.yml
tests/user/test_user.yml
tests/user/test_users.yml
tests/vault/env_setup.yml

This patch updates the base image for CentOS 10 Stream tests.
While fixing this issue, `ansible-lint` complained about the current yamllint configuration we used, so the PR has both commits.

Update c10s image

---

.pre-commit-config.yaml
requirements-dev.txt
roles/ipaclient/module_utils/ansible_ipa_client.py

Fixes flake8 issue with 7.2.0 and update linter configuration.

Fix flake8 7 2 0
